### ISSUE TITLE
Filter gossip transactions when received from peer

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#1011]
If Alice adds A, B and C and gossips this to Bob, Bob adds those transactions to the gossip list for Alice. This is not needed since it's clear Alice already has them.

**Comment by gerardsn** [comment]
Isn't this already done by:
https://github.com/nuts-foundation/nuts-node/blob/86cbfad2a5d348e07ea3af4eb554e2e2972199e6/network/transport/v2/gossip/manager.go#L45-L48
What is on the log doesn't get Gossiped to the peer.

**Comment by woutslakhorst** [comment]
You're correct

**Comment by woutslakhorst** [comment]
Not all gossiped transactions are removed from the queue, only those that are new to Bob. Those that Bob already has should also be removed from the queue for Alice. This happens when those TXs are gossiped through Charlie
