### ISSUE TITLE
VCR: Assert that all fields in a VC are defined by the context

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1032]
When issuing a VC, we must validate that all fields are defined by the JSON-LD context(s). Otherwise the integrator could falsely assume the extra fields are protected by the signature (which they are not). Or when integrations contains bugs (incorrect field names) it could cause vulnerabilities (e.g. `usercontext` instead of `userContext` for a `NutsAuthorizationCredential`, leading to a user identity not being required when exchanging medical data).

**Comment by reinkrul** [comment]
RFC014 specifies `legalBase`, but this isn't included in the context;

```
  "legalBase": {
    "consentType": "explicit",
    "evidence": {
      "path": "pdf/f2aeec97-fc0d-42bf-8ca7-0548192d4231",
      "type": "application/pdf"
    }
```

We can't add this to the context, because that will break existing VCs on the dev and stable network.

**Comment by woutslakhorst** [comment]
A new context will be created including the legalBase
