### ISSUE TITLE
Storage: research privacy requirements regarding encryption/partitioning of sensitive data

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1034]
E.g. social security numbers/BSN, what requirements are there to store them encrypted/partitioned (by customer). What laws are they subject to/NEN?

@woutslakhorst ?

**Comment by woutslakhorst** [comment]
GDPR, NEN7510, NEN7512

A BSN alone isn't very useful information. An attacker would have to get hold of personal information and the BSN first. Then with the data within the credentials, the attacker could defer what type of decease somebody has.

Encryption is commonly required when placing data on portable media on when in transfer. Encryption at rest is not required (yet)

**Comment by woutslakhorst** [comment]
Removing it from the milestone

**Comment by woutslakhorst** [comment]
With the removal of the network and introduction of SQL, encryption at rest can now be handled by the DB.
