### ISSUE TITLE
Network: TransactionList chunks can be larger than max allowed message size

### ISSUE THREAD

**Issue by gerardsn** [nuts-foundation/nuts-node#1063]
https://github.com/nuts-foundation/nuts-node/pull/1043 increased the message overhead.

https://github.com/nuts-foundation/nuts-node/blob/ee9f7bafe953fe1729efbc1b028e996658faff48/network/transport/v2/senders.go#L30
^ is no longer sufficient

**Comment by gerardsn** [comment]
Can often be reproduced by https://github.com/nuts-foundation/nuts-go-e2e-test/pull/21

The test only uses new/empty DIDs, so I would expect them all to be the same size. However, the amount of bytes over the limit varies. Below is from 3 different runs
rpc error: code = ResourceExhausted desc = trying to send message larger than max (524305 vs. 524288)
rpc error: code = ResourceExhausted desc = trying to send message larger than max (524363 vs. 524288)
rpc error: code = ResourceExhausted desc = trying to send message larger than max (524376 vs. 524288)

**Comment by woutslakhorst** [comment]
Adding 2 bytes per TX as overhead should give a safe margin?
