### ISSUE TITLE
Incorrect search results on closely matching indexed values

### ISSUE THREAD

**Issue by ltieleman** [nuts-foundation/nuts-node#1086]
The phonetic name search implementation sometimes gives back illogical search results. See screenshot below.
It would make sense to (at least) include the organizations for which the beginning of the name matches the query param input.

![image](https://user-images.githubusercontent.com/105062116/167150752-36d6d9b1-046d-478b-8519-9a8d6f1262d3.png)

**Comment by woutslakhorst** [comment]
The low level phonetic values for `zorgwaard`:

```
"Zorg" = "874"
"Zorgw" = "8743"
"Zorgwa" = "8743"
"Zorgwaa" = "8743"
"Zorgwaar" = "87437"
"Zorgwaard" = "874372"
```

This does not give a reason why `Zorgwaa` isn't returning any results.
If I add Zorgwaard as organization to the development network, it's returning results.

@ltieleman could you provide stats on your environment (versions, which UI, etc)

**Comment by ltieleman** [comment]
@woutslakhorst I used the latest versions available when I created the issue. I used the UI to demonstrate the functional impact, but I have the same result when calling the API directly with:
http://localhost:1323/internal/didman/v1/search/organizations?didServiceType=eOverdracht-receiver&query=Zorgwaa

- nutsfoundation/nuts-node                                                                  master                                     dbcccf1ef019   3 days ago      42MB (git commit cb1161f179249bed26dd1fcc63653671f2ba93e3)
- nutsfoundation/nuts-registry-admin-demo                                                   master                                     25abe4dee9eb   3 days ago      22.9MB
- nutsfoundation/nuts-demo-ehr                                                              main                                       42e708ccc793   3 days ago      29.3MB

**Comment by woutslakhorst** [comment]
ahhhh a DIDman query with service, not a direct search. Could you verify that you can find the organisation if you use `/internal/vcr/v2/search`?

**Comment by reinkrul** [comment]
Such a DIDMan query could return a list of exact matches and a list of phonetic matches, that way implementors can decide how to present it to their users ("did you mean...?")

**Comment by ltieleman** [comment]
Just pulled the latest nuts-node/ehr/admin images. Still able to reproduce with the http://localhost:1323/internal/didman/v1/search/organizations?didServiceType=eOverdracht-receiver&query=Zorgwaa  
(deleted everything in the data folders, so a clean start). 

With /internal/vcr/v2/search I get better results. When I search for "Zorgwaa" I get both "Zorgwaard" and "Zorgvilla de Ton" as response.

There is something fishy going on though, because after I rename Zorgstroom to Zorgwaard and Zorgwaard to Zorgstroom in the admin I am able find Zorgwaard in the first query as well. Even if I revert the renaming afterwards. So it's more then just the names...

**Comment by woutslakhorst** [comment]
> There is something fishy going on though, because after I rename Zorgstroom to Zorgwaard and Zorgwaard to Zorgstroom in the admin I am able find Zorgwaard in the first query as well. Even if I revert the renaming afterwards. So it's more then just the names...

That is a different issue: Changing the name of an organization in YOUR administration does not mean it is published as such on the network.

**Comment by woutslakhorst** [comment]
From DIDman it requires City to be non-nil. Does your organizations all have the city filled?

**Comment by ltieleman** [comment]
> From DIDman it requires City to be non-nil. Does your organizations all have the city filled?

Yes.

**Comment by woutslakhorst** [comment]
reproduced it, so labelling it as bug

**Comment by woutslakhorst** [comment]
Requires fix listed here: https://github.com/nuts-foundation/go-leia/pull/21
