### ISSUE TITLE
New storage engine

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1095]
We identify 4 categories of storage:

- Volatile: contains data that can be lost/purged without consequences for the Nuts Node
  - Contains: network outbound connector backoff store
  - Storage: filesystem-local BBolt database
- Index: views/projections of shared/critical data. Can be rebuild (in case of corruption) but can take a long time.  
  - Contains: VCR document store and revocations, VCR issued credentials index, VDR document store and metadata
  - Storage: filesystem-local BBolt database
  - Does not need to be backupped
- Shared: public data published to/received from the network. When lost, can be retrieved from other netwrk nodes.
  - Contains: public transactions + payload
  - Storage: pluggable key-value database
  - Could be backupped, but not required
- Critical
  - Contains: payloads of private transactions, private TX query scheduler storage, issued VCs, private keys (special case)
  - Storage: pluggable key-value database
  - Must be backupped

These categories identify 3 types of storage:

- Pluggable key-value database
- Filesystem-local BBolt database
- Secure private key storage

The first 2 are going will be provided by the storage engine.

**Comment by woutslakhorst** [comment]
Removing milestone and keeping issue to track different categories progress

**Comment by reinkrul** [comment]
Done for now. Future may see JSON-LD native storage and go-leia in e.g. ElasticSearch.
