### ISSUE TITLE
Searching for a credential type should filter out other types

### ISSUE THREAD

**Issue by stevenvegt** [nuts-foundation/nuts-node#1133]
When searching for a credential, the type is used to expand the fields, but it's not used to filter out other types. So when a credential has matching fields but is from a different type, it still appears in the results. This is confusing.

**Comment by woutslakhorst** [comment]
This is also a feature to make sure you find all VCs that assert the same concept. NutsOrganization vs Kvk, both must be found with the same query.

Solutions:
- add a NotNil part to the query (key = "") that can only be satisfied by the required concept
- add a search option to restrict to a specific type

**Comment by woutslakhorst** [comment]
Adding:

```
"organization": {
  "name": ""
}
```

to the `credentialSubject` in the query already fixes it for the current logic. If this is desired UX is another question?
