### ISSUE TITLE
Publisher.isBlockingTransaction() should check PAL header

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1134]
`Publisher.isBlockingTransaction()` is checking the transaction content type (whether it equals `application/did+json`). But we decided a TX is considered blocking when it doesn't have a PAL header (in other words, of all non-private TXs the payload must be present).

TODO:
- Check whether this is spec'd in the RFCs

**Comment by woutslakhorst** [comment]
irrelevant since publisher has no use anymore now TXs always have their payload attached.

**Comment by gerardsn** [comment]
Publisher has been removed #1173
