### ISSUE TITLE
e2e tests not working correctly for versioned branches

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#1135]
The docker compose files explicitly use `master`

**Comment by gerardsn** [comment]
I think this is handled in the GH actions workflow:

https://github.com/nuts-foundation/nuts-node/blob/2a700fab3ab2b061dc4d46d1d7e9266ba7daeff6/.github/workflows/e2e-tests.yaml#L69-L77

This should probably be documented in the e2e test to make sure tests keep working

**Comment by gerardsn** [comment]
I think this is handled in the GH actions workflow:

https://github.com/nuts-foundation/nuts-node/blob/2a700fab3ab2b061dc4d46d1d7e9266ba7daeff6/.github/workflows/e2e-tests.yaml#L69-L77

This should probably be documented in the e2e test to make sure tests keep working

**Comment by woutslakhorst** [comment]
fixed by find/replace magic
