### ISSUE TITLE
Config: cased config properties can't be passed using environment vars 

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#118]
E.g. the following does work, as expected;

```
NUTS_STRICTMODE=true
```
(`strictmode` is all-lowercase)

The following does not work because `bootstrapNodes` contains a capital `N`;

```
NUTS_NETWORK_BOOTSTRAPNODES=bootstrap:5555
```

When I change it to `bootstrapnodes` in the "koanf" tag, it does work.

**Comment by woutslakhorst** [comment]
and if you use: `NUTS_NETWORK_BOOTSTRAP_NODES`?

**Comment by reinkrul** [comment]
Also doesn't work; it then interpolates the key to `network.bootstrap.nodes`

**Comment by woutslakhorst** [comment]
i can seriously live with: "everything has to be lowercase"

**Comment by reinkrul** [comment]
I could live with that too.

**Comment by woutslakhorst** [comment]
latest proposal: use `snake_case` for config names everywhere

**Comment by woutslakhorst** [comment]
snake_case also doesn't work: all `_` get replaced with a `.`

**Comment by woutslakhorst** [comment]
reflection also won't work because the config gets parsed before injected into each engine. When it's parsed `_`s get converted.

The only thing that will definitely work is to convert all config params to `[a-z]`
