### ISSUE TITLE
Use updated go-leia in VDR

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#1185]
go-leia will support a 2 DB initializer: one for the index and one for the documents. The payloads DB could be reused for this.

**Comment by woutslakhorst** [comment]
Is this the best solution when looking forward? Separation of concerns comes to mind...

**Comment by gerardsn** [comment]
VDR does not use go-leia.
#1238 replaces the bbolt storage with the storage engine

**Comment by woutslakhorst** [comment]
> VDR does not use go-leia.
Then we can close this.
