### ISSUE TITLE
Add DID Doc Update validation

### ISSUE THREAD

**Issue by stevenvegt** [nuts-foundation/nuts-node#12]
Update checks are not complete.

* [x] Version of a new doc does not start with 0
* [x] Version or updatedAt timestamp of a updated doc !> previous
* [x] New keys added should be added to the keystore
* [x] Removed keys should be removed from the keystore
* [x] Resolving a chain of controllers (more than 1)
* [x] Deactivation of ducuments
* [x] Timeline validation according to [RFC004 3.4.1](https://nuts-foundation.gitbook.io/drafts/rfc/rfc004-distributed-document-format#3-4-1-timeline-validation)
* [x] Full e2e test which will test the complete life cycle of a document:
  * [x] Creation of a new document A
  * [x] Update Document A with a new service
  * [x] Update Document A with a new authentication key, old one should be removed
  * [x] Creation of New Document B
  * [x] Update of Document B controller which transfers control to Document A
  * [x] Update of Document B with new service endpoints, signed by Document A
  * [ ] Creation of Document C
  * [ ] Update of Document C which makes Document B the controller
  * [ ] Deactivation of Document C
  * [x] Deactivation of Document A and thus also Document B

**Comment by woutslakhorst** [comment]
Timeline validation is also to be removed: nuts-foundation/nuts-specification#30
