### ISSUE TITLE
Change trust behaviour in VC search

### ISSUE THREAD

**Issue by stevenvegt** [nuts-foundation/nuts-node#1220]
Searching for credentials allows a:
```
searchOptions": {
        "allowUntrustedIssuer": true
    }
```

This should be set to true when searcing for Nuts Auth credentians, but this is a bit counter intuitive when you are securing your APIs.

The point of this flag is mainly to search for credentials issued by (multiple) (un)trusted third parties. But this is not relevant if the `issuer` is explicitly provided in the search query. You only want to search for credentials issued by this party.

I propose to change the behavior of this endpoint to return untrusted issuers when the issuer is explicitly set.

Then it also begs the question: what other situations are there left that justifies setting `allowUntrustedIssuer` to true. I think there are none and so we can remove the option.

**Comment by woutslakhorst** [comment]
> Then it also begs the question: what other situations are there left that justifies setting allowUntrustedIssuer to true. I think there are none and so we can remove the option.
debugging.

**Comment by woutslakhorst** [comment]
For the future use of credentials we require a framework which decides which combination of credentials is valid for a certain purpose. This would mean that trust on the individual level is irrelevant. 

For search the parameter can then be removed entirely, always return what you seek (trusted or not). When using the credential it must be totally clear is there's a trust issue or not!

We must check if the feedback is correct when using an untrusted organizationCredential in different parts of the node.
