### ISSUE TITLE
Node forgets VCs after reboot

### ISSUE THREAD

**Issue by stevenvegt** [nuts-foundation/nuts-node#1231]
## Symptoms:
Searching for a VC in the network works on a fresh node, but after rebooting, it can no longer be found. Newly created VCs show up in the results, but these disappear as well after after a reboot.

## Cause:
A migration operation is still in place which should have been removed after the network reset.

## Affected versions:
Only master:
https://github.com/nuts-foundation/nuts-node/blob/master/vcr/vcr.go#L147

v2 and v3 are not affected.

## Workarounds:

After a reboot, force the network to re-index the network transactions by performing the following API rest call:
`POST localhost:1323/internal/network/v1/reprocess?type=application%2Fvc%2Bjson`

**Comment by woutslakhorst** [comment]
only master is affected, V3 and earlier are not.

**Comment by woutslakhorst** [comment]
fixed by #1232
