### ISSUE TITLE
Network: improve visibility/analysability for unretrievable private TXs

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1260]
There are be several reasons a node can't retrieve a private TX, including:

- It can't connect to the other node(s) for retrieving the private TX
- It can connect to the other node, but the node won't/can't send the TX
- etc

If a private TX is received but the payload can't be retrieved, an operator would have to find out about it and analyse the issue using the log. But this should be a metric (for alerting) and should be present on the node's diagnostics page. Maybe including the reason why it failed.

In fact; sort of dead letter queue?

**Comment by woutslakhorst** [comment]
It's already there, just not exposed.

The scheduler has a Dead letter bucket. The last error could be added, it currently only has a count.

**Comment by woutslakhorst** [comment]
Also add an API for retrieving unfinished jobs and maybe also a Delete.

**Comment by woutslakhorst** [comment]
This is currently listed in the diagnostics page: `protocol_v2.payload_fetch_dlq` with the `Event` struct as output. It would be better to output the count to `state.failed_events` in the diagnostics and add a `nuts_dag_failed_events_total{type=x}`.

The an API can fetch the actual details.

**Comment by woutslakhorst** [comment]
The counter isn't really that useful since all private payload fetches will be retried and they will never give an error. More useful would be: `nuts_dag_events_notified_total` and `nuts_dag_events_finished_total` so you can do one minus the other in prometheus.
