### ISSUE TITLE
Network: backoff when connection fails on protocol level

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1265]
The outbound connector backoff works when the connection fails on TCP/TLS level (e.g. time-out, DNS error, etc). But then, when a connection can be made (TLS handshake succeeds) but an application protocol level check fails (e.g. node DID authentication), the backoff isn't increased. The node immediately tries to reconnect, while it is often a non-temporary error (e.g. node DID misconfigured). In this case (and maybe other cases), the backoff should be increased as well.

**Comment by woutslakhorst** [comment]
This is quite common on the development network and spams the logs.

**Comment by reinkrul** [comment]
```
WARN[0235] Peer node DID could not be authenticated      did="did:nuts:HFsofiK4N5N4pv1wS3Cznr6WovgW6mh7xki4uW2nzaiv" error="none of the DNS names in the peer's TLS certificate match the NutsComm endpoint (nodeDID=did:nuts:HFsofiK4N5N4pv1wS3Cznr6WovgW6mh7xki4uW2nzaiv)" module=Network peerAddr="..." peerDID= peerID=5c6c8b3b-ad6b-4f7f-ae07-0ca068f907e8
```

**Comment by woutslakhorst** [comment]
Message at the client side

```
WARN[0049] Failed to open gRPC stream                    error="nodeDID authentication failed" module=Network peerAddr="nuts-development.woutslakhorst.nl:5555" protocolVersion=2
ERRO[0049] Error while setting up outbound gRPC streams, disconnecting  error="nodeDID authentication failed" module=Network peerAddr="nuts-development.woutslakhorst.nl:5555" peerDID= peerID=7af4c1bd-6b16-466a-80d1-ccf7e212deef
```

**Comment by reinkrul** [comment]
I can't reproduce it in the integration test. Is it for incoming or outbound connections?

**Comment by woutslakhorst** [comment]
This is incoming, thats it, no other logs.

**Comment by reinkrul** [comment]
We only have backoff for outbound connections. I don't think it is wise to hastily add it to v5 for inbound connections.

There are some things to consider, especially when backoff kicks in due to authentication failures:

- You can now (crudely) reset backoff by deleting the connections.db file. If you fix your node and want to reset all backoffs to reconnect to other nodes, this might not be possible due to the backoff, the other nodes have regarding your node.
- Inbound backoff should always give more slack than outbound backoff, otherwise a new connection attempt will always fail due to backoff violation.

Maybe a rejected (inbound) connection due to backoff should report the connecting party when the connection can be re-attempted?

**Comment by woutslakhorst** [comment]
Correct, temporary bans should be possible by nodes

**Comment by reinkrul** [comment]
Happens when the node making the outbound configures a nodeDID but is misconfigured (e.g. it doesn't have a NutsComm endpoint in its DID document). Then the remote node closes the connection, and the backoff (for the local node) should be triggered.
