### ISSUE TITLE
Document current backup mechanism for Ops

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#1269]
BBolt config + file behaviour + additional requirements for Ops.
Redis config + link to Redis backup instructions.
Vault config + link to Vault backup instructions.

**Comment by woutslakhorst** [comment]
Redis and Vault part will be done before V5

**Comment by woutslakhorst** [comment]
Trustfile backup!

**Comment by reinkrul** [comment]
I think when https://github.com/nuts-foundation/nuts-node/pull/1446 is merged, all points are taken care of?
