### ISSUE TITLE
Improved network message sending/handling

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#1302]
Fixes to prevent the node from slow processing and throwing lots of errors.

- [x] #1307
- [x] #1310
- [x] #1322

**Comment by woutslakhorst** [comment]
Proposal for heads in `prevs`: just point to the latest TX ref (and use the stored LC value beside it). Every node will have a head. This head does not need to be the same. Pointing to a head still assures moving forward in LC values. This is besides the requirement to point to the DID Doc update transaction. The heads shelf in the DB can be replaced by a latest TX.Ref + TX.LC value.

**Comment by reinkrul** [comment]
Everything for v5 is fixed.
