### ISSUE TITLE
Support TLS offloading via HAProxy

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#1337]
HAProxy can send the client certificate as base64 DER certificate not PEM:

```
http-request set-header X-SSL-Client-Cert          %{+Q}[ssl_c_der,base64]
```

The node currently only supports PEM.

**Comment by reinkrul** [comment]
Test: https://github.com/nuts-foundation/nuts-go-e2e-test/pull/33
