### ISSUE TITLE
VCR: add trust to credentials

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#134]
Add configuration options to trust an issuer of VCs. This must be specified per type.

when untrusted, should it return an error and/or must we provide an override flag?
the same for a credential that is not trusted (yet/anymore)

**Comment by woutslakhorst** [comment]
Proposal:
- GET operation to return the raw VC
- Resolve operation to return a ResolutionResult with details about the state: ["revoked", "untrusted", "trusted"]
- Search only returns "trusted" results.

**Comment by woutslakhorst** [comment]
Trusting/untrusting should be doable via the API as well since that would seriously help with the automated tests. The configfile should point to a `trusted_issuers.yaml` which contains a structure of trusted issuers:

```
NutsOrganizationCredential:
  - did:nuts:1
  - did:nuts:2
OtherCredential:
  - etc
```

The structure can be expanded with information about proof types.

**Comment by reinkrul** [comment]
> Trusting/untrusting should be doable via the API as well since that would seriously help with the automated tests. The configfile should point to a `trusted_issuers.yaml` which contains a structure of trusted issuers:
> 
> ```
> NutsOrganizationCredential:
>   - did:nuts:1
>   - did:nuts:2
> OtherCredential:
>   - etc
> ```
> 
> The structure can be expanded with information about proof types.

At runtime VC-issuers marked as "trusted" using the API don't get persisted (since we don't write `nuts.yaml`)? That's sounds like odd behaviour to me. I don't see the issue with automated tests, since trusted credentials can just be modelled as a `map[string][]string` and passed/manipualted by the automated tests?

Configfile looks fine.

**Comment by woutslakhorst** [comment]
They do get persisted.
