### ISSUE TITLE
ldutils_test.go reads (HTTP) external JSON-LD schemas during test

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1357]
Tests should not use external resources because it makes test flaky. E.g. when the external resources goes away/relocates, is slow, or the local network has a hickup.

Replace with a local webserver.

**Comment by jeroendee** [comment]
Will have a look.

**Comment by reinkrul** [comment]
> Will have a look.

The test is actually `ldutils_test.go` on line 146.

**Comment by jeroendee** [comment]
h3. What
In the unittest _"it resolves an external doc when allowingExternalCalls is true"_ in `ldutils_test.go` (on line 146) don't depend on an external call being made. 

h3. Why
During unit-testing depending on external calls being made increases the chance of tests becoming flaky.  

h3. How
Implement a test-double, in this case a stub, through the usage of the httptest package.
