### ISSUE TITLE
Separate certificate for /public?

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1363]
RFC states PKIoverheid Private is used, but its Root CA isn't trusted by browser vendors. Which certificate needs to be used for `/public` endpoints? This could also be a LetsEncrypt certificate?

**Comment by olafz** [comment]
Any publicly trusted certificate can currently be used for the `/public` endpoint. It will use a separate subdomain (see https://nuts-node.readthedocs.io/en/latest/pages/deployment/recommended-deployment.html#subdomains) and proxied by Nginx/HAProxy/...

**Comment by woutslakhorst** [comment]
when using a reverse proxy: no problem. When using tls termination on echo........ not supported?
