### ISSUE TITLE
Add support for Redis Sentinel

### ISSUE THREAD

**Issue by olafz** [nuts-foundation/nuts-node#1369]
You can configure a Nuts node to use Redis to store all non-volatile data (see https://nuts-node.readthedocs.io/en/latest/pages/deployment/database-configuration.html#redis).

We deploy high availability for Redis with[Redis Sentinel](https://redis.io/docs/manual/sentinel/), but the Nuts node does not support Redis Sentinel (yet).

Currently, the Nuts node supports `storage.redis.address`, `storage.redis.database`, `storage.redis.username` and `storage.redis.password` variables. When you expand this to support Redis Sentinel, the following variables are relevant from the [`go-redis`](https://github.com/go-redis/redis/blob/master/sentinel.go#L22-L33) client:

```go
MasterName string
SentinelAddrs []string
SentinelUsername string
SentinelPassword string
```

A very simple Redis Sentinel client connecition implementation could look like this in the Nuts node:

```
rdb := redis.NewFailoverClient(&redis.FailoverOptions{
    MasterName: "mymaster",
    SentinelAddrs: []string{
        "sentinel1:26379",
        "sentinel2:26379",
        "sentinel3:26379",
    },
})
```

**Comment by reinkrul** [comment]
Specify the following connection string parameters for `storage.redis.address`:

- `sentinelMasterName`: name of the sentinel master, if you specify this parameter Sentinel support will be enabled.
- `sentinelUsername`: optional sentinel user name
- `sentinelPassword`: optional sentinel password

To use Sentinel you'll have to use the connection string-style Redis address, e.g.: `rediss://instance1:1234,instance2:1234,instance3:1234?sentinelMasterName=<master>`
The other Redis options for non-Sentinel will still be applied (e.g. username/password, TLS, other connection string params).

**Comment by woutslakhorst** [comment]
Current go-redis client has a bug in V9: https://github.com/go-redis/redis/issues/2175
Current solution points to a fork which has this problem solved.
go-redis version is also a beta.
