### ISSUE TITLE
Add support for Vault KV version 2

### ISSUE THREAD

**Issue by olafz** [nuts-foundation/nuts-node#1370]
Currently, the Nuts node only supports version 1 of the Vault KV store. See https://nuts-node.readthedocs.io/en/latest/pages/deployment/database-configuration.html#vault.

It would be nice when the Nuts node would add support for KV version 2, preferably with support for auto-detection of the version - such that a migration would be very straight-forward.

**Comment by reinkrul** [comment]
We considered this in https://github.com/nuts-foundation/nuts-node/issues/766, v1 and v2 are considered modes rather than a newer version of the API (https://www.vaultproject.io/docs/secrets/kv). Since the Nuts node doesn't need versioning which v2 brings, we settled for v1.

What would v2 bring for your use case?

**Comment by olafz** [comment]
> What would v2 bring for your use case?

v2 provides versioning, which is also the main use-case: v1 does not provide a way to version or roll back secrets. This could make it (more) difficult to recover from unintentional data loss or when data is accidentally overwritten. Where possible, we prefer v2 over v1 for this reason.

**Comment by woutslakhorst** [comment]
> v2 provides versioning, which is also the main use-case: v1 does not provide a way to version or roll back secrets. This could make it (more) difficult to recover from unintentional data loss or when data is accidentally overwritten. Where possible, we prefer v2 over v1 for this reason.

They key (in key/value) in our case is the fingerprint of the public key associated with the private key. So it'll always be a single version. Loss of key material is mitigated by the fact that a DID Document has a controller (parent) that is able to add/remove keys. We still have to add support for a "root" owner which you can keep offline/physical medium.
