### ISSUE TITLE
Decide whether we want HTTP bind addresses per engine or just use the global config

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#14]
Now each engine defines a HTTP bind address (or remote server address when running the client). The global config also defines the bind address. Since we don't plan to start just some modules per node (fine-grained microservices) but use the all-or-nothing approach, there's (imo) no need to specify a bind address per engine.

**Comment by woutslakhorst** [comment]
Unless we want to bind internal API to a different interface. But that should be future work I think.

**Comment by reinkrul** [comment]
In that case these alternative ports are determined by the core/global config anyways, not per engine I think. So we get a map with API categories -> ports;

`
binds:
  public: 0.0.0.0:1323
  admin: localhost:9999
  internal: nuts-node.lan:2000
`

or something

**Comment by woutslakhorst** [comment]
This issue only focusses on using a single `address` config for each engine!

**Comment by reinkrul** [comment]
Already fixed.
