### ISSUE TITLE
Check whether CRL verification on client certificates works out of the box on NGINX and HAProxy

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1422]
CRLs must be checked, but when offloading TLS (as we recommend) this must be done by the proxy. We must check if NGINX and HAProxy do it out-of-the-box, or if anything else is required to do so.

**Comment by woutslakhorst** [comment]
nginx validates against a file. This file does need to be updated by another process.

**Comment by reinkrul** [comment]
The same applies to HAProxy.
