### ISSUE TITLE
Avoid connecting to wrong network?

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1424]
When a party deploys a new node, it could accidentally configure the incorrect bootstrap node of another environment. In severe cases this could lead to a data leak.

E.g., the new node wants to connect to a production network (bootstrap node runs on `some-node:5555`), but accidentally connects to a test network which is not meant for production data (e.g. `some-node:5556`). There's little a system administrator can do to verify it's connected to the right network (e.g. inspecting registering registered organizations).

Possible solutions:

- Recommend nodes to have very clear gRPC address, e.g. `nuts-acceptation.some-party.nl`. Do not only use a separate port for a different network.
- Add a header specifying the network (as string) to the gRPC connection (e.g. `acceptation` or `production`), drop connection if a node connects with a different network label. This protects against accidental misconfiguration.

**Comment by woutslakhorst** [comment]
won't fix
