### ISSUE TITLE
Auth: RequestAccessToken API call returns status code of remote node

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1428]
The RequestAccessToken API call, which calls CreateAccessToken on the remote node, returns the status code of the remote node if it returns a non-successful code. So if the remote node returns status 404, RequestAccessToken returns 404 as well.

This is weird and potentially unsafe API design, and makes it fuzzy about what went wrong. Better to return a specific error code and describe what went wrong (including the status code the remote node returned) in the error message. E.g.;

- 502 Bad Gateway
- 503 Service Unavailable

See `auth/api/v1/api.go:328`:

```go
        accessTokenResponse, err := authClient.CreateAccessToken(endpointURL, jwtGrantResponse.BearerToken)
	if err != nil {
		if statusCodeErr, ok := err.(core.HTTPStatusCodeError); ok {
			return core.Error(statusCodeErr.StatusCode(), "unable to create access token: %w", err)
		}

		return fmt.Errorf("unable to create access token: %w", err)
	}
```

**Comment by woutslakhorst** [comment]
v1 will be deprecated, won't fix
