### ISSUE TITLE
Auth: Don't require publicURL to be configured when IRMA is disabled

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1444]
When organizations don't use the Nuts Node to sign IRMA contracts (e.g. they only implement eOverdracht sender role, or they use an external IRMA server), they can disable IRMA schema updates, but they still need to configure publicURL when enabling strict mode.

We can drop this requirement if IRMA is disabled.

**Comment by gerardsn** [comment]
From the flag name or description it is not clear that this is used to disable IRMA. 
```
auth.irma.autoupdateschemas | true | set if you want automatically update the IRMA schemas every 60 minutes.
```

If IRMA is disabled we also do not need to verify that `auth.irma.schememanager==pdbf` in strictmode

**Comment by gerardsn** [comment]
Now a required field
