### ISSUE TITLE
Network: inform through log message when reprocess is finished

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1445]
It now logs that it started, but would be nice to know when it finished.

**Comment by woutslakhorst** [comment]
That might be a bit tricky with a queue in between...

**Comment by reinkrul** [comment]
At least we should document which indication sysadmin should look for to determine it's finished?

**Comment by woutslakhorst** [comment]
Using metrics: https://github.com/nats-io/prometheus-nats-exporter#the-nats-prometheus-exporter-api ?

**Comment by pascaldekloe** [comment]
What is preprocess? The term is not used in the documentation at all.

**Comment by woutslakhorst** [comment]
It's an API call to walk over all transactions and do VC and DID stuff to them:

https://nuts-node.readthedocs.io/en/stable/search.html?q=reprocess&check_keywords=yes&area=default

**Comment by pascaldekloe** [comment]
Apparently you're supposed to use the asynchronous calls for batches too on NATS. PublishAsyncComplete can be used to wait. Error handling is a bit vague. 😒

 https://github.com/nats-io/nats.go/issues/783#issuecomment-890522942

**Comment by gerardsn** [comment]
closed by #2108
