### ISSUE TITLE
VCR: Allow received VCs with only VerifiableCredential as type

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1448]
Stable network contains VCs that contain only "VerifiableCredential" as type, missing e.g. "NutsAuthCredential". This currently causes an error, which keeps popping up every time the VC is retried.

The RFC states that the VC must contain "VerifiableCredential" and _can_ have 1 additional type. So; the Nuts node MUST accept VCs that only specify "VerifiableCredential" as type.

Prerequisite is that the expanded version of the NutsAuthorizationCredential is indexed/stored?

**Comment by woutslakhorst** [comment]
> Prerequisite is that the expanded version of the NutsAuthorizationCredential is indexed/stored?
Paths from extended form are indexed, the entire raw form is stored.
