### ISSUE TITLE
VCR: Do not retry VCs that are semantically/syntactically incorrect

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1449]
When VCs can never be parsed, because e.g., the format is invalid (not JSON, or invalid JSON-LD), the scheduler should not retry it as it currently does. And probably log a warning.

Follow up on https://github.com/nuts-foundation/nuts-node/issues/1423

**Comment by woutslakhorst** [comment]
This requires a specific (wrapping) error that is recognised by the scheduler
