### ISSUE TITLE
VCR: Searching for VC yields "json arrays are not supported"

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#145]
Using the following query:

```golang
response, err := client.Search(context.Background(), "organization", SearchJSONRequestBody{
	Params: []KeyValuePair{
		{
			Key:   "organization.city",
			Value: "Franeker",
		},
	},
})
```

Yields the following error: `json arrays are not supported `. I added the `currentPath` variable and it points out the problem is `@context`.

When I ignore the error (returning nil instead of returning an error), the search works properly.

**Comment by woutslakhorst** [comment]
`template.go#234`, it'll probably be ok to return nil at that point
