### ISSUE TITLE
Auth: requestAccessToken "credentials" marked required, but can be used without

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1461]
In OpenAPI "credentials" is a required field, but the call completes just fine without passing it.

Also seems like the issuing Nuts Node also misses this check?

**Comment by woutslakhorst** [comment]
Requests may be made without credentials (eg: eOverdracht notification). So it the field required but may be empty or just not required?

**Comment by woutslakhorst** [comment]
use-cases indicate tokens may be requested without credentials. Making the credentials field optional would be a braking change.

Proposal: add description to OAS that credentials may be zero length?

@reinkrul ?

**Comment by reinkrul** [comment]
We can "unrequire" it in OAS for v5; yes it's an API change, but a backwards compatible one (the reverse wouldn't be).

Suggestion: just remove `required: true` from OAS?

**Comment by woutslakhorst** [comment]
that will change all generated code

**Comment by reinkrul** [comment]
I think we allowed ourselves non-breaking changes to OAS?

Since, as far as I know, all current vendors use Java or .NET (which don't use pointers a null parameter is just null). Maybe Kotlin users (with `?` notation) but I don't think people use Kotlin-native OAS generators.

**Comment by woutslakhorst** [comment]
> I think we allowed ourselves non-breaking changes to OAS?

No we explicitly said no changes to the API
