### ISSUE TITLE
DIDMan: getCompoundServiceEndpoint returns 500 when service does not exist

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1463]
Or when the endpoint can't be resolved.

500 is reserved for unexpected errors, so it should return something else.

**Comment by gerardsn** [comment]
What call reproduces the error? (Prime suspects such as ErrServiceNotFound are mapped to a sensible statuscode)

Possible errors in `vdrAPI.GetCompoundServiceEndpoint` that are not mapped to a statuscode

- `vdrTypes.ErrNoActiveController` and `vdrDoc.ErrNestedDocumentsTooDeep`, both returned by `vdrTypes.DocResolver`
- Any error returned by `ssi.ParseURI `-> resolvers.go#L324, unwrapped `url.Parse` error from go-did library.

**Comment by pascaldekloe** [comment]
Can not reproduce @reinkrul. Can you you specify the steps please?

**Comment by reinkrul** [comment]
Weird, can't reproduce it. Still, found out that the response codes don't exactly match the description; 406 is returned when the service does not exist (but should return 404), but really a trivial bug.

Closing.
