### ISSUE TITLE
Support more auth methods for Vault like appRole

### ISSUE THREAD

**Issue by stevenvegt** [nuts-foundation/nuts-node#1472]
Can we support more authentication methods in addition to the VAULT_TOKEN?

https://www.vaultproject.io/docs/auth
https://www.vaultproject.io/docs/auth/approle

**Comment by woutslakhorst** [comment]
👍  for appRole

**Comment by olafz** [comment]
I would argue this is not the responsibility of the Nuts node.

Vault supports a large number of authentication methods. Why would you want to create any logic in the Nuts to support a specific auth method, like appRole? The Nuts node will always run in an environment that will support some kind of existing, external authentication method (e.g., Nomad, GCP, Azure, Kubernetes, etc. in production or something like GitHub or Okta in local development).

When _any_ or these (non-token) authentication method returns OK, Vault invokes the token method to create a new unique token (`VAULT_TOKEN`). In other words, each vendor can have one or more authentication methods enabled and use the authentication method(s) that makes the most sense for their use case. The resulting `VAULT_TOKEN` can then be passed to the Nuts node.

**Comment by woutslakhorst** [comment]
Given the explanation from Olaf, it is important to get feedback on this from vendors

**Comment by stevenvegt** [comment]
I'm closing this one. If this feature requests comes up again, we can reopen.
