### ISSUE TITLE
Certificate in the keyvault

### ISSUE THREAD

**Issue by HansSDBGroep** [nuts-foundation/nuts-node#1488]
Right now the certificates for the nuts node can only be placed on disk.
It woul be nice if the certificate can be taken from the (Azure) keyvault.

**Comment by HansSDBGroep** [comment]
With TLS offloading?
Yes that would even be better.

**Comment by olafz** [comment]
> Right now the certificates for the nuts node can only be placed on disk.
> It woul be nice if the certificate can be taken from the (Azure) keyvault.

This is already possible when you run the Nuts node container: you can store the certificates in a secret store (Vault, Azure keyvault, etc.) and mount them in the Nuts container (ie. in memory, tmpfs). Then, you can run the Nuts node with either a config parameter or environment variable:

```
NUTS_NETWORK_CERTKEYFILE=/secrets/nuts-key.pem
NUTS_NETWORK_CERTFILE=/secrets/nuts-cert.pem
```

**Comment by woutslakhorst** [comment]
If this works for Azure, then a bit of documentation would already solve it.

**Comment by stevenvegt** [comment]
@HansSDBGroep does this answers your question?

**Comment by reinkrul** [comment]
Closing as there is a solution available.
