### ISSUE TITLE
VCR: Make VC validators pluggable (and not hardcoded)

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1505]
We have hardcoded validators for `NutsAuthorizationCredential`s and `NutsOrganizationCredential`s (and a base validator for any credential). These VC-type-specific validators shouldn't be hardcoded into the Nuts Node: it makes introducing new versions (through releasing a new JSON-LD context version) error-prone and unpractical, because it requires a Nuts Node released.

Validating VC types is a good feature to prevent (hard to debug) mistakes, but the validation rules should be externalized, so they become configuration of the Nuts Node, rather than hardcoded functionality.

Options:

- Don't do validation (the lazy solution)
- JSON schema (might be weird to combine with JSON-LD)
- Make own format (future compatibility issue/lots of work)
- ...?

**Comment by woutslakhorst** [comment]
Won't fix. Issuers are responsible and if self issued then the authorization policy should do it.
