### ISSUE TITLE
Docs: missing reverse proxy for Grpc in deployment diagram

### ISSUE THREAD

**Issue by stevenvegt** [nuts-foundation/nuts-node#1507]
In the deployment diagram: https://nuts-node.readthedocs.io/en/stable/pages/deployment/recommended-deployment.html the line between *Other service provider* and the nuts node with the "sync network" should go through a reverse proxy.

<img width="255" alt="Screenshot 2022-10-05 at 11 08 38" src="https://user-images.githubusercontent.com/3896736/194024270-50afbbe3-6124-442e-b970-1770bb95a474.png">

**Comment by gerardsn** [comment]
Does the latest version of the docs describe what you need?
https://nuts-node.readthedocs.io/en/latest/pages/deployment/recommended-deployment.html

**Comment by woutslakhorst** [comment]
done in latest doc
