### ISSUE TITLE
Document change in behaviour for TLS V4 <> V5

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#1515]
I believe V5 now also allows for TLS offloading on echo. This was previously not possible and the default was not to offload it on the Nuts node. Therefore a hybrid solution was possible: grpc TLS offloading on the node and https offloading on the reverse proxy. This is no longer possible, correct @reinkrul ?

**Comment by reinkrul** [comment]
In v5 you can disable TLS on HTTP endpoints using `http.default.tls = disabled`. If you still configure the global TLS properties, TLS will still be enabled on gRPC endpoints. So then you get the <= v4 behavior of TLS on gRPC, non-TLS on HTTP.

The reverse is currently not possible.

**Comment by woutslakhorst** [comment]
So that should be added to the change log since default behaviour changes and a change in config is required to get it back?

**Comment by woutslakhorst** [comment]
Also add note on changed JSON-LD context defaults and API behaviour

**Comment by reinkrul** [comment]
Actually, `disabled` is default, so it won't be enabled unless you enable it. So no behavior change there.

**Comment by woutslakhorst** [comment]
Ok, so just a link to general docs because of extended functionality then

**Comment by reinkrul** [comment]
Tested this; when just specifying TLS properties (certfile & friends) they're picked up by gRPC. Then TLS is enabled on gRPC but not on HTTP. To enable TLS on HTTP endpoints, specify `server` or `client-server` for the `tls` property (per endpoint).

So it works as in <= v4
