### ISSUE TITLE
VCR: SearchVCs partial/wildcard matching has unintended consequences

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1518]
Given an eOverdracht transfer, if the sending party certain FHIR URLs schemes might match correctly, but unintendedly, when performing SearchVCs. Especially when a FHIR server uses incremental numbering when creating tasks (e.g. HAPI FHIR server, by default). The following match:

- /Task/2
- /Task/2023123
- /Task/29bb421d-5b88-4d3e-b4d4-3a97eb3bd73e

When the EHR specifies both receiver and sender DIDs when searching (as it should), the occurrence should be much less frequent, but it still occurs. But when it occurs, the EHR (at least Demo EHR) tries to request an access token for the incorrect resource, which causes subsequent FHIR calls to fail.

There are 2 ways to mitigate this situation:

- Make SearchVCs match exactly on strings, unless specified otherwise
  - Maybe fields that are partially matched should be part of configuration? 
- Inform all parties (integrating the Nuts Node) that they must match the results from SearchVCs to the queried FHIR resources.

Maybe it might even happen on fields guaranteed to be random, e.g. `issuer` or `credentialSubject.id`?

I believe partial matching is only there for organization name search?

**Comment by woutslakhorst** [comment]
Prefix matching is the current default. An option for match type could be added to the API.
But, the default for FHIR resources is to use UUIDs to prevent all other sorts of issues.
It would be wise for implementations to do something with the fact they receive a list of matches. They probably want 1...
