### ISSUE TITLE
Auth: sanitize errors returned by CreateAccessToken

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#1527]
In development it should help the caller (remote Nuts node) identify the problem, but on production the errors should be sanitized to avoid leaking internals, which could point a hacker to a vulnerability.

in production (strictmode=true) it should have a generic error message.

**Comment by pascaldekloe** [comment]
Little waring-up with #1541…

**Comment by reinkrul** [comment]
These are 2 issues:
- Sanitize responses from `CreateAccessToken` (called by the remote node)
- Errors returned by `CreateAccessToken`, called by `RequestAccessToken` (called by the local EHR) should be clearly distinguishable as errors from the remote node
