### ISSUE TITLE
Docker builds fail for PRs merged by dependabot

### ISSUE THREAD

**Issue by gerardsn** [nuts-foundation/nuts-node#1531]
Dependency PRs merged using `@dependabot merge` result in `Error: Username and password required`.
Manually merging dependabot PRs works just fine.

**Comment by woutslakhorst** [comment]
Githubs user/roles management for forks/bot actions is troublesome. It also changes without warning...

For the e2e tests we added a `permissions` option which might also have a variant for docker builds.

But, do we really need docker builds for PRs?

**Comment by woutslakhorst** [comment]
Works when merging manually. That way the correct user is connected to the merge and the build will trigger.
