### ISSUE TITLE
Remove storageClassName from PVC spec so that it will take default one which is set in k8s cluster

### ISSUE THREAD

**Issue by anandlahoti** [nuts-foundation/nuts-node#1533]
Because of this parameter it is creating PVC on the Virtual machine, not taking the default one.
 
https://github.com/nuts-foundation/nuts-node/blob/6bc794666f45667a8f6c82b1a23943f256c5629a/charts/nuts-node/templates/nuts-data-pv.yaml#L25

For Example: Checkout Redis Master PVC template looks like no need to mention empty spec: https://github.com/bitnami/charts/blob/master/bitnami/redis/templates/master/pvc.yaml

**Comment by woutslakhorst** [comment]
The comment suggest this is intentional. The suggested change changes behaviour.

**Comment by gerardsn** [comment]
Closed due to inactivity. Feel free to reopen with more details / arguments on why the default behavior should change.
