### ISSUE TITLE
CLI: Make commands case-insensitive

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1548]
Quality of life. Introduced in Cobra 1.6: https://github.com/spf13/cobra/pull/1802

**Comment by pascaldekloe** [comment]
Really? Why?

**Comment by reinkrul** [comment]
Pro: maybe it helps some Windows user? What do you see as disadvantage?

**Comment by pascaldekloe** [comment]
Do Windows users type in upper-case? With multiple ways to do the same thing, you generally need a good reason to do so. I can not forse all scenario in which it may lead to trouble. Commands are tokens now. Easy to find. Easy to exclude.

**Comment by reinkrul** [comment]
Teaching our users not to type in random stuff in random ways is probably a good idea
