### ISSUE TITLE
Investigate keepalive_requests setting on nginx

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#1556]
The default setting for nginx is 1000 requests before the connection is closed.

Does this influence our grpc traffic and if so, what kind of error is logged?
This can then be added to the docs.

The e2e tests have a docker setup with nginx that could be used to investigate. Lowering the keepalive_requests value and setting a low gossipinterval.

**Comment by pascaldekloe** [comment]
GRPC uses HTTP which is stateless. Connections on the network layer "should" have no effect. We could spend some time in confirming that that is actually the case. Do we want that?

**Comment by woutslakhorst** [comment]
> GRPC uses HTTP which is stateless. Connections on the network layer "should" have no effect. We could spend some time in confirming that that is actually the case. Do we want that?

nginx handles it as http requests not tcp and does impose restrictions (such as max upload size). So yes I think this needs to be investigated.

**Comment by pascaldekloe** [comment]
E2E tests are [launched](https://github.com/nuts-foundation/nuts-node/blob/d9aec88a57dc5050f75c98b0be185527197a39a0/.github/workflows/e2e-tests.yaml#L75) as a GitHub workflow.

**Comment by pascaldekloe** [comment]
The problem with end-to-end is that the setup may, or may not create enough connections to trigger connection loss. I think it would be good to have a GRPC client against a (Docker) node setup for testing, regression, and error reproduction.

**Comment by woutslakhorst** [comment]
nginx also has a setting for the maximum number of requests per open connection. If this is set to 1 in a test, sending a couple of GRPC messages down the line will trigger a disconnect very quickly. If it doesn't then there's no issue.

E2E tests can be run standalone, not github actions required

**Comment by woutslakhorst** [comment]
internals of nginx show that the `keepalive_requests` counter is only increased by the http handler. If a grpc pass statement is used on a location block, the grpc handler is used which does not count requests.
