### ISSUE TITLE
VCR: Validating VCs fields breaks backwards compatiblity

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1561]
In v5 we added validation of VC fields: all fields must be defined by the JSON-LD context. This has broken NutsAuthorizationCredentials, because it required LegalBase to be present which was missing from the JSON-LD context.

Validation is performed when:
- Issuing a VC (self-issued)
- Retrieving a VC (resolving or searching) (self-issued or by someone else)
- Creating an access token (self-issued, or issued by a trusted 3rd party in future)

**Given**
- Contents of VCs are only validated ("are all fields defined in JSON-LD context?") when issuing it. It exists to help vendors find bugs in their integration.
- Nuts v1 JSON-LD context OR RFC014 will have to be changed: JSON-LD context is missing LegalBase, while RFC014 states it MUST be present. Both are considered "released".

**Possible solutions**
- v2 Nuts JSON-LD context becomes default in v5 and v4.3
  - 👍  Pros:
     - Quick adoption of v2 JSON-LD context
     - Technically "pure" solutions: no shortcuts, e.g., altering released specifications
     - No changes required for existing integrations from vendors
     - No/minimal changes required in RFCs
   - 👎 Cons:
     - Nuts Node v4 users must upgrade to v4.3 of v5: nodes running <= v4.3 can't process the new credentials
- Current situation: don't allow LegalBase in v5, allow it starting v6 (through Nuts v2 context)
  - 👍  Pros:
     - ...
   - 👎 Cons:
     - Nuts Spec v1 will have to be altered, which is already released.
     - Existing integrations from vendors will have to be changed
     - Adoption of Nuts v2 is deferred until v6 is released (which is unscheduled)
- Lenience (variant on above): keep current situation, but accept LegalBase in API, remove it from VC before issuing it
  - 👍  Pros:
     - No changes required for existing integrations from vendors. We keep our promise "you may run the previous version, and it will keep working".
   - 👎 Cons:
     - Odd API behavior from developer perspective, which might lead to incorrect conclusions (LegalBase expected to be there, but it isn't)
     - Nuts Spec v1 will have to be altered, which is already released.
- Add LegalBase to Nuts v1 JSON-LD context in v5; remove it from VC before validating signature for backwards compatibility (based on issuance date, or verify signature twice; with legalBase and without)
   Can be made less awkward if the VC are sanitized (legalBase removed if there 'illegally') before storing, complemented with a migration to do the same to existing VCs in storage.
  - 👍  Pros:
     - No changes required for existing integrations from vendors
     - No changes to Nuts RFC
   - 👎 Cons:
     - Nuts v1 JSON-LD context must be altered
     - Weird signature validation processing, which depends on VC context & type
     - Requires migration of existing VCs (otherwise historic VCs will become invalid)

**Comment by reinkrul** [comment]
Release v4 patch version with:

- Support for Nuts v2 JSON-LD context, for forward compatibility with v5
- Remove hardcoded check: NutsAuthorizationCredential v1 MUST contain LegalBase (already present on master/v5 branch)

**Comment by woutslakhorst** [comment]
I agree on #1573 as a general good idea.

The searching is a problem since technically it's correct but functionally a bit annoying. The functional requirement is actually: "give me valid credentials with which I can access a given resource (and I don't care about which version)". This probably requires an abstraction layer, similar to configurable indices and configurable trust.

For the rest of the problems: create a V1.1 for the current context and add legalBase under a different name.

**Comment by reinkrul** [comment]
Fixing by releasing v4.3 which doesn't require `legalBase`: see https://github.com/nuts-foundation/nuts-node/issues/1580#issuecomment-1288880589
