### ISSUE TITLE
JSON-LD context tracking issue

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1580]
The story of Alice in Wonderland going down the rabbit hole to shave a yak:

- For v5 we decided we want to validate that all fields are defined in the JSON-LD context, to avoid VCs containing data not protected by the signature: https://github.com/nuts-foundation/nuts-node/issues/1032
- Bug found: v1 JSON-LD context does not define `legalBase`
  - We can't add it to the context, because it would invalidate the signature of existing VCs
  - https://github.com/nuts-foundation/nuts-node/issues/1452
  - Solution: introduce new v2 JSON-LD context, which defines `legalBase`
- Bug found: VCR requires `NutsAuthorizationCredential` to contain `legalBase`
  - https://github.com/nuts-foundation/nuts-node/issues/1561
  - Solution: only require v2 `NutsAuthorizationCredential` to contain `legalBase`
- Bug found: on release of v5, which must be compatible with v4, nodes running the latter won't be able to process v2 `NutsAuthorizationCredential`
  - Solution: release v4.3.0 release which;
    - adds support for v2 `NutsAuthorizationCredential`
    - removes requirement for `legalBase` on v1 `NutsAuthorizationCredential`
- Bug found: VCR search for v1 doesn't return v2 credentials and vice versa, due to JSON-LD context base specifying a version in its URL.
  - https://github.com/nuts-foundation/nuts-node/issues/1574
  - Solution:
    - Release v4.3 and v5 with lenient search, returning both v1 and v2 credentials
    - Change v2 JSON-LD context base to something versionless
       - Decision required: use a URL or a URI/IRI to avoid confusion of `@context` location (URL) or context base (inside the context itself).
         - Everyone seems to use a URL, so maybe do the same to avoid future (undiscovered as of yet) incompatibility. Consider using a subdomain (e.g. `schema.nuts.nl` or `rdf.nuts.nl`) to avoid future collisions.

**Comment by woutslakhorst** [comment]
> VCR search for v1 doesn't return v2 credentials and vice versa, due to JSON-LD context base specifying a version in its URL.

Not a bug, a feature.

**Comment by reinkrul** [comment]
We decided to not fix `legalBase`. This means:

1. Nuts JSON-LD context v1 will stay as-is
2. Upcoming v4.3 release will remove validation of `legalBase`
3. Introduction of Nuts JSON-LD context v2 will be reverted
4. RFC014 will be altered: `legalBase` will be removed
5. Upcoming v5 release will require all passed fields to be defined in the context
