### ISSUE TITLE
Support NutsComm path prefixes

### ISSUE THREAD

**Issue by jarimayenburg** [nuts-foundation/nuts-node#1588]
The gRPC server currently always runs on the root path of the NutsComm endpoint. If a reverse proxy in front of the Nuts node is configured to receive both gRPC and regular HTTP traffic on port 443, it will have to determine either by hostname or by path whether to send the request to the gRPC port on the application or the HTTP port.

Due to G1 TLS certificate requirements, it's nice to be able to use as few hostnames as possible, so it's preferable to use paths for this. The reverse proxy could be configured to rewrite paths as follows:
```
<host>:443/http/internal --> <host>:80/internal
<host>:443/grpc --> <host>:5555/
```

However, the gRPC client expects the gRPC server to always run on the base path of the NutsComm endpoint. It's therefore not possible to configure the NutsComm endpoint as e.g. `grpc://<host>:443/grpc`.

It would be nice to properly support URLs for the `network.grpcaddr` config, so a node can configure a path prefix. This would be a breaking change, because nodes supporting older versions would be unable to use NutsComm endpoints with path prefixes.

**Comment by jarimayenburg** [comment]
@reinkrul If we were to implement this quickly, could we still include it in the V5 release? Cause if so, I'll get started on it immediately.

**Comment by jarimayenburg** [comment]
You mean because we'd be managing nodes for multiple service providers hosted in our system? This is just a service that we provide to these service providers, basically provide a node along with some other services (e.g. FHIR interface with Zorginzage implementation) as a SaaS solution. There's always the option for them to host it in their own infrastructure if they choose to do so.

**Comment by jarimayenburg** [comment]
Seems like gRPC doesn't like the idea of path prefixes. The maintainers don't go out of their way to block it but they don't actively maintain it either
https://github.com/grpc/grpc-dotnet/issues/110#issuecomment-465349311

**Comment by reinkrul** [comment]
We're not going to support it at this moment, reasoning:

- It can be supported through other means (expose additional ports, additional subdomains in SAN)
- It is not supported by gRPC (custom work for every implementation)
- It promotes running many Nuts nodes using the same certificate, which is a risk for the vendor and thus for Nuts itself.
