### ISSUE TITLE
Core: rename engine interfaces to make them compliant with Go convention

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1622]
Our engine interfaces are "ables":

- `Runnable`
- `Migratable`
- `Configurable`
- `Diagnosable`
- `Injectable`
- `HealthCheckable`
- `Routable`

Go generally names interfaces as things that do something, e.g. `Read() []byte` is defined by `io.Reader`. We should consider renaming our interfaces to make them compliant with the Go convention.

Others:
- `Named`
- `Engine`
- `ViewableDiagnostics`

**Comment by gerardsn** [comment]
This is for one-method interfaces only
https://go.dev/doc/effective_go#interface-names
> By convention, one-method interfaces are named by the method name plus an -er suffix or similar modification to construct an agent noun: Reader, Writer, Formatter, CloseNotifier etc.

**Comment by reinkrul** [comment]
I think consistency here (all are "-ables", while some have just 1 function) is more important than following convention: otherwise we would get a weird mix. Agreed, @woutslakhorst @gerardsn @pascaldekloe ?

**Comment by woutslakhorst** [comment]
`Router`, `Runner`, `Migrater` and `Configurer` are easy? The others could require a totally different name to adher to convention.

**Comment by reinkrul** [comment]
Thought about that too, but `Router` (something that is actively routing) and `Routable` (something that can be routed to). You could say `RouteProvider` but that gets ugly.

I'm closing this as a non-issue because I don't think it makes much of a different in code quality, given the effort.
