### ISSUE TITLE
VCR: Revoked VCs spam log using SearchVCs

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1628]
When searching for VCs and encountering revoked VCs, the Nuts Node logs an info message for every revoked VC that would otherwise be returned:

```
 level=info msg="Encountered invalid VC, omitting from search results." credentialID="did:nuts:Fhn6hdQQpe29SXPpcASpttJLqZzFyHTtfyRmGkWpzVp3#d9f56379-38ae-4469-814e-f7747da49171" error="credential is revoked" module=VCR
```

This should be a trace log at best (when err = revoked)

**Comment by woutslakhorst** [comment]
Added bug label because logs need to be clean on production
