### ISSUE TITLE
Docker: inconsistent tagging

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1629]
- Demo EHR uses semantic version without prefix "v" (e.g. "5.0.0")
- Registry Admin uses semantic version without prefix "v" (e.g. "5.0.0")
- Nuts Node uses semantic version **with** prefix "v" (e.g. "v5.0.0")

This is confusing, should be consistent.

**Comment by reinkrul** [comment]
Will be fixed in v6

**Comment by woutslakhorst** [comment]
should all be without `v`
