### ISSUE TITLE
VCR: invalid VC is still retried

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#1633]
```
ERRO[0055] Retry failed error="canonicalization failed: unable to normalize the json-ld document: loading remote context failed: Dereferencing a URL did not result in a valid JSON-LD context: https://hinq.nl/identifiers/v1" eventSubscriber=vcr_vcs module=Network txRef=da1a709776ebbc110afd4a6645083e46ecf31e8964ccabe6272aa5df20ba6012
```

**Comment by gerardsn** [comment]
The error message `Retry failed` indicates that the retry mechanism is terminated. This happens after 100? retries, or if any of the retries _after the first_ retry returns an `EventFatal`. I get a `Notify event dropped` for the same tx (as expected). 
```
time="2022-11-10T14:37:23Z" level=error msg="Notify event dropped" error="canonicalization failed: unable to normalize the json-ld document: loading remote context failed: Dereferencing a URL did not result in a valid JSON-LD context: https://hinq.nl/identifiers/v1" eventSubscriber=vcr_vcs module=Network txRef=da1a709776ebbc110afd4a6645083e46ecf31e8964ccabe6272aa5df20ba6012
```
My best guess is that your notifier failed on the first attempt due to a write lock or something like that, and got terminated on the second attempt?

**Comment by woutslakhorst** [comment]
My events DB is full of:
```
{"error":"canonicalization failed: unable to normalize the json-ld document: loading remote context failed: Dereferencing a URL did not result in a valid JSON-LD context: https://hinq.nl/identifiers/v1","hash":"ba1e368f761e295188c9d5911ba1bfecd0b966c59107c5cf8b29a0aba01eb678","retries":101,"transaction":"ba1e368f761e295188c9d5911ba1bfecd0b966c59107c5cf8b29a0aba01eb678","type":"payload"}
```
Could it be the case that these were already here (as retry) and are not removed. So when in the DB before the fix, they still are after?

**Comment by gerardsn** [comment]
The regular retry mechanism stops at 100 retries, so the `"retries":101` indicates that this event did encounter an `EventFatal`.

Failed events are not cleared from the events DB by design. They can be queried using /internal/network/v1/events.

**Comment by woutslakhorst** [comment]
but why didn't it stop at 20?

**Comment by gerardsn** [comment]
It was probably stopped on the second attempt. 

From the `notifier.notifyNow` method:
```
if errors.As(err, new(EventFatal)) {
	// mark as failed event
	dbEvent.Retries = maxRetries  
	err = retry.Unrecoverable(err)
}
```
An `EventFatal` fast forwards to `maxRetries`. This is incremented by 1 again to 101 before the error is actually returned. (and this is also how I know that this is an EventFatal vs actually 100 retries.)

**Comment by woutslakhorst** [comment]
> The regular retry mechanism stops at 100 retries, so the "retries":101 indicates that this event did encounter an EventFatal.
Just hit me, we set it to +1 manually.....

There's no way to delete failed events is there? We should probably add it?
