### ISSUE TITLE
Missing documentation on default IRMA public endpoint

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#1646]
According to code it should live at `/public/auth/irmaclient/session` but no documentation can confirm this.....

**Comment by reinkrul** [comment]
Why and what should it be documented?

**Comment by woutslakhorst** [comment]
To start with the fact that the above mentioned URL is the default URL you have to configure in irma frontend js packages.

**Comment by woutslakhorst** [comment]
This is done by the node, but best to add it to be complete
