### ISSUE TITLE
Upgrade irmago to v0.11.0

### ISSUE THREAD

**Issue by stevenvegt** [nuts-foundation/nuts-node#1655]
https://github.com/privacybydesign/irmago/releases

**Comment by woutslakhorst** [comment]
There's already a dependabot PR but they broke our tests by not being race condition safe

**Comment by stevenvegt** [comment]
Ah, I see:
https://github.com/privacybydesign/irmago/issues/268
And
https://github.com/nuts-foundation/nuts-node/pull/1644
