### ISSUE TITLE
Bootstrapnodes can send private VCs over an unauthenticated connection

### ISSUE THREAD

**Issue by gerardsn** [nuts-foundation/nuts-node#1664]
Connections to bootstrapnodes are accepted as authenticated, even if authentication fails (failed authentication is logged). This allows private VC exchange over unauthenticated connections, even in strict mode. (possibly allows DIDComm in the future too)

Unauthenticated connections solve a chicken-egg problem: need to a connection with the network to sync to get the details to authenticate the connection. 

We can't authenticate the connection as soon as the information becomes available since this could kill the synchronization process: 
- If the bootstrap node has changed its NutsComm/certificate since inception, authentication fails as soon as its first NutsComm address is received and the connection will be dropped. 
- If all other discovered NutsComm endpoints up to that point in the DAG are offline, no peers are remaining to complete synchronization.
- Makes changing NutsComm impossible in a multi-graph scenario

Proposal:
1. boostrap nodes should be removed from the configuration after initial synchronization
2. marking these connections as unauthenticated prevents the exchange of private VCs and enforces step 1

Does this impact HA setups?

**Comment by woutslakhorst** [comment]
> Does this impact HA setups?
Don't think so, there the problem lies more with your own nodes upgrading their connections when the nodeDID/NutsComm address is registered.

**Comment by woutslakhorst** [comment]
A bootstrap node should only provide a node with public transactions. Then the node should setup its nodeDID, remove the bootstrap node and restart

**Comment by reinkrul** [comment]
Alternative solution: don't authenticate bootstrap nodes. Ideally there are public bootstrap nodes (e.g. hosted by Nuts foundation) that will never send you private VCs (so you don't need to remove them).
