### ISSUE TITLE
Network: increase max. backoff and add reset API

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1675]
The current back-off for outbound connectors is bound to max. 1 day, meaning it will reconnect at least once a day. But if there's (many) endpoints that are abandoned, it will still clutter the log. Thus, the max. backoff should be increased (suggestion: 1 week), and:

- Allow it to be configured
- Add an API call (and CLI) to Network module which resets the backoff

**Comment by woutslakhorst** [comment]
> Add an API call (and CLI) to Network module which resets the backoff

That would also require to know which addresses have a backoff.

**Comment by reinkrul** [comment]
You can derive that from diagnostics

**Comment by woutslakhorst** [comment]
> You can derive that from diagnostics

Which will be changed as soon as that list gets too long.... (which it already is), why do I want to look at 100 ngrok addresses in my list?

**Comment by reinkrul** [comment]
Should probably be a sub-diagnostic, maybe served from `network` itself, since it's still useful to be able to view:

```
/status/network/connectors
```

**Comment by woutslakhorst** [comment]
The general idea is to have diagnostics and logs clean. Nodes that are down should be visible but nodes that have been abandoned should be gone.

**Comment by reinkrul** [comment]
Outbound connectors diagnostics are being moved to separate page: https://github.com/nuts-foundation/nuts-node/pull/1966
