### ISSUE TITLE
Decryption race condition

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#1688]
Decrypting the PAL header (or other future decryption actions) is done by getting the latest DID Document. If a key rotation has occurred, an older key might be able to decode but this is currently not done.

This is a broader issue with encryption/decryption and legacy keys. We might have to say that encryption/decryption with asymmetric keys from the DID Document can only be used in runtime (timewise) use-cases?

**Comment by reinkrul** [comment]
We currently don't remove rotated keys (https://github.com/nuts-foundation/nuts-node/issues/1660) but if we do, you can't decrypt the PAL header after key rotation has occurred (because now the private key is gone).

We can currently only solve this by saying PAL is a runtime-property, which can only be checked in the present (with some delay to account for network latency and key rotation). But that means it can't be used to exchange historic private TX payload.

It's really just a transport-level ACL: to determine whether the other party is allowed to receive it. Would DIDComm be able to solve this?

**Comment by woutslakhorst** [comment]
Backport to V5

**Comment by woutslakhorst** [comment]
> It's really just a transport-level ACL: to determine whether the other party is allowed to receive it. Would DIDComm be able to solve this?

no

**Comment by woutslakhorst** [comment]
If you rotate an asymmetric encryption key, you usually decrypt all symmetric keys and then re-encrypt them. In our case this would not be possible since encrypted data is on-chain. The encryptor could detect new keys and re-issue any VC. This really feels like a bandaid solution. A cleaner solution would be to reverse the responsibility of who must guarantee the delivery. This is currently the case for the wallet owner. If we shift this to the issuer, then it can have a retry queue which can re-encrypt a message each time it retries it. If there's a direct connection between the issuer and wallet owner, then encryption isn't even needed.

**Comment by woutslakhorst** [comment]
We could migrate everything to [OID4VCI](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html) with the pre-authorized code flow.

This would eliminate the need for authenticated grpc connections, ECIES encryption, PAL headers and maybe even the client certificates (at some point)

**Comment by woutslakhorst** [comment]
OIDVCI has gotten an update on 30th of December 2022. DIDs are now mentioned and supported.

Making the credential issuance a synchronous process would make this a non-issue

**Comment by gerardsn** [comment]
OpenID4VCI is being implemented and will obsolete the private transactions. Do the DidComm messages (kik-v) have the same problem? If not we can close the issue

**Comment by woutslakhorst** [comment]
> OpenID4VCI is being implemented and will obsolete the private transactions. Do the DidComm messages (kik-v) have the same problem? If not we can close the issue

DidComm messaging is runtime so during a key rotation "a message" could fail but when attempted again it succeeds. Nothing will be permanently broken. So could be closed I guess.
