### ISSUE TITLE
Core: enable strict mode by default

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1701]
Makes it safer.

- [ ] Update documentation #1796 
- [ ] Update nuts-network-local https://github.com/nuts-foundation/nuts-network-local/pull/32
- [ ] Update nuts-workshops https://github.com/nuts-foundation/nuts-workshops/pull/38
- [ ] Update nuts-go-e2e-tests https://github.com/nuts-foundation/nuts-go-e2e-test/pull/54
- [ ] Update nuts-getting-started https://github.com/nuts-foundation/nuts-getting-started/pull/1
- [ ] Update performance-test https://github.com/nuts-foundation/performance-test/pull/6

(use https://github.com/search?q=org%3Anuts-foundation+nutsfoundation%2Fnuts-node&type=code)

**Comment by woutslakhorst** [comment]
also update repos that are used in development: nuts-network-local and such
