### ISSUE TITLE
NTS-010: POST request with parameters in URL

### ISSUE THREAD

**Issue by stevenvegt** [nuts-foundation/nuts-node#1724]
**Description:**
The endpoint `/internal/network/v1/reprocess` only accepts a POST method, but also uses a query parameter in the URL.

**Technical description:**
The endpoint `/internal/network/v1/reprocess` accepts a parameter type in the URL and there is no other POST body value.

**Impact:**
This issue is not directly affecting the security of the application, but it is a weird behavior. Accepting a POST request with URL parameters only, fails the purpose of POST method.

**Recommendation:**
Change the submission of the parameter as POST body instead of in the URL. If possible, it might also be good to implement basic authentication requirement over this endpoint, as the documentation mentions Transactions are not verified and added to an in-memory queue. For large sets of transactions, memory usage can become high.

**Comment by reinkrul** [comment]
@woutslakhorst why was stil style chosen?

**Comment by woutslakhorst** [comment]
It must be a POST since you're changing server state. It could have been modelled as submitting a "job" with a regular body. That would have been a bit more work. I can't see the security issue in this finding though.

**Comment by stevenvegt** [comment]
Ok, so close with wontfix?

**Comment by woutslakhorst** [comment]
wont fix
