### ISSUE TITLE
VCR: Add CLI commands

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#173]
What would be good commands to add?

- trust/untrust
- etc

**Comment by reinkrul** [comment]
- `search [concept] [name/ID]` (concept optional?)
- `trust [issuer DID] [type]`
- `untrust [issuer DID] [type]`
- `trusted` (lists trusted issuers)

**Comment by woutslakhorst** [comment]
First focus will be on trust: add/remove and list (un)trusted.
