### ISSUE TITLE
Network failed event list should return moment last retried

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1731]
Helpful for debugging.

```
      {
        "error": "",
        "hash": "a7c62cef74e0c0891ae0ac8afbf7cddf82c148345caa991d8c48418252cd915d",
        "retries": 20,
        "transaction": "a7c62cef74e0c0891ae0ac8afbf7cddf82c148345caa991d8c48418252cd915d",
        "type": "payload"
      },
```

**Comment by gerardsn** [comment]
last attempt is currently not tracked by events, so it would have to be added. 
- what is the preferred time format?
- a reload of the backoff for the retry mechanism after a restart is currently based on the number of retries. Should this be changed to time-based if we keep track of the last retry attempt?

**Comment by reinkrul** [comment]
> what is the preferred time format?
RFC3339

> a reload of the backoff for the retry mechanism after a restart is currently based on the number of retries. Should this be changed to time-based if we keep track of the last retry attempt?
Out of scope issue; this is just analysis
