### ISSUE TITLE
Unknown JSON-LD context should not remain as failed event.

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#1732]
Currently it remains with a retry count of 101 in the failed event list.

It should not be added, and the current entries should be removed via migration.

```
      {
        "error": "canonicalization failed: unable to normalize the json-ld document: loading remote context failed: Dereferencing a URL did not result in a valid JSON-LD context: https://hinq.nl/identifiers/v1",
        "hash": "fe90fc98c75281adfb50cf245f4de3dc3bec7e27c32a39273580f45ee7a45b70",
        "retries": 101,
        "transaction": "fe90fc98c75281adfb50cf245f4de3dc3bec7e27c32a39273580f45ee7a45b70",
        "type": "payload"
      }
```

**Comment by reinkrul** [comment]
There's no way to distinguish disallowed JSON-LD context URLs (our own `filteredDocumentLoader`) from remote document loading errors (e.g., time-outs). This is needs a change in piprate/json-gold (thrown away `err`).
