### ISSUE TITLE
VDR: Failed event on controller

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#1754]
On the stable network the following error is in my events list:

```{"error":"network document not signed by one of its controllers","hash":"fdec9e572b0ab2955c22c0de4c62654a0b46f180150fb2f5b068b1a0fd2f8fb8","retries":101,"transaction":"fdec9e572b0ab2955c22c0de4c62654a0b46f180150fb2f5b068b1a0fd2f8fb8","type":"payload"}```

 This is an error returned by the VDR which checks the controller hierarchy. Note that the TX has been correctly signed.

Question is if this is recoverable? Could mishaps happen due to timing/parallel updates?

**Comment by reinkrul** [comment]
This _should_ not be possible using the Nuts Node and CLI/API (or at least, should be quite hard to achieve), so question is whether somebody really did his/her best to cause this, or it's a bug in the DID document lifecycle.

Action: find out what caused this situation (maybe try to find out who caused it), and whether it's something we need to fix/document

**Comment by reinkrul** [comment]
```
ransaction fdec9e572b0ab2955c22c0de4c62654a0b46f180150fb2f5b068b1a0fd2f8fb8:
  Type: application/did+json
  Timestamp: 2022-10-24 08:24:54 +0000 UTC
  Prevs: ed6c24805488336a9b1d2077e3b478dce1fe3f4096976b850f0cc139ff44381a eed6b9dcbc171d9b3aee711831a66b83d8c66e7d683d7975f4486c6470e6e618 a4bceb3869ae54389230926ca5a8e41c79fed74b5e703339fe6caae796227210
```

**Comment by reinkrul** [comment]
Analyzed using https://github.com/nuts-foundation/data-viewer;

```
NUTS_NODE_ADDRESS=<address> ./data-viewer analyze did-graph did:nuts:EeJ9pj1EH2qmc3oR7mpyAJvaTWoiCN1RDzGPzJsqzE6L fdec9e572b0ab2955c22c0de4c62654a0b46f180150fb2f5b068b1a0fd2f8fb8 > test.dot && dot -Tpng test.dot -o out.png
```

![out](https://user-images.githubusercontent.com/1481228/213664022-36ae5d9f-693f-4be6-a17b-90354170e8a1.png)

**Comment by reinkrul** [comment]
According to our business rules, the result should be a conflicted, but nonetheless active, DID? Since it merges the deactivated version with the bottom one. But it appears the update is rejected because it resolves the latest version to the deactivation TX, starting with `7118`, while it actually refers (using prev) to a version, not deactivated (TX starting with `eed6`).

The resolve is done at `vdr/ambassador.go:267` (v5.0.2):
```
currentDIDDocument, currentDIDMeta, err := n.didStore.Resolve(proposedDIDDocument.ID, &types.ResolveMetadata{AllowDeactivated: true})
```

**Comment by woutslakhorst** [comment]
So bug?

**Comment by reinkrul** [comment]
> Resolving of controllers is done in `resolveControllers`. It should indeed use one of the prevs to find the 'currentDocument'.

We added the `prev` of the previous DID document version last year I think, I don't remember whether we had a reset after that? In other words; if we changed the resolve of `currentDIDDocument` to be (one of) the `prev`s, are there DIDs that break because they don't refer their previous version?

**Comment by woutslakhorst** [comment]
We already do that with transaction signature verification?

**Comment by woutslakhorst** [comment]
We'll first fix the bug and then test on development if all is fine. We're nog ignoring the failure yet.

**Comment by woutslakhorst** [comment]
Retry has to stay for now due to race condition
