### ISSUE TITLE
CRL: revocation checking fails when unrelated CRL can't be updated

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1761]
`crl/validator.go:256`:

```go
// If the CRL validator is outdated kill the connection
if !v.IsSynced(maxValidityDays) {
    return errors.New("CRL database is outdated, certificate revocation can't be checked")
}
```

If _any_ CRL is outdated, it blocks the token from being verified. But it should only check the relevant root CAs and intermediate CAs (the ones used by the peer).

**Comment by woutslakhorst** [comment]
Why the reopen?

**Comment by reinkrul** [comment]
Found an edge case where it could go wrong; https://github.com/nuts-foundation/nuts-node/issues/1883
