### ISSUE TITLE
Docker user should not run as root

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1779]
See https://www.howtogeek.com/devops/why-processes-in-docker-containers-shouldnt-run-as-root/

Best to use a UID >10.000 range: https://elastisys.com/howto-stop-running-containers-as-root-in-kubernetes/ (also see https://medium.com/@gggauravgandhi/uid-user-identifier-and-gid-group-identifier-in-linux-121ea68bf510)

**Comment by stevenvegt** [comment]
Can you provide a bit more info?

**Comment by VPelt** [comment]
If a application within a container runs as a root user there is a greater chance that an exploid leads to executing tasks within the container with root level permissions. Many (file) permission checks can be bypassed if i can execute commands as root.

A simple example would be if the nuts process had only read-only rights to a certificate and corresponding directory an exploid in an api that would allow an attacker to write a file to disk still wouldn't allow the attacker to write or overwrite a certificate. Or to allow source code to be modified by the nuts process itself.

To minimize this risk and reduce potential attack surface it is a best practice to run an application within a container as a non-root user. Our kubernetescluster is configured to scan for this and not allow any containers to run as a root user

a minimum we would need therefor is a 'nuts' user which runs the nuts proces, and in the values.yaml a configuration equivalent to

```
securityContext: 
  runAsNonRoot: true
  runAsUser: 1000
```

**Comment by woutslakhorst** [comment]
So this is mainly a Helm chart configuration problem?

**Comment by woutslakhorst** [comment]
ahh yes, `/opt/nuts` has been created as root. This will require a migration for existing nodes that do not mount the directory with certain permissions. I'm adding this issue to the v6 milestone
