### ISSUE TITLE
Refuse transactions when node is not yet synchronized with network

### ISSUE THREAD

**Issue by stevenvegt** [nuts-foundation/nuts-node#1802]
When a node is not connected to the network, and a user creates a DID, this node has a genesis transaction and cannot be connected to another network anymore. This often happens and confuses the users resulting in long debugging sessions.

To prevent this, we can add a check:
* If this node is not a "genesis node"
* And if this node is not connected to a network
* And strict mode == true?
* Then: Refuse creating new DIDs

**Comment by woutslakhorst** [comment]
If we migrate to the mult-chain, this will be solved since there no longer is a single root.

**Comment by woutslakhorst** [comment]
network will be removed. Won't fix.
