### ISSUE TITLE
Docs: rework Getting Started documentation and Docker setups

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1804]
People keep making mistakes when setting up their nodes, primarily:
- confusing vendor/care organizations roles (and what to register on what)
- don't know what `NutsComm` is all about and its relation to the TLS certificate and DID documents
- order of starting node, letting it sync, creating vendor DID document and then restarting

We spend lots of effort on trying to prevent this with more documentation, but now it looks like there's too much of it. Especially when it comes to the getting started. Issues:

- We have 2 repos with test setups, `nuts-network-local` and `nuts-getting-started` (last one is now archived)
- `nuts-network-local` is far too complicated when starting multiple nodes, with having to specify up to 9 Docker Compose profiles to start all auxillary apps (Demo EHR, Admin, FHIR server)
- The repo name `nuts-network-local` is too technical and doesn't tell you want it's purpose is (but the name `nuts-getting-started` is too narrow).
- Getting Started chapter 4 (creating customers) includes the same steps as chapter 3 (connecting to a network), but in different wording and level of detail.

Ideas:
- Restructure Getting Started documentation, with maybe a graphic (like a developer's journey) of the integration path
  - Include node bootstrap, because now steps are being mixed up
- Simplify `nuts-network-local`, keeping the flexibility (I don't want to start heavy-weight FHIR servers when I just want to run 2 nodes) but make it easier to start auxillary apps.

**Comment by woutslakhorst** [comment]
Actually the most important step by step documentation is in nuts-workshops. The documentation on read the docs should only refer to the OS reference implementation. Concepts like vendor and organisation are not really part of this. Maybe it's better to move Bolt related documentation (implementation, workshops, etc) to the wiki?

Besides docs:
- Implement discovery so the node reconnects when DID Documents change.
- Multi chain will remove the "connect first then create a NodeDID" ordering.
- Do something clever with NodeDID generation and configuration

**Comment by woutslakhorst** [comment]
moved to wiki.
