### ISSUE TITLE
Build storage back-end based on storage API

### ISSUE THREAD

**Issue by stevenvegt** [nuts-foundation/nuts-node#1819]
Create new storage backend which implement the /crypto/storage Storage interface
Implement it using a generated HTTP client based on the API specification #1820 .

**Comment by reinkrul** [comment]
TODO: documentation

**Comment by stevenvegt** [comment]
Done with:
* https://github.com/nuts-foundation/hashicorp-vault-proxy/pull/17
* https://github.com/nuts-foundation/nuts-node/pull/1898
