### ISSUE TITLE
wrong status code for SignJWT api error returns

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#182]
It returns a 400 for all signJwt errors. It should return 400 for `ErrKeyNotFound` but a 500 in all other cases.

**Comment by gerardsn** [comment]
should this be 400 or 404 for `ErrKeyNotFound`?

**Comment by woutslakhorst** [comment]
the resource that is not found is not in the url (that would justify a 404) but in the body as part of the operation. So 400 as it is now.
