### ISSUE TITLE
Create a crypto storage API specification

### ISSUE THREAD

**Issue by stevenvegt** [nuts-foundation/nuts-node#1820]
Create a API specification:

Based on https://developer.hashicorp.com/vault/api-docs/secret/kv/kv-v1
* list secrets (might not be needed)
GET /secrets/keys/
* store / update secret
POST /secrets/keys/:id
* read secret
GET /secrets/keys/:id
* delete secret
DELETE /secrets/keys/:id

**Comment by reinkrul** [comment]
Removed from v5.1 milestone since it doesn't necessarily need to be in v5

**Comment by stevenvegt** [comment]
Closed by #1828
