### ISSUE TITLE
HTTP: Rework API auth using user-owned private key

### ISSUE THREAD

**Issue by beardedfoo** [nuts-foundation/nuts-node#1821]
The internal API endpoints are not protected with authentication. We would like to implement this functionality using JWT bearer tokens with a tool for callers to generate the JWT's.

TODO:
- [x] Update "API Authentication" documentation
- [x] Update Demo EHR
- [x] Update Registry Demo
- [ ] Optional: Finish JWT generator (tests, documentation, binary release)

**Comment by reinkrul** [comment]
Typical use cases of the internal APIs:

- Vendor's administrative app managing DID documents and verifiable credentials
- Vendor's EHR app searching the registry, and creating/using NutsAuthCredentials
- System administrator

**Comment by beardedfoo** [comment]
Regarding: """Applications (consuming the API) will be generally running in a container, using ssh-agent there might not make sense"""

These applications can sign their JWT's using an unencrypted (passwordless) key, and will not need to strictly use the ssh-agent to do their signing.

**Comment by beardedfoo** [comment]
This is being built up here:
https://github.com/nuts-foundation/nuts-node/tree/feat/api-auth

Further changes required in that branch are:
- unit tests
- keep old token middleware available
- classify and authenticate API calls as rw vs. ro (or some other role-based model)

The most difficult work required for this feature was implemented here:
https://github.com/nuts-foundation/jwt-generator

**Comment by reinkrul** [comment]
Roles could be added later? (Since it's not breaking)

**Comment by beardedfoo** [comment]
https://github.com/nuts-foundation/nuts-demo-ehr/pull/354

**Comment by beardedfoo** [comment]
https://github.com/nuts-foundation/nuts-registry-admin-demo/pull/116
