### ISSUE TITLE
HTTP: Remove promhttp metrics

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1838]
Original issue: 

> Which is really weird and useless. Due to incorrect usage of the API.
> Should probably use `echo.WrapMiddleware(promhttp.Handler())` to register (global) middleware that records any path, rather than just `/metric`

New goal and scope: remove API metrics from `/metric`

**Comment by woutslakhorst** [comment]
We decided not to monitor API calls since this is usually done by the reverse proxy.
```router.Use(e.prometheusMiddleware.HandlerFunc)``` should not be there anymore?

See #1770
Soo issue should be called: leftover API metrics should be removed

**Comment by reinkrul** [comment]
I agree

**Comment by gerardsn** [comment]
I think these can stay. It is a limited set of counters on 1 endpoint (see below). So there is no security risk in the context of NTS-009 #1716. Note that `promhttp.Handler()` is also the handler for all other metrics, so pulling these apart might be difficult. Besides complexity, I think that this specific endpoint is useful to have in the metrics as it is an indication how reliable the other metrics might be.

```
❯ http :11323/metrics | grep promhttp
# HELP promhttp_metric_handler_requests_in_flight Current number of scrapes being served.
# TYPE promhttp_metric_handler_requests_in_flight gauge
promhttp_metric_handler_requests_in_flight 1
# HELP promhttp_metric_handler_requests_total Total number of scrapes by HTTP status code.
# TYPE promhttp_metric_handler_requests_total counter
promhttp_metric_handler_requests_total{code="200"} 6
promhttp_metric_handler_requests_total{code="500"} 0
promhttp_metric_handler_requests_total{code="503"} 0
```

**Comment by woutslakhorst** [comment]
I believe they only count the number of times `/metrics` is called....

But if removing them is more work than keeping them....

**Comment by gerardsn** [comment]
> I believe they only count the number of times `/metrics` is called....

Exactly, it counts the 200,500,503 status codes returned for calls to `/metrics`, and those currently in-flight (could indicate (accidental) DoS on the endpoint).

> But if removing them is more work than keeping them....

So closing this issue for now.
