### ISSUE TITLE
DIDMan: organization search result is confusing when duplicate VCs exist

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1839]
When there are multiple VCs for the same DID with the same (organization) properties, the search result contains the same search results multiple times. This is technically correct, since they're all different VCs, but confusing to the user.

We should either:
- Deduplicate the search result (since, after all, the API is meant to search for organizations, not for VCs)
- Add VC ID to the results (this might even be usable for use cases, not having to do an additional VC search?)

**Comment by woutslakhorst** [comment]
DIDman will be removed. Won't fix.
