### ISSUE TITLE
Racy behavior during shutdown due to obscure asynchronous programming

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1900]
Components which start goroutines themselves typically look like this (e.g. our modules/engines):

- Have a non-blocking `Start()` function, which starts one or more goroutines. These are passed a context.
- Have a non-blocking `Stop()` function, which cancels the passed contexts to instruct goroutines to stop.

Since `Stop()` is non-blocking, it will not wait until all goroutines have finished processing.

An alternative approach we have, is (e.g. `v2.Protocol` and its `diagnosticsMan`/`listHandler`):

- Have a non-blocking `Start(ctx)` function, which starts one or more goroutines. Context is passed through
- There is no `Stop()` function; goroutines are instructed to stop by cancelling the context.

This leads to racy behavior during shutdown: dependencies (typically storage) will already have been shutdown, while dependent goroutines are still trying to do work. We haven't encountered any big issues or data corruption due to this behavior, currently it's only annoying due to it causing error logs. So it should be fixed.

Given Golang's convention of letting callers start a goroutine for your function, instead of starting it yourself, improvements include:

- The component that starts a goroutine is responsible blocking until it shuts down. This yields to the following design patterns:
  - When `Start()` is non-blocking (meaning it starts goroutines), it must provide a `Stop()` function that blocks until all goroutines have exited
  - Components with a `Start()` (blocking) but without `Stop()` will typically be passed a context to signal shutdown
  - When `Start()` is blocking, it must block until all goroutines have exited
  - When starting goroutines, use a `sync.WaitGroup` to wait for them to exit, e.g.:
     ```
    go func(w *sync.WaitGroup) {
			w.Add(1)
			defer w.Done()
			asyncFunc()
		}(w)
    ```
- When issues arise with long-running goroutines blocking shutdown, the `System.Shutdown` function might have to time-out on `Stop()` functions of modules that take too long (or at least log it).

**Comment by reinkrul** [comment]
Instances of race conditions:
```
ERRO[0048] Error handling message                        error="unable to add received transaction to DAG (tx=ce8f58fe2ebd62a5a3e8a1527923e8c8dcef0cc55284627dc7fad42baeb93e62): database error: database not open" messageType="*v2.Envelope_TransactionList" module=Network peerAddr="nuts-development.woutslakhorst.nl:5555" peerAuthenticated=true peerDID="did:nuts:HSr29Y6qFFSHGPzn9VK7dhpbT14U9epwPhMECRHBwdaQ" peerID=a4d2499f-de62-4933-8e45-b59f80b4679d
```

```
ERRO[0048] Failed to persist backoff                     error="database error: database not open" module=Network
```

**Comment by woutslakhorst** [comment]
when using `ctx` for routine killing, we could also add an `isCancelled` method to the interface. If a piece of logic depends on another engine it should check that engine's context with `isCancelled`. If true do nothing and log a bunch of debug messages.

**Comment by gerardsn** [comment]
remaining leaks are in code that will be removed in te future
