### ISSUE TITLE
VCR: revocation returns 500 when VC is not found

### ISSUE THREAD

**Issue by gerardsn** [nuts-foundation/nuts-node#1902]
```
curl -X 'DELETE' 'localhost:1323/internal/vcr/v2/issuer/vc/{id}' -H 'accept: application/json'
{"detail":"could not revoke (id=...): not found","status":500,"title":"RevokeVC failed"}/
```

API spec for error returns:
```
error returns:

400 - Credential can't be revoked. Most likely due to a missing private key.
404 - Credential is not found
409 - Credential has already been revoked
500 - An error occurred while processing the request
```

**Comment by stevenvegt** [comment]
Let's make clear what this "not found" means. Could be the credential does not exist in the network, but also might mean the credential is not found in the issuer store. This difference should be clear from the error.

**Comment by woutslakhorst** [comment]
@reinkrul wit the latest fix, is a 404 still possible?

**Comment by reinkrul** [comment]
No, it's also removed from the OpenAPI spec (not for v5.0.9, just master)
