### ISSUE TITLE
Lost issuer DB prevents revoking of issued credentials

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#1911]
issued credentials are stored in the issuer db and the vcr. If you lose your issuer db, the network will send you a copy to the vcr. At that point you can see and use the vc but you can no longer revoke it.

"lost" credentials recovered from the network should find their way back into the issuer DB.

**Comment by reinkrul** [comment]
As designed; database should be backed up. But we could introduce a "rebuild" feature; finding all credentials issued by specified issuer, put them in issuer DB.

Maybe we could reconsider the issuer DB and make it more resilient, either by completely eliminating it (always work on VCs received over network, which may not be feasible for private VCs), or making it more like "volatile" storage.

**Comment by woutslakhorst** [comment]
> But we could introduce a "rebuild" feature; finding all credentials issued by specified issuer, put them in issuer DB.

Required since a backup could be missing some VCs but the network already has them. It's hole in the 'feature'.

**Comment by reinkrul** [comment]
The easiest fix is to not check for credential existence. Fix on v5 and release patch version.
