### ISSUE TITLE
VDR: private transactions fail if the node's DID document cannot be found

### ISSUE THREAD

**Issue by gerardsn** [nuts-foundation/nuts-node#1927]
strict mode + unable find the node's own DID document is a fatal error that kills the node. 

In non-strict mode it is not fatal, which results in: cannot find own DID doc -> don't know if private transactions is addressed to me -> a failed event for every private transaction. This also clutters the diagnostics page with these messages:

```
- type: transaction
  hash: e4f301b21c7b2dc04917c60eb55f84dba1d9677425a78c220e7dac90dd74fdc4
  retries: 101
  latest: 2023-02-25T09:47:28.48363339Z
  transaction: {}
  payload: []
  error: 'failed to decrypt PAL header (tx=e4f301b21c7b2dc04917c60eb55f84dba1d9677425a78c220e7dac90dd74fdc4): unable to find the DID document'
```

This can occur when the configured DID is incorrect, or in my case, I deleted `network/data.db` (DAG) + `vdr/didstore.db` (VDR) to trigger resynchronization but left the `NodeDID` in the config.

**Comment by gerardsn** [comment]
The question probably is
1. Should this be a fatal error in non-strict mode as well? This prevents all failed events that a user currently cannot get rid of without direct manipulation of the DB.
2. (how) do we want to support re-syncing from the network. Deleting the VDR means you cannot configure a node DID during re-synchronization, but removing the node DID means that all private transactions addressed to that DID are not processed. (Can be fixed by a `Reprocess` of VCs after syncing and reinstating the node DID. (This does not get rid of the failed events.))

**Comment by woutslakhorst** [comment]
After deletion of files, `reprocess` is always required. This should be in line with the restore procedure. Since the restore procedure does not mention the NodeDID, those docs are also broken?

**Comment by gerardsn** [comment]
The restore procedure probably needs to be extended to restore DBs in a particular order. VCs are always going to fail if the VDR is not there, but the other way is fine. And maybe make a distinction between restoring from backup and from the network.

Still leaves the question of how to get rid of all those failed events when the restore procedure is executed incorrectly. A `reprocess` bypasses the retry mechanism (Notifier), so the events are not updated.

**Comment by woutslakhorst** [comment]
| Still leaves the question of how to get rid of all those failed events when the restore procedure is executed incorrectly. A reprocess bypasses the retry mechanism (Notifier), so the events are not updated / removed from the diagnostics page.

That would require an API then?
So what do we do with this issue? Mark some docs as incorrect and fix them? Create an API for deleting events?
