### ISSUE TITLE
Network: add more info to outbound connector stats

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1929]
- Next connection attempt
- Last occurred error

**Comment by woutslakhorst** [comment]
Outbound connectors should get their own diagnostics endpoint? It's getting way too long. Might already be an issue for that somewhere....

**Comment by reinkrul** [comment]
I had a dejavu and thought this was already implemented (separate endpoint), but couldn't find it. It must be _somewhere_
