### ISSUE TITLE
Auth: Inconsistency on check of organisation credentials

### ISSUE THREAD

**Issue by jelmerterwal** [nuts-foundation/nuts-node#1931]
When using the drawup contract API and using the responding 'message' part for a customer that has an '&' in their 'OrganizationCredential' it will introduce problems when verifying the credentials at the other side (other vendors node).

Example response;
```
Token request validation failed, legal entity mismatch (expected name=xxx & xxx, actual name=xxx &amp; xxx, expected city=xx, actual city=xx)
```

**Comment by reinkrul** [comment]
Due to Mustache template rendering in `auth/contract/template.go:99`; variables with `&` gets replaced with `&amp;`

**Comment by reinkrul** [comment]
Fixed by https://github.com/nuts-foundation/nuts-node/pull/1937
