### ISSUE TITLE
"Notify event dropped" logs on error level

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1932]
When a non-retryable error occurs while processing events, it logs an error message. 
```
stable-2-node-1  | time="2023-02-28T12:07:21+01:00" level=error msg="Notify event dropped" error="canonicalization failed: unable to normalize the json-ld document: loading remote context failed: Dereferencing a URL did not result in a valid JSON-LD context: https://hinq.nl/identifiers/v1" eventSubscriber=vcr_vcs module=Network txRef=ce489a207b469a75b2a0b0973f589eee05008137d7323c1f402dd25c70f0b1cd
```

This is intended behavior (since the action is designed as non-retryable), thus it should not be an error/warn log (indicates administrator action is required).

**Comment by woutslakhorst** [comment]
`Debug` then?

**Comment by reinkrul** [comment]
We decided on warn.

**Comment by woutslakhorst** [comment]
| thus it should not be an error/warn log (indicates administrator action is required).

and

| We decided on warn.

but, but...

**Comment by reinkrul** [comment]
The thought was as follows: this will happen sometimes during development or introduction of a new VC type (which you might need to configure). So you'll want to see the log (it could also indicate misconfiguration of your node), but not as error.

**Comment by woutslakhorst** [comment]
Replace json-ld with vc-jwt?

**Comment by woutslakhorst** [comment]
> It could be the case when 2 nodes share 1 use-case out of 3 and thus have a different config. Then both of them will see a lot of warnings...

@reinkrul using WARN will still generate a lot of logs.

**Comment by woutslakhorst** [comment]
won't fix
