### ISSUE TITLE
Keep initial private key of controlled DIDs

### ISSUE THREAD

**Issue by stevenvegt** [nuts-foundation/nuts-node#1947]
When a new DID document is created and has no self-control, the initial key is not stored (ephemeral key). This is a good practice, however, since we might want to change the network tx format, keeping this key allows us to migrate existing DIDs.

Should be a simple code change:

https://github.com/nuts-foundation/nuts-node/blob/31dd66a42b806e61291cec4a7deb6bfd23d4452d/vdr/didservice/creator.go#L136-L140

Lets discuss.

**Comment by woutslakhorst** [comment]
You have to assume this is already used and widespread. Our admin demo does this for the "customers".

**Comment by reinkrul** [comment]
Also add to verification methods to keep track of private keys.
