### ISSUE TITLE
ProtocolV2 gossip/conversation manager should not manage peers on peerID

### ISSUE THREAD

**Issue by gerardsn** [nuts-foundation/nuts-node#1950]
connection management recently changed from peerID to peerID+nodeDID #1874. 

ProtocolV2 assumed peerIDs are unique, which is no longer true. Message sending/handeling has been updated to reflect this (#1938 #1940). All that remains is the gossip and conversation manager.

**Comment by woutslakhorst** [comment]
What's the impact if not changed before nodes use the "new" setup?

**Comment by gerardsn** [comment]
Connection lookup will always find the first connection that registered the peerID, and its hard to spoof the peerID before it is used.

gossip manager: the spoofer can remove messages from the true peer's gossip queue.

conversation manager: conversationIDs only have meaning to the side that created it. The spoofer can trigger a conversation and not respond. This prevents the node from starting a conversation with the true peer until the other conversation reached its timeout.

**Comment by gerardsn** [comment]
#2024 only fixed the conversation manager
