### ISSUE TITLE
Merge server and client tls.Config in the grpc connection manager

### ISSUE THREAD

**Issue by gerardsn** [nuts-foundation/nuts-node#1959]
Currently the connection manager setup creates a separate config to use in inbound and outbound connections. They both use the same config, but may need some customization incase TLS is offloaded.

Maintaining 1 config should be less susceptible to errors

Both configs always use the same CA's and client cert == server cert

still needs to work with TLS offloading

**Comment by reinkrul** [comment]
(it's not about nuts node config)

**Comment by woutslakhorst** [comment]
So `config.crlValidator.Configure(..)` is done by `NewGRPCConnectionManager()` and `newGrpcServer()`. With the same trustStore.
