### ISSUE TITLE
CRL: should try to update more frequently

### ISSUE THREAD

**Issue by gerardsn** [nuts-foundation/nuts-node#1987]
`validator.updateCRL` only updates the CRL after its `Next Update` time has expired. (so when the CRL is invalid and `validator.IsSynced` will return false)

from [RFC5280](https://www.rfc-editor.org/rfc/rfc5280#section-5.1.2.5)
```
5.1.2.5. Next Update

   This field indicates the date by which the next CRL will be issued.
   The next CRL could be issued before the indicated date, but it will
   not be issued any later than the indicated date. CRL issuers SHOULD
   issue CRLs with a nextUpdate time equal to or later than all previous
   CRLs.  ...
```

The Next Update on pkiO certificates is very infrequently
```
DomPrivateServicesLatestCRL-G1.crl:
	This Update at 2022-11-03 14:22:42 +0000 UTC
	Next Update at 2023-11-02 14:22:41 +0000 UTC
PrivateRootLatestCRL-G1.crl:
	This Update at 2022-11-03 11:59:29 +0000 UTC
	Next Update at 2023-11-02 11:59:28 +0000 UTC
```

Worst case (for pkiO) the current flow fails to mark a certificate as revoked for a year.

**Comment by gerardsn** [comment]
note that both CRLs currently contain 0 revoked certificates (in ~3 years)

**Comment by reinkrul** [comment]
- Introduce a minimum update interval (4h)
- Check CPS of Logius to see if it's really 1 year (or did they make a mistake?)

**Comment by reinkrul** [comment]
Then 4 hours still sounds good.

**Comment by gerardsn** [comment]
from [QuoVadis CPS](https://www.quovadisglobal.com/wp-content/uploads/2020/01/QV_CPS_PKI_Overheid_Organisatie203G20Private20Service20V1.3.pdf) (which is actually issuing end user certificates, the above is the Logius CPS for the rootCA and intermediates)

```
4.9.3.6 Geldigheid CRL
De geldigheid van een CRL is maximaal 72 uur en wordt elke 12 uur gegenereerd.

4.9.7 Frequentie uitgifte Certificate Revocation List (CRL)
QuoVadis zal de CRL ten behoeve van eindgebruiker certificaten tenminste een keer in de 7 kalenderdagen bijwerken en opnieuw uitgevenen de datum van het veld “ Volgende update” zal niet meer dan 10 kalenderdagen zijn na de datum van het veld “Ingangsdatum”.
```

timeframes do not make sense to me, but 4hrs still seems to be a good choice.

**Comment by gerardsn** [comment]
> Then 4 hours still sounds good, I'd say. What happens if an error occurs, is the dependent operation aborted (e.g. TCP connection from other Nuts node)? Since checking more often means more chance for it to go wrong.

if downloading fails, `Sync` returns errors. The SyncLoop just logs these, but if Sync is called ad-hoc it's up to the implementation to decide on this. for the JwtX509Validator (used in UZI validator) its a hard fail and the Auth request is rejected even if the CRL it already has is still valid

**Comment by gerardsn** [comment]
And [KPN](https://certificaat.kpn.com/files/CPS/KPN_PKIoverheid_CPS_Private_Services_v1.0.2.pdf)
```
4.8.6 CRL-uitgiftefrequentie
De update van de CRLwordt om de 15 minuten geïnitieerd, nadat de CRL is gegenereerd wordt de CRL gepubliceerd.Een CRL heeft een geldigheidsduur van vierentwintig uur.
```

**Comment by gerardsn** [comment]
but more importantly, we have already [specced](https://nuts-foundation.gitbook.io/drafts/rfc/rfc008-certificate-structure#3.3-crl) the update frequency at 1 hour
