### ISSUE TITLE
Network: Node DID must be set at startup / remove NodeDIDResolver concept

### ISSUE THREAD

**Issue by gerardsn** [nuts-foundation/nuts-node#2015]
If the node DID is not available at startup, the private transaction request loop is not started.

Currently the `autoNodeDIDResolver` can pickup on new DIDs at any point (in non-strict mode). If this happens after startup, it would appear that a node is able to receive private transactions based on all diagnostics info, but still fails due to the request loop not being started.

Solution is to only auto discover DID once at startup. This is just developer convenience and should still not happen in strict mode. This also allows removal of the `NodeDIDResolver` concept to simplify code.

**Comment by reinkrul** [comment]
I'd like to suggest to fix this for v5.2
