### ISSUE TITLE
Auth: rename RequestAccessToken.requester to something not related to eOverdracht

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#2026]
People keep mixing up `requester` and `authorizer`, since they think `requester` means eOverdracht sender (or receiver, depending on their rationale), but the roles are switched during the process: when the eOverdracht sender calls the receiver's notification endpoint, it acts as `requester`. But when the eOverdracht receiver accesses the FHIR endpoint of the sender, it also acts as `requester`.

Maybe `relying_party` would be better?

**Comment by woutslakhorst** [comment]
`relying_party` would also be interpreted as the receiver...

**Comment by woutslakhorst** [comment]
v1 api is deprecated, won't fix.
