### ISSUE TITLE
Revisit pre-authorized code and access token generation (security)

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#2030]
They both use a quickly thrown together random code generator, but this might need replacing with something securer.

Also check what kind of codes (length/characters) other products are using.

**Comment by woutslakhorst** [comment]
What about just using a 256 secure random for the pre-authorized code?

**Comment by woutslakhorst** [comment]
For the access token we could use our own RFC003 or RFC7523 with DIDs?

**Comment by woutslakhorst** [comment]
What do we do for client authentication in the access token request call?

Options:
- nothing
- some JWT based on DIDs (RFC7523)
- something else

**Comment by woutslakhorst** [comment]
decision:

We do not use client authentication for requesting the access token. The credential request will already feature a signature which contains a c_nonce from the authorization flow.

This will have to be reassessed when using something else than pre-authorized code flow.

For access tokens we'll use secure random tokens (base64 encoded 128 bits) linked to the pre-authorized code and an expiration date. Auth server should clean tokens. Tokens are valid for 15 minutes.

**Comment by reinkrul** [comment]
Summarized: random 128-bit pre-auth codes and access tokens, base64 encoded. TTL is 15 minutes.
