### ISSUE TITLE
Allow the credential to be requested multiple times

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#2031]
The specification states credentials must be re-queryable (with some gotchas, check spec), we now delete them when they are retrieved by the wallet.

**Comment by reinkrul** [comment]
Also see https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#name-multiple-accesses-to-the-cr

**Comment by woutslakhorst** [comment]
But the pre-auth code can only be short lived?

**Comment by woutslakhorst** [comment]
Nothing to do here. The pre-authorized code is removed after authorization. The flow remains and is usable through the access token. The access token is only short lived.
