### ISSUE TITLE
Move endpoints to /n2n

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#2032]
See last comment for solution: move to /n2n

---

There currently is no trust store configured, so it falls back to the OS certbundle.

We should decide which certificates parties should use to secure their OIDC4VCI endpoints and integrate the correct trust store.

Also consider integrating CRL validation.

**Comment by reinkrul** [comment]
Analysing pros and cons of using PKIOverheid Private Services or publicly trusted CAs:

We originally wanted to use the `auth.publicurl` endpoint (meant for public access to auth means services, by mobile devices/browsers) since it's already there and configured, but that means we'll be used publicly trusted CA anchors. Unless we ask parties to configure TLS renegotiation on their reverse proxies to support multiple server certificates on the same server+port, but that's going be really inconventient.
Parties already have a PKIOverheid Private Services HTTP endpoint for the existing OAuth2 flows (everything under `/n2n`), so PKIo Private or publicly trusted CA are probably equally easy to setup on another endpoint.

Leftover considerations:
- Security of our OpenID4VCI implementation: it's not proven to be secure, so PKIOverheid Private Services is the "safe" route
- We want to exchange credentials with other parties than Nuts nodes (e.g. receive VCs from LrZA or KIK-v Authoriteit) who might not (or will not) have a PKIOverheid Private Services certificate, so this route is not future-proof

Options:
- Start with PKIOverheid Private Services, until we think our implementation is safe enough, then switch to publicly trusted certs (without client TLS requirement)
- Spend extra effort to make our implementation safe enough and use publicly trusted certs from the start (no client cert required).

**Comment by woutslakhorst** [comment]
I think OIDC is supposed to be 'open', so no client certificates. We mainly use the PKIOverheid certs for accountability, blocking and as a delaying factor when blocked.

Main security concern would be DoS style attacks for the credential_offer endpoint. An offer isn't signed so it can be spoofed and then if enough are sent, the DB can be overloaded. If this can't be secured then PKIOverheid is still needed.

**Comment by reinkrul** [comment]
> I think OIDC is supposed to be 'open', so no client certificates. We mainly use the PKIOverheid certs for accountability, blocking and as a delaying factor when blocked.
> 
> Main security concern would be DoS style attacks for the credential_offer endpoint. An offer isn't signed so it can be spoofed and then if enough are sent, the DB can be overloaded. If this can't be secured then PKIOverheid is still needed.

We could do client authentication, with client_id (e.g. lookup issuer in Nuts registry, or some other means for other clients)

**Comment by woutslakhorst** [comment]
> We could do client authentication, with client_id (e.g. lookup issuer in Nuts registry, or some other means for other clients)

I do not believe the offer uses access tokens?

**Comment by reinkrul** [comment]
After discussion:
- OpenID4VCI interfaces need to be open to be compliant with external systems/parties (wallets/issuers), so it needs to use a publicly trusted certificate
- Endpoints need to be moved to `/public`
- Credential offerers (issuers) need to be trusted: trust comes from the issuer being registered in the Nuts Registry; in other words, the issuer have registered a OpenID4VCI credential issuer service in its DID document.
- Credential offer endpoint is at risk for DoS attacks, so it needs a signature to make sure it comes from the trusted issuer.
  - We could extend it with a field (e.g. JWT) which authenticates it

**Comment by reinkrul** [comment]
Discussed this today, considerations:

- Every added security measure to the credential offer endpoint is custom
- The mid-term goal is issue VCs from Nuts nodes to Nuts nodes, so we control both sides
- It's easy to make it more open in the future, external parties want to issue VCs to Nuts nodes (since we're still complant).

Decision: all OpenID4VCI endpoints will require the Nuts node certificate (PKIOverheid Private Services). They will be put under the `/n2n` interface.
