### ISSUE TITLE
Validate requested credential definition and format

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#2037]
When a wallet requests a credential using `CredentialRequest`, it sends a credential definition and format. These need to be validated:

- The only supported format is `ldp_vc`, reject requests with other formats
- Verify the requested credential is the one offered (and verify credentialSubject, bound to pre-authorized code).

See https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#name-credential-request and https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#name-credential-offer-3

**Comment by woutslakhorst** [comment]
depends on #2050
