### ISSUE TITLE
Persist credential issuer offers and support retry of delivery

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#2039]
We need to store the OpenID4VCI issuance of credentials.

Things we need to store:
- Initiator (issuer/holder); will always be issuer for now
- Status (offered/requested/retrieved); will always be offered or retrieved for now
- Issuer DID
- Holder DID
- Grants, including parameters (generated pre-authorized code)
- Arbitrary number of nonces
- Arbitrary number of access tokens (or just 1) and expiry
- Created timestamp
- Expiry/NotAfter timestamp
- RetrievedOn timestamp
- Credential definition
- Issued credential (ID) after it has been requested by the wallet

**Comment by reinkrul** [comment]
![erd](https://user-images.githubusercontent.com/1481228/232067072-e0ca3ba5-faa0-4fb7-8642-79d45faf5f18.svg)

**Comment by woutslakhorst** [comment]
where would the relation with the pre-auth code be stored? (short lived)

**Comment by woutslakhorst** [comment]
Make sure to refresh the pre-auth token on retry

**Comment by woutslakhorst** [comment]
persistence and guaranteed delivery is for phase 2

**Comment by reinkrul** [comment]
server-to-server OpenID4VCI will be removed
