### ISSUE TITLE
Revisit OIDC4VCI access token expiry

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#2051]
How long do they need to be valid? Can you keep re-requesting new access tokens using the same pre-authorized code?

**Comment by reinkrul** [comment]
A new nonce needs to be provided by the server in each `CredentialResponse`, such that new `CredentialRequest` use a proof with a fresh nonce.

**Comment by reinkrul** [comment]
Comment from @gerardsn:

> [Questions]

c_nonce here and in TokenResponse do not expire. Storage wise does that mean we always keep the latest value in store for each party we interacted with?
any experience with this in large scale interactions? I'm foreseeing some potential issues where the nonce gets replaced by a new request before the old request is handled, not sure if this makes sense though.

**Comment by reinkrul** [comment]
Pre-auth code can be used just once:

> This code MUST be short lived and single-use.

https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#section-4.1.1

Access tokens expire in 15 minutes.

**Comment by woutslakhorst** [comment]
That's a big impact for the retry mechanism? This also means that pre-auth tokens do not need to be stored? But a state which cred should be issued to whom must be stored?
