### ISSUE TITLE
Add EmployeeIdentity signing means

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#2053]
Starting a session must return a session identifier and set an html template for the session.

**Comment by stevenvegt** [comment]
I would say the it returns a sessionPtr which contains 2 URLs one for embedding and one for opening in a new tab. Opening these URLs render a piece of html with the LOGIN contract text, the claimed user identity and a question if this is correct and 2 buttons to either confirm or deny the claim. The embeddeable url only shows the text and buttons, the other is a more complete page with header and footer etc and instructions to close the tab after completion.

**Comment by woutslakhorst** [comment]
2 issues encountered:

- can't set VerifiablePresentation type
- proofPurpose on VP is always assertionMethod, this should be `authentication`?
