### ISSUE TITLE
OIDCIssuer must have a list of offered credential types

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#2058]
Places of use:

- List in OIDCIssuer metadata (`credentials_supported`)
- Check when credential is requested

**Comment by woutslakhorst** [comment]
credential types you mean

**Comment by woutslakhorst** [comment]
This is config only, used to create metadata. Question: is this config file or DB entry config? Does it change runtime?

Issuing new credential types is probably part of the standard software (AuthCred, OrgCred) or part of a larger project. Config file time (on update) should suffice.

Proposal, add default definition files for AuthCred and OrgCred as assets. Make a DIR configurable for additional where each file becomes an entry in `credentials_supported` of the server metadata.

**Comment by woutslakhorst** [comment]
using `vcr.oidc4vci.definitionsdir` as config param
