### ISSUE TITLE
Network: remove AutoDIDResolver

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#2066]
People are generally not aware that the node might auto-detect a node DID, which then is often the cause of connection issued (authentication failures), since those DIDs are often not set up correctly (e.g. incorrect NutsComm address, or a DID that hasn't been synced at all). At the same time, it's hard to disable the feature: you can only do so by not configuring a node DID and putting it into strict mode (which forces you to configure your node in a safer way, which you might not want in dev environments).

Better to get people more comfortable handling their node DID and have them explicitly configure it in their `nuts.yaml`, so I propose removing the feature.

**Comment by woutslakhorst** [comment]
fine with me
