### ISSUE TITLE
Network: add connect-to-self healthcheck 

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#2087]
This asserts the NutsComm address matches the node's TLS certificate, to see if it's set up correctly.
This also checks that the correct certificate chain is configured.

Should be just opening a (TLS) socket (no HTTP/gRPC involved).

**Comment by woutslakhorst** [comment]
As discussed: if an ingress won't open the port until the service is healthy, it'll never become healthy.

**Comment by reinkrul** [comment]
And is this how it's actually used (failing healthcheck preventing a service from being routed traffic to) in practice?

If so, how does the ingress check it? HTTP response code or the actual response body? Or does it depend?

We could use "UNKNOWN" as sort of warning; node can be used, but with notices?
