### ISSUE TITLE
Access token includes username field

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#2111]
`username` is a standard introspection field defined in: [rfc7662](https://www.rfc-editor.org/rfc/rfc7662)
Currently it's only filled for the `selfsigned` means.
If we fill it from IRMA (with email), dummy (with *dummy*) and UZI (with #UZI) as well, it can be used as default auditing identifier.

**Comment by reinkrul** [comment]
Is this a bug report or a feature request (summary reads like a bug report, description, not sure).
