### ISSUE TITLE
Validate credentialSubject in issued/received VCs

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#2119]
There must always be at least 1 credentialSubject, with an ID. The ID must be a valid DID.

Related to https://github.com/nuts-foundation/nuts-node/issues/2115 (try to avoid issuing invalid VCs as much as possible).

**Comment by woutslakhorst** [comment]
At which points?
- creating
- receiving/validating
- after searching
- using

**Comment by reinkrul** [comment]
It's just another check in the existing validator, which is used in all of these cases you listed.
