### ISSUE TITLE
Deleting a service fails if it is referenced

### ISSUE THREAD

**Issue by stevenvegt** [nuts-foundation/nuts-node#2131]
API call such as`DELETE {{nodeaddress}}/internal/didman/v1/service/did:nuts:FJ2WaKNaf6jKZ9tgJoNCmQKh3xoe9vFEBzj59WSkmSEV%23G4QaQAzVABv6x5RTKNHwSAonJQW2F4hcb4Y71NWdMMiD`

Which is a serviceEndpoint, fails if the service is referenced in a compound service.

**Comment by woutslakhorst** [comment]
What is the expected result for the compound service when the service is deleted? What is the expected result for any 'child' DID that references the service?

eg: fail, ignore or cascade?

**Comment by reinkrul** [comment]
This is not a bug, but intended. But it might be very unpractical when changing the service endpoint.

Maybe a creation should also just update it, if it already exists? Makes API more user-friendly. But we can still retain the sanity check.

On the other hand, if another party wants to annoy you, they can reference a service on your DID document from theirs, which you don't control. Which makes it hard to delete the endpoint.

Maybe we should remove the check altogether and make a creation an update if it already exists.
