### ISSUE TITLE
Docker Hub tags are stale

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#2167]
The generalized and latest tags (e.g. `v5` and `latest`) are pointed to the last release, not the highest released version. Thus, if `v5.3.0` gets released and then bugfix version `v5.2.9`, the latter is pointed to by the `v5` and `latest`. But the should point to the highest released version, meaning `v5.3.0`.

**Comment by woutslakhorst** [comment]
or in other words still broken after switching plugins

**Comment by woutslakhorst** [comment]
use action-get-latest-tag to get latest repo tag, then only enable latest tag if tag == steps.x.output.tag

**Comment by woutslakhorst** [comment]
The github action maintainer is not extremely active, so on failure we might have to fork the repo.
