### ISSUE TITLE
Change default Dockerfile health check from /status to /health

### ISSUE THREAD

**Issue by gerardsn** [nuts-foundation/nuts-node#2193]
This should give a better view of the actual health status of a node, but may break setups where nodes are killed when they health check does not return status 200.

Current `HealthStatus` mapping:

`UP`: 200
`UNKNOWN`: 200
`DOWN`: 503

**Comment by gerardsn** [comment]
Probably need to have som clear definitions on what should be `UNKNOWN` vs `DOWN` to see what may or may not kill a node and go through all existing health statuses to apply this.

**Comment by woutslakhorst** [comment]
If backends are unreachable and/or a config param is invalid, DOWN should be reported.

**Comment by gerardsn** [comment]
To assess the impact of this change I've made a summary of what the `health` endpoint currently checks: 

crypto
- fs/mem: status is always up
- external/vault: status is result of ping

PKI
- loops over all in-mem CRLs and checks if they are still valid / failed to update. For failing CRLs this triggers an update every 10 seconds. This is probably fine from the node perspective, but **is this also acceptable for CRL providers?** (When the system CA store is configured as the tls.truststore this could be a very long list of CRLs. Can we even expect all of these to have a functional CRL distribution endpoint that we can update from hourly? And do we even want to try to fetch all of these CRLs every hour? Not in scope for this issue, but came to mind due to a previous discussion with @reinkrul.)

Network [status if failing]
- validate own cert: (disabled if no cert configured) [DOWN]
- did:nuts auth check: (disabled if no nodeDID configured)
   - assert keys owned (DB/extenal calls) [DOWN]
   - db calls: resolve did doc -> NutsComm (db call) [UNKNOWN]
   - verify NutsComm with cert: [DOWN]
   - selfcheck: ping grpc endpoint found in the NutsComm address (disabled if no nodeDID) [UNKOWN]

---

Missing health checks on recent features:

- Storage: Can/should we ping the SQL DB?

- Discovery: Should we check that all servers are online? (fail with UNKNOWN since it's not this node that is failing)

- Policy: Probably needs a ping for an external policy server.

**Comment by reinkrul** [comment]
I think for `did:web`, the security relies heavily on the server certificate, so revocation checking is i.m.o. an important trait. But maybe not in the form of how it works with the `did:nuts` truststore (maybe only actually used certificates, or OCSP?).

Given Discovery: the servers aren't under the node's control, so it shouldn't report `DOWN` in that case (there's nothing the node's admin can do other than notify the admin of the Discovery Server).

We should take care we don't go into a reboot loop because a dependent system is down (e.g. Policy backend).

**Comment by woutslakhorst** [comment]
The original distinction is:
- /status for if the service is running
- /health to be monitored by external services that will warn/call sys admins.

Using /health for process monitoring will create bootloops when other services are down. Better to stick with /status

**Comment by gerardsn** [comment]
document for Kubernetes:
- /status -> liveness probe
- /health -> readiness probe

leave health check unchanged
