### ISSUE TITLE
admin-demo Requirements

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#220]
Note: this issue is to be moved to the new repository (which is yet to be created).

### Functional requirements

User actions:
- **Authentication**:
  - Login
  - Logout
- **Software vendor**:
  - Register vendor (in: contact information which will be registered in DID, see https://github.com/nuts-foundation/nuts-specification/issues/35)
  - Update vendor's contact information
  - Update vendor's technical endpoints
- **Care organizations**:
  - Register care organization (name, city, emaildomain)
  - Publish care organization on Nuts Network (creates DID + VC)
  - Update care organization's details (triggers VC re-issue)
  - Deactivate care organization on Nuts Network (revoke)
  - Enable Bolt
  - Disable Bolt
- **Verifiable Credentials/Trust**:
  - List trusted VC issuers
  - List untrusted VC issuers
  - Trust VC issuer
  - Untrust VC issuer

System actions:
- Link with Demo EHR for ultimate demo-effect

### Non-functionals
- Very easy to deploy (zero-conf)
- Single Docker container

**Comment by woutslakhorst** [comment]
https://github.com/nuts-foundation/nuts-registry-admin-demo

**Comment by woutslakhorst** [comment]
may be moved to that repo?

**Comment by reinkrul** [comment]
Can't move, will recreate.
