### ISSUE TITLE
Helm Chart: allow using existing secret for redis password

### ISSUE THREAD

**Issue by henk-hofs-pink** [nuts-foundation/nuts-node#2211]
I'd like to set a secret to my k8s cluster for the redis-password.
The bitnami redis helm chart supports an option called auth.existingSecret to get the value from a secret already present, would make sense to do the same for the nuts-chart.

**Comment by reinkrul** [comment]
@henk-hofs-pink we don't have any active contributors for the helm chart, would be fantastic if you could provide this in a pull request/contribution!

**Comment by henk-hofs-pink** [comment]
opened #2214
