### ISSUE TITLE
Sanitize kid lookup

### ISSUE THREAD

**Issue by stevenvegt** [nuts-foundation/nuts-node#226]
Since the kid is part of the filename, It might be possible to read file contents by inputting a kid like "../../../etc/passwd".

**Comment by woutslakhorst** [comment]
luckily its `/internal` so impact is less. Still needs fixing.

Refactor to pub key resolvement via did Document solves this as well

**Comment by woutslakhorst** [comment]
see #227

**Comment by woutslakhorst** [comment]
Fixed by replacing public keystore by vdr keys
