### ISSUE TITLE
Use editors draft of OIDC4VCI

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#2281]
It solves some problems we're encountering. Best to adjust all `offer`, `request` and `metadata` to editors draft spec.

https://openid.bitbucket.io/connect/editors-draft/openid-4-verifiable-credential-issuance-1_0.html

To check for draft V -13
- [x] error codes #2285
- [x] rename `types` -> `type` in  offers #2286
- [x] nesting of credentials in offer and request

**Comment by gerardsn** [comment]
changes since release -11 (published version) https://bitbucket.org/openid/connect/diff/openid-4-verifiable-credential-issuance/openid-4-verifiable-credential-issuance-1_0.md?at=master&diff1=2ccdbc16fada4f8ad39752ee3d34bcc6ec8096ce&diff2=master

**Comment by gerardsn** [comment]
changes are implemented, should we keep this open for the links?

**Comment by woutslakhorst** [comment]
you can also search through closed issues.
