### ISSUE TITLE
Backup/restore documentation is incorrect

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#2324]
- it lists didstore.db as something that needs to be restored but also a reprocess of dids is mentioned.
- the did reprocess is also the last in the order, it should be the first.

At some point we decided on a basic set of things to restore, just because it was easier to just tell people to make a backup of the entire data dir. This was also reflected with the restore (1:1). Seems this is incorrect/weird now.

What do we want? Only restoring 1 or 2 db files when making a backup for 5 seems weird (although functionally correct). Restoring all from file is uniform but without a reprocess could be broken (because different db files get a backup at a different time)

**Comment by gerardsn** [comment]
I added the reprocess for the VDR to the documentation around v5.1 when there were some issues that seemed to fixed by a reprocess. Since then we have identified and fixed the issue, so the VDR reprocess can be removed to bring it back to its previous state.
I think this is also related to #2149

**Comment by gerardsn** [comment]
Considering that not all backups are created at the same time I think it's best to restore all data from the minimal amount of sources, so reprocess dag + issued VCs? How does this change when we move to SQL DB?

**Comment by woutslakhorst** [comment]
> How does this change when we move to SQL DB?

single db

**Comment by reinkrul** [comment]
> Considering that not all backups are created at the same time I think it's best to restore all data from the minimal amount of sources, so reprocess dag + issued VCs? How does this change when we move to SQL DB?

Restore procedure for SQL would be: 1. restore your SQL database backup. 2. restart node
