### ISSUE TITLE
tlsIdentifierResolver handles ports for candidateURLs incorrectly

### ISSUE THREAD

**Issue by gerardsn** [nuts-foundation/nuts-node#2350]
`tlsIdentifierResolver.resolveFromCertificate()` contains the following lines:
```
if tlsIdentifierResolverPort == 443 {
	// Not really required, but makes prettier URLs
	candidateURL = fmt.Sprintf("https://%s", host)
} else {
	candidateURL = fmt.Sprintf("https://%s:%d", host, tlsIdentifierResolverPort)
}
```
`var tlsIdentifierResolverPort = 443` is a package variable that is never changed...?

**Comment by reinkrul** [comment]
It's adjustable for testing purposes, since we allocate a random open port for the HTTP server during unit test. On live systems we only test on 443.
