### ISSUE TITLE
VDR: DID resolution should follow the spec

### ISSUE THREAD

**Issue by stevenvegt** [nuts-foundation/nuts-node#2354]
When resolving a DID document, the result should be in the form defined by https://w3c-ccg.github.io/did-resolution/.

Currently the resolution result looks like this:
GET http://localhost:1323/internal/vdr/v1/did/{{did}}

```
{
  "document": {...},
  "documentMetadata": {
    "created": "2023-07-05T08:45:23Z",
    "hash": "72b43e0c6cea3cb905a8d8b984ca1d67d6196535cd428c9e71c58c2810964fac",
    "txs": [
      "c11ccf5ba3fd66777e0f21e799ec65601d52c63cb524cd3cbc03cb1a8b2445a5"
    ],
    "deactivated": false
  }
}
```

And according to the spec it should look more like this:

```
{
	"@context": "https://w3id.org/did-resolution/v1",
	"didDocument": {...},
	"didResolutionMetadata": {
		"contentType": "application/did+ld+json",
		"retrieved": "2024-06-01T19:73:24Z",
	},
	"didDocumentMetadata": {
		"created": "2019-03-23T06:35:22Z",
		"updated": "2023-08-10T13:40:06Z",
                "deactivated":false,
    		"hash": "72b43e0c6cea3cb905a8d8b984ca1d67d6196535cd428c9e71c58c2810964fac",
          	"txs": [
                    "c11ccf5ba3fd66777e0f21e799ec65601d52c63cb524cd3cbc03cb1a8b2445a5"
                ],
	}
}
```

**Comment by reinkrul** [comment]
What, the metadata?

**Comment by woutslakhorst** [comment]
The spec is not compatible with did:web. Also how serieus is it? It hasn't been updated since January, has version 0.2. Last issue comment is a year old.

**Comment by stevenvegt** [comment]
> The spec is not compatible with did:web
Can you elaborate? This is not the format the webserver serving the did:web document should return, but the resolver must return. So user->resolver.resolve(did:web:example.com)->http.GET(example.com/.well_known/did) etc. The resolver returns the DID document wrapped in this resolver format. You can even wrap a `did:key` document in this resolver result.

**Comment by woutslakhorst** [comment]
I thought it replaced the actual DID Document result, but it could define the return of our own API. This would be a breaking change though.

**Comment by reinkrul** [comment]
It would be VDR v2 API or we return it in the specified format when the requester clearly asks for resolution according to the mentioned draft spec (e.g. `Accept` header with resolution options)

**Comment by reinkrul** [comment]
I'd say we add it when someone requires it.
