### ISSUE TITLE
Create VC Wallet

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#2389]
Under `vcr/holder`, the `wallet.go` can be added.

The wallet contains a stoabs KVStore with a shelf for each DID and values (vc.ID => vc).
The wallet must be filled by a migration where all non-AuthCreds that are owned by a node are added to the right wallet. This could be done from the VCR?
Then any VC (owned, non-AuthCred) received through the network (ambassador) or via OpenID4VCI must be added to the wallet.

The wallet should get an All(did) method. Maybe we can expose it through an API as well, but that would be a bonus?

**Comment by reinkrul** [comment]
- Diagnostic showing the number of VCs in the wallet
- Re-add to wallet when DAG is reprocessed (probably works out of the box through ambassador)
