### ISSUE TITLE
Add configuration option for scope to PresentationDefinition mapping

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#2390]
For example when an eOverdracht client gets an AuthorizationRequest using the `eOverdrachtV1` scope. The authorization server must translate the `eOverdrachtV1` scope to the correct PresentationDefinition.

It would probably be best to manage this through an API?

**Comment by reinkrul** [comment]
Having an API means storage, I'd say configuration for now?

**Comment by woutslakhorst** [comment]
> Having an API means storage, I'd say configuration for now?

given the desired storage refactor, configuration without an API would suffice (for now)

**Comment by woutslakhorst** [comment]
This is a temporary solution to provide a mapping that enables us to use AuthCreds. In the final design the scope is passed to backends that translate the scope to a PD.
