### ISSUE TITLE
Extend VDR diagnostics with own conflicting DID Documents

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#241]
Now it only shows the global # of conflicted docs. This should be extended with the DIDs of your own conflicted DID documents.

**Comment by reinkrul** [comment]
We can check for each item in the list whether the local node can control it (is controller and controller has private key, there's an existing function for that check). Add it to the VDR diagnostics.

Check that how to resolve it, is documented.
