### ISSUE TITLE
handle access token request with all correct VP validations

### ISSUE THREAD

**Issue by gerardsn** [nuts-foundation/nuts-node#2495]
Validation is split in 3 steps:
- Validate VP + VCs in it.
- Validate that the Presentation Submission fulfills requirements for requested scope. Should this also check that the VP does not contain more VCs than required by the Presentation Definition for the given scope?
- Confirm that Presentation Submission truthfully describes the VP

Expensive checks should probably go last (so probably execute in opposite order).

**Comment by reinkrul** [comment]
> - Validate that the Presentation Submission fulfills requirements for requested scope. Should this also check that the VP does not contain more VCs than required by the Presentation Definition for the given scope?
- Confirm that Presentation Submission truthfully describes the VP

RFC021 specifies that the introspection endpoint should return the VCs (not the VP), so we could take the credentials (to be included in the access token) from the submission. Then we only actually use the requested credentials.
