### ISSUE TITLE
Support did:key

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#2522]
Sphereon Wallet issues a credential with the holder's name when activating it, the issuer is a `did:key` DID. Should be support it?

Note that the online issuers in the SPhereon demo environment seem to use `did:jwk` (at least the "Sphereon Guest" credential).

**Comment by woutslakhorst** [comment]
`did:key` is dead, long live `did:jwk`

See: https://dutchblockchaincoalition.org/en/bouwstenen-2/diip-2 and https://identity.foundation/jwt-vc-issuance-profile/

**Comment by reinkrul** [comment]
Already merged
