### ISSUE TITLE
Moving away from shared network state

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#2548]
For a more robust system, we want to move away from shared network state. The network is currently used for the features below, for which we all have a future replacement
- Public transactions:
  - Publishing DIDs: will be replaced by `did:web`
  - Public VCs acting as "registry": will be replaced by "use case list" (requires https://github.com/nuts-foundation/nuts-node/issues/2549)
  - VC revocations: will be replaced by revocation status list, hosted by over HTTP (requires https://github.com/nuts-foundation/nuts-node/issues/2550)
- Private VCs for NutsAuthorizationCredentials: NutsAuthorizationCredentials will be replaced by a Presentation Exchange-driven protocol (requires https://github.com/nuts-foundation/nuts-node/issues/2551)

After these features have been replaced we can drop the gRPC network and nodes don't need to maintain an active peer-to-peer network and state.

**Comment by woutslakhorst** [comment]
More specific: removing shared state makes it easier to maintain and service a node. We noticed that ease of deployment is a much more important non-functional than expected.

**Comment by woutslakhorst** [comment]
all mentioned points are taken care of in v6 release.
