### ISSUE TITLE
Use Case List ("Registry")

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#2549]
The "Nuts Registry" is currently implemented by publishing VCs to the network. This epic proposes a new feature to better align this with having multiple "registries" or use case governing bodies: a "use case list" (better name to be decided on) that keeps track of care organizations (for that particular use case) in the form of Verifiable Presentations.

The list will be an actual JSON list with Verifiable Presentations (instead of the current verifiable credentials on the network), which can be downloaded from a distributed URL. The list can be served and maintained by a Nuts node, or any other software implementing the specification.

Organizations can post their Verifiable Presentation to the system maintaining the list. As long as validation of the VP (signatures, trust status) passes, it will be added to the list. Entries will be automatically pruned after X time (e.g. 7 days), so parties will have to regularly re-submit their VP to maintain their entry.

Loading the list involves simply downloading the list, and checking validity of the VPs.

For each use case, a different use case list source can be configured.

**Comment by woutslakhorst** [comment]
@reinkrul issue is done I think?

**Comment by reinkrul** [comment]
Probably some documentation work, but that should be done with the pending doc touchup.
