### ISSUE TITLE
Add creationOptions to DID creation

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#255]
A creationOptions object defines the following:

```
{
  "controllers": [], // list of controller DIDs
  "isController": true/false, // is the newly generated DID in control of its own document
  "hasCapablilityInvocation": true/false, // is the generated key used for capabilitInvocations
  "hasAssertionMethod": true/false, // key used for assertion?
  "hasCapablilityDelegation": true/false, // key used for capablilityDelegation?
  "hasAuthentication": true/false, // key used for authentication?
  "hasKeyAgreement": true/false // key used for keyAgreement?
}
```
- `isController == false` and `hasCapablilityInvocation == true` is a valid state since it will allow a DID Dubject to control DID Documents of its children.
- if `isController == true`, then the generated DID will be added to the list of controllers.
- `isController == true` and `hasCapabilityInvocation == false` is not allowed.
- If `isController == false` and `hasCapabilityInvocation == false` then the private key must not be persisted and wiped after the transaction has been published. The `controller` MUST then have at least one entry.

**Comment by woutslakhorst** [comment]
The PR implementing this should also add the `getting started manual` on DID creation.

**Comment by reinkrul** [comment]
Is it optional? If so, what are the (sensible) defaults?

**Comment by reinkrul** [comment]
(accidentally closed issue...)
