### ISSUE TITLE
Support data exchanges without NutsAuthorizationCredentials

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#2551]
Allowed/disallowed based on consent stored in local or external system, using OAuth2 service-to-service flow or OpenID4VP with Presentation Exchanges.

@woutslakhorst can you further specify this epic?

**Comment by woutslakhorst** [comment]
There's no changes required for the code. Maybe this would be an issue for nuts-specification? Maybe it could only be an addition to RFC021#security considerations?

**Comment by woutslakhorst** [comment]
Part of solution architecture. Should be on wiki.
