### ISSUE TITLE
ValidDuration param ignored for BehandelaarLogin means

### ISSUE THREAD

**Issue by stevenvegt** [nuts-foundation/nuts-node#2552]
As reported on the Nuts slack: https://nuts-foundation.slack.com/archives/C02GJMAE7TL/p1697719167616289
When creating a EmployeeIDCredential, the `validDuration` param in the drawup does not affect the `expirationDate` in the created VC.

This is logical, since the `validDuration` during drawup only affects the dateTimes in the contract text. However, the created `NutsEmployeeCredential` has a validity possible much longer than the provided duration. The contract text is part of the presentation challenge, but as with the VC, the expirationTime does not reflect the contract text and is set to a fixed value of  24h. This probably should be determined from the contract text or become an param in the `POST /internal/auth/v1/signature/session` request.

![image](https://github.com/nuts-foundation/nuts-node/assets/3896736/afbbaf4a-d75c-4dc9-b5b8-291c48cf7e66)

![image](https://github.com/nuts-foundation/nuts-node/assets/3896736/0408bdf0-6c04-41ea-a0d2-3e0ac510e9c0)

**Comment by woutslakhorst** [comment]
won't fix
