### ISSUE TITLE
Support path_nested in Presentation Exchanges

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#2553]
We should support `path_nested` when processing presentation submissions (https://identity.foundation/presentation-exchange/#presentation-submission)

**Comment by gerardsn** [comment]
[OpenID4VC](https://openid.net/specs/openid-4-verifiable-presentations-1_0.html#name-nested-verifiable-presentat) restricts this feature to 1 level of nesting.

`PresentationDefinition.Match` should also apply the nesting in the created `PresentationSubmission`
