### ISSUE TITLE
Validate PEX definitions and submissions against JSON schema

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#2554]
We now come across bugs (in unit tests, probably later runtime as well) because the PDs and submissions aren't validated properly. Since the model is quite elaborate, writing 100% coverage for all things required/specified in the specification is a lot of work. Easier/safer is to use the JSON schemas provided in the spec (https://identity.foundation/presentation-exchange/#json-schemas), and use a JSON schema processor/validator to validate definitions and submissions.

(A) list of Go implementations: https://json-schema.org/implementations

**Comment by woutslakhorst** [comment]
The definition and submission structs are generated from JSON schema. Isn't that enough?

**Comment by reinkrul** [comment]
That doesn't check that required properties are actually provided (e.g. id), or that the values (of strings/enums) are valid.

**Comment by woutslakhorst** [comment]
Could it cause any forwards compatibility problems?

**Comment by gerardsn** [comment]
Future additions might fail schema validation, but they would have failed later anyway since the node doesn't know how to proces the additions?
