### ISSUE TITLE
Disable dark-mode for EmployeeID screen

### ISSUE THREAD

**Issue by stevenvegt** [nuts-foundation/nuts-node#2665]
The CSS of the EmployeeID screen detects the OS dark mode settings, which makes the whole form a bit funky. We probably should disable this feature.

Relevant code: https://github.com/nuts-foundation/nuts-node/tree/master/auth/services/selfsigned

Example of the form in dark-mode, embedded in an iframe of the ECD.
![image](https://github.com/nuts-foundation/nuts-node/assets/3896736/12aac058-3552-49dc-b5ad-ad45af5acc83)

**Comment by reinkrul** [comment]
Should we? What do vendors usually do with dark mode?

**Comment by woutslakhorst** [comment]
`background: white;` is usually somewhere in the css of every healthcare webapp

**Comment by stevenvegt** [comment]
We can also make it more ~complicated~ advanced and add config flag to the node or add query params to the url?

**Comment by reinkrul** [comment]
I'd say set white by default, we can always allow custom CSS stylesheet to be included if someone requests it.
