### ISSUE TITLE
Network: validate transactions on startup (loaded from disk)

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#267]
In case of e.g. corrupt storage or a new version of the nuts node with a bug due to changed business rules, which don't comply with the transactions already in storage. When encountering invalid transaction on startup, it should refuse to start.

Should validate:

- TX validity (semantic, cryptographic)
- DAG integrity
  - All prevs are present

**Comment by woutslakhorst** [comment]
If all prevs must be processed first, missing prevs would not be possible unless the DB is corrupt.
