### ISSUE TITLE
Network: disallow DAG transactions with missing previous'

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#268]
It's currently allowed to have transactions on the DAG which's previous transactions are missing (for historic reasons). This complicates things for head calculation and DAG walking (transaction looks to be present but is never reached by the DAG walker) and should be disallowed.

**Comment by woutslakhorst** [comment]
And also process `prevs` first if not processed already. Do we need a separate issue for this and the atomic processing?
