### ISSUE TITLE
Split request-access-token API

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#2682]
it currently handles s2s and user based flows. The user based flow currently returns a 302 which should be a 200 JSON like:
```
{
"redirectURL":"https://example.com"
}
```

Therefore the API needs to be split into 2

**Comment by reinkrul** [comment]
Both are invoked by the EHR system, so neither should return a HTTP 302?

**Comment by woutslakhorst** [comment]
completed
