### ISSUE TITLE
Allow disabling Nuts network

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#2732]
If someone wants to run a Nuts node without the functionality of the gRPC network (e.g. a collective only using did:web, e2e tests), you should be able to disable the Nuts network. This means no gRPC server will be started, no outbound connections will be made, no stores create/migrated.

**Comment by woutslakhorst** [comment]
- don't expose a gRPC endpoint
- no bootstrap nodes
- set auto-discovery to false
done
