### ISSUE TITLE
Migrate credential wallet to SQL storage

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#2798]
Starting v6 we support SQL storage. One of the stores we still need to migrate is the credential wallet (`VCR/Holder/wallet.go`).

On the `master` branch there is functionality to migrate credentials from VCR store to the current BBolt wallet, but since this feature isn't released yet we can simply change the store implementation to SQL.

**Comment by gerardsn** [comment]
Since the wallets only apply to did:web, and no credentials have been issued for this yet, we can also remove the migration. So just change store implementation

**Comment by reinkrul** [comment]
Requires https://github.com/nuts-foundation/nuts-node/issues/2799
