### ISSUE TITLE
VCR: no automatic context adding when issuing VC

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#2852]
This is not backwards compatible, but ok for V6. If we want to support the v2 data model and v1.1 data model it's easier to require the context to be added by the user of the API. (At least when issuing JSON-LD format)

**Comment by gerardsn** [comment]
- our OAPI specs currently contains `IssueVCRequest` schema that defines properties `@context` and `type` as a string. At least `@context` needs to change to an array (or oneOf with array and string) to fix the issue, but ideally both. 

- The vc v2 datamodel has replaced `issuanceDate/expirationDate` with `validFrom/validUntil`, and has made `validFrom` optional. 

- The linked issue also raises a concern about semantics of a credential that does not contain the default (v1 or v2) context.

Considering the above, I think it might be wise to only relax the constraints on the current API for now by allowing users to provide _all_ contexts and types the final VC will contain. The v1 context and `VerifiableCredential` type still need to be added if missing, but by allowing them to be provided there is less confusion/magic. Remaining question is what to do with contexts that are not used? (example: kik-v credential contains an unused nuts.nl/credentials/v1 context)

**Comment by woutslakhorst** [comment]
Can we get away (for this version) with a `oneOf` with string and array for those types?
