### ISSUE TITLE
Reconsider TLS options for network

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#2864]
We now have `network.enabletls` for disabling TLS on the gRPC network layer, which can only be set when strict mode is disabled. The option is used for local/workshop settings in which TLS is inconvenient.

To make the minimal setup easier for networkless deployments (`did:web` only), you don't want to configure anything `network.` related. So:

- Remove `network.enabletls` configuration flag
- If TLS properties are configured, enable TLS.
- If no TLS properties are configured, disable TLS.
- Require TLS to be configured in strict mode (TLS offloading still works; needs to be explicitly configured)

If we decide to keep the `network.enabletls` option, we should remove the following log warning:

```
TLS is disabled, which is only meant for demo/workshop purposes!
```

**Comment by woutslakhorst** [comment]
As far as I can see, enabling/disabling based on existence of TLS configuration is fine.
