### ISSUE TITLE
Introduce dev Docker image

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#2866]
This Docker image is intended for developers to quickly spin up a node for local/dev environments.

- Builds off the latest `master` image
- Disables strict mode
- Stores private keys on disk
- Stores SQL data in SQLite
- Disables Nuts network
- Disables IRMA
- Embeds `ngrok` to super-easy `did:web` usage (which requires a TLS certificate)

**Comment by woutslakhorst** [comment]
since ngrok is going commercial all the way, maybe checkout https://github.com/localtunnel/localtunnel?

**Comment by reinkrul** [comment]
> since ngrok is going commercial all the way, maybe checkout https://github.com/localtunnel/localtunnel?

Worth a try.

**Comment by gerardsn** [comment]
now available
