### ISSUE TITLE
StatusList2021: e2e test does not fail if status list can't be resolved

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#2922]
The e2e-test checks on nodeA that a credential is revoked, which can only be confirmed if the StatusList2021Credential can be retrieved from the issuer => nodeB.

By design the revocation check should softfail (making the e2e-test fail), meaning that it does not consider the credential revoked if the StatusList2021Credential cannot be retrieved.

(rewritten by gerardsn)

**Comment by woutslakhorst** [comment]
This is not a problem if there's a e2e test that checks for a fail with a revoked VC

**Comment by gerardsn** [comment]
that is how the test is designed, but apparently it wasn't working properly
general test setup:
nodeB issues VC
nodeB checks if VC valid -> true
nodeB revokes VC
nodeB checks if VC valid -> false
nodeA checks if VC valid -> false ==> if fetching the StatusList2021Credential from nodeB fails, this should return true.

**Comment by woutslakhorst** [comment]
So title is incorrect? It should read revoked VC e2e test is broken?

description: test doesn't fail if list can't be retrieved.

**Comment by gerardsn** [comment]
either that, or soft-fail is not working as designed
