### ISSUE TITLE
Loading a VC on the same wallet that issued it returns an error

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#2925]
I got the following error when loading a VC that I just created on the same node:

```
{
    "detail": "credential with this ID already exists with different contents: did:web:sqqc2c8c-8080.euw.devtunnels.ms:iam:groot#70a208fb-fae9-43c4-aa99-5591e57445bf",
    "status": 500,
    "title": "LoadVC failed"
}
```

Content is identical

**Comment by woutslakhorst** [comment]
comparison is done using string equals, whitespace and/or normalising would cause/fix it.

**Comment by reinkrul** [comment]
Maybe unmarshal to `map[string]interface{}` and then `DeepEqual`?

I've not run into this issue yet..

**Comment by reinkrul** [comment]
Probably a JSON-LD VC? I'd not expect this with JWTs.
