### ISSUE TITLE
discovery.server.definition_ids can't be configured through environment

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#2938]
`NUTS_DISCOVERY_SERVER_DEFINITION_IDS` is translated to `discovery.server.definition.ids` (instead of `_ids`).

Solution: rename `definition_ids` to `definitions`.

**Comment by woutslakhorst** [comment]
ahh yes, our policy is that all configuration options are lowecaseconcatenatedwithoutunderscorehypendsordots
