### ISSUE TITLE
Discovery configuration not very developer friendly

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#2946]
Changes to a service definition for the discovery service takes a long time to take effect.

It seems a node only look at the next moment to refresh. It doesn't do anything when the definition changes. When a presentation definition changes, it would be nice to immediately send a new vp.

ps: there's also an overlap between the id of a definition and the endpoint...
pps: searching is done via example query param: `credentialSubject.organization.name` but the result is accessible via `searchResult.Fields["organization_name"]`

**Comment by reinkrul** [comment]
Also: document Discovery Definition format

**Comment by reinkrul** [comment]
Return the fields that were specified in the query.

**Comment by woutslakhorst** [comment]
@reinkrul didn't we already implement this?

**Comment by woutslakhorst** [comment]
> Changes to a service definition for the discovery service takes a long time to take effect.
> It seems a node only look at the next moment to refresh. It doesn't do anything when the definition changes. When a presentation definition changes, it would be nice to immediately send a new vp.

For now, we keep the setup simple and make no changes.

**Comment by woutslakhorst** [comment]
> ps: there's also an overlap between the id of a definition and the endpoint...
pps: searching is done via example query param: credentialSubject.organization.name but the result is accessible via searchResult.Fields["organization_name"]

Creating a more elaborate and flexible search requires clustered JSON search using SQL as storage. This would probably require publishing changes and indexing VPs in memory. Very nice to have for a future version.
