### ISSUE TITLE
Discovery: describe how to migrate endpoint and hoster

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#2955]
We need to check how to perform the following operations:

- Discovery Service is moved to another endpoint within the same organization (data and tag stay the same)
- Discovery Service is moved to another endpoint in another organization (service ID stays the same, data is emptied, tag changes)

**Comment by gerardsn** [comment]
IMO should be checked before v6 since it may result in breaking changes to the discovery service. If it is too hard to change the server we are introducing a single point of failure.

**Comment by reinkrul** [comment]
Another approach to explore is to use CRDT to manage the state which could maybe reduce complexity. Needs to be explored, rewrite RFC.

**Comment by woutslakhorst** [comment]
Other proposal:
- remove tag, only use LC
- regard changing servers as master/master failover which could lead to loss of data if done uncontrolled. This will only last for X hours
- clients forward GET/POST to server
