### ISSUE TITLE
SQL storage should have no default in strictmode

### ISSUE THREAD

**Issue by gerardsn** [nuts-foundation/nuts-node#2964]
storage configuration is not an afterthought. if this is not set in production setting the node should fail to start

**Comment by woutslakhorst** [comment]
Given the remark on the PR: is `strictmode` to prevent unsafe or also stupid configuration?

**Comment by gerardsn** [comment]
strictmode is to prevent unsafe, not stupid configurations

However, 
- we discourage using SQLite in strictmode, so it would be weird to provide the user with a SQLite db if none is configured
- If the sql config is missing after a restart the node is going to use a SQLite from there on (#2971 means its configured as an env variable which I think is slightly easier to fail)
- SQLite can still be configured explicitly

**Comment by woutslakhorst** [comment]
> we discourage using SQLite in strictmode

but it's not unsafe, right?
