### ISSUE TITLE
StatusList2021: check existing APIs to match revocation logic

### ISSUE THREAD

**Issue by gerardsn** [nuts-foundation/nuts-node#2970]

**Comment by gerardsn** [comment]
Revocation is handled correctly. Status is checked when validating VCs and VPs. 

The `v2/search` (or `v2/issuer/vc/search`) API has a `SearchVCResult.revocation` parameter that could contains a Revocation credential if one exists. This probably needs a mechanism to signal a StatusList2021 revocation, or more general,  the resolved status of each `credentialStatus` in the VC.

**Comment by woutslakhorst** [comment]
"Fix VC search API so revocation field can also handle StatusList2021 style revocations"

**Comment by woutslakhorst** [comment]
Issuer requires a method to check if a VC is already revoked.

**Comment by woutslakhorst** [comment]
For StatusList2021, keep `revocation` field in search result empty. Use verifier api to check credential status (revoked or not). Options will need to be ignored for 'did:web', options argument needs to be deprecated.
