### ISSUE TITLE
Docker: stop publishing "latest" image tag

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#2975]
We publish a `latest` Docker tag that points to the latest release (e.g. v5.4.5). In my opinion, we should stop publishing `latest` and retract the existing `latest` tag from Docker hub.

- People should not use the "latest release" because it's safe (since it's not the latest `master` tag): a major version can break deployments, so it's unsafe to use in production.
- When talking about Nuts network, "stable" is a network name. In ReadTheDocs, "stable" refers to the documentation of the latest released version. These are different concepts with the same name.
- When talking about Docker image tags, "latest" means the most recent release, but in ReadTheDocs "latest" is the latest build from master. More confusion.
- "latest" docker tag sometimes goes awry, when builds race to publish their images; it's conceived as the "highest" released version, but sometimes it's the latest published version.

Instead, people should find the newest major release and use that one (that's what I always do when deploying new Docker containers), or pinpoint a minor or patch version, depending on company policy. Minor versions don't break functionality, so automatic upgrade should be safe there.

We can probably keep `master`.

**Comment by reinkrul** [comment]
Decided against it

**Comment by woutslakhorst** [comment]
latest tag is used in the getting started for devs
