### ISSUE TITLE
Add diagnostics endpoint(s) to Policy spec and add this to the /health endpoint

### ISSUE THREAD

**Issue by gerardsn** [nuts-foundation/nuts-node#2986]
in the case of an external policy router na admin should be able to detect issues. Might as well standardize (some) APIs to allow the node to detect that the dependency is down

**Comment by woutslakhorst** [comment]
You mean: add diagnostics return to policy module? liveness (and readiness) probe terms are for k8s

**Comment by reinkrul** [comment]
External policy router feature has been removed.
