### ISSUE TITLE
Docs: make really clear node must be mounted on (sub)domain

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#2997]
Otherwise, `did:web` DIDs are going to have deeper subpaths than `/iam`, which causes OpenAPI endpoints (in particular `/.well-known`) not to match. Maybe enforce through validating that `url` does not contain a path.

Or, we should reconsider the limitation to `/iam`?

**Comment by woutslakhorst** [comment]
Don't know if I understand. But this software can limit DID creation to root DIDs and `/iam` only?

**Comment by reinkrul** [comment]
We now limit DIDs to domain and `/iam/<tenant>`
