### ISSUE TITLE
Error "invalid_request - no credentials available" needs more pointers for fixing

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#3007]
When the Nuts node wallet can't match a Presentation Definition during an OpenID4VP flow, the following error occurs:

```
invalid_request - no credentials available
```

This is returned to the verifier and ultimately shown to the user. I forecast this is one of the most often seen errors, but probably does not give enough info to developers to fix this.

Users might also see this error, so we should either use error URIs (so developers can map the error for their users), or make it more user-friendly.

**Comment by woutslakhorst** [comment]
> Users might also see this error, so we should either use error URIs (so developers can map the error for their users), or make it more user-friendly.

Error is sent to the callback, it should not display it... It either comes from the organization wallet, in which case the user can't do anything about it and the organization misconfigured their wallet/setup. If a user wallet is sent a PD, it will probably not send this error back but render something where it shows the missing credentials.

**Comment by woutslakhorst** [comment]
We could add an API that checks if credentials are available in a wallet for a given use case (scope to PD mapping). Then the client can show more information on missing credentials. Credential types should also have some sort of metadata, so a nice graphical interface can be shown. This is something wallets currently do, but is missing in specs.
