### ISSUE TITLE
OpenID4VP: rename "user" wallet in API layer and PEX mapping to "personal"

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#3029]
Reasoning: "user" is a technical term for the entity who's logged in to the Nuts node. The OpenID4VP can also be fulfilled by a mobile wallet on the user's smartphone. Also: the other option is "organization", of which "user" isn't a good complementary.

Better would be to change "user" to "person"/"personal".

@woutslakhorst agree?

**Comment by gerardsn** [comment]
`person` is also a better fit in case a patient needs to present something

**Comment by reinkrul** [comment]
"User" is probably more the go-to term in security land
