### ISSUE TITLE
VCR: Better describe did:nuts/did:web specifics in IssueVC API

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#3043]
The current description doesn't really help much:

```
Issues a new Verifiable Credential for provided type in the context.

error returns:

400 - One or more of the given parameters are invalid
412 - A private transaction is issued for a subject that does not have a NutsComm address
500 - An error occurred while processing the request
```

Needs info on what fields are required and forbidden for did:nuts/did:web, and maybe an example for each of them.

**Comment by gerardsn** [comment]
[Open API](https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/) can differentiate on a `oneOf` based on a discriminator. Our codegenerator seems to support this.

By adding a discriminator on the DID method we can define a different schema for each DID method.

**Comment by woutslakhorst** [comment]
> [Open API](https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/) can differentiate on a `oneOf` based on a discriminator. Our codegenerator seems to support this.
> 
> By adding a discriminator on the DID method we can define a different schema for each DID method. I'd prefer this over adding more text.

Code generator tend to do different things for different languages. Keeping it simple might be better. Also no longer an issue for v7
