### ISSUE TITLE
Add wallet hint in authorize request

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#3053]
Both the OAuth2 authorize as the OpenID4VP authorize use the same endpoint. When implementing request_uri's this is not possible due to the http method mismatch: GET for OAuth2 and POST for OpenID4VP. We can no longer make a distinction based on `response_code`.

Therefore the wallet authorize endpoint needs to live somewhere else and we need to tell the authorization server where it is. For now we'll pass `client_metadata.authorization_endpoint` along with the first request for authorization.

The desired path is /openid4vp/{did}/authorize.

Other openid4vp endpoints like `presentation_definition` and `response` may go under the `openid4vp` root path as well.

Note: there's no link between the endpoint passed and the client_id. Any presented credentials should have a relation to the client_id through authorization policies.

**Comment by woutslakhorst** [comment]
The newest OpenID4VP editors draft adds `request_uri_method` prevents the current problem.

**Comment by gerardsn** [comment]
linking to #2712 for context
