### ISSUE TITLE
Remove references to http.default in documentation

### ISSUE THREAD

**Issue by rolandgroen** [nuts-foundation/nuts-node#3059]
De http.default config mapping bestaat niet meer.
In the files README.rst en docs/pages/deployment/configuration.rst komt nog de tekst voor:

> As a general safety precaution ``auth.contractvalidators`` ignores the ``dummy`` option if configured,
requesting an access token from another node on ``/n2n/auth/v1/accesstoken`` does not return any error details,
``auth.accesstokenlifespan`` is always 60 seconds, ``http.default.cors.origin`` does not allow a wildcard (``*``),
json-ld context can only be downloaded from trusted domains configured in ``jsonld.contexts.remoteallowlist``,
and the ``internalratelimiter`` is always on.

_Originally posted by @rolandgroen in https://github.com/nuts-foundation/nuts-node/pull/3042#discussion_r1570423518_

**Comment by woutslakhorst** [comment]
note: fix is to remove cors related comment.
