### ISSUE TITLE
IAM: HTTP client has no time-out by default

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#3088]
The OpenID4VP, OpenID4VCI and OAuth2 client calls use `auth.timeout`, which has no default (`0`) meaning no time-out. This is a security risk, as the caller can control which endpoint will be called (e.g. by providing `presentation_definition_uri`. When an attacker initiates many calls that request from sources slow-responding, they can attempt to (D)DoS.

The least we should do is make sure the HTTP client has a reasonably short time-out (especially for calls that are expected to be cheap on the server side)

**Comment by woutslakhorst** [comment]
from `auth.go`:

```
if auth.config.HTTPTimeout >= 0 {
		auth.httpClientTimeout = time.Duration(auth.config.HTTPTimeout) * time.Second
	} else {
		// auth.http.config got deprecated in favor of httpclient.timeout
		auth.httpClientTimeout = config.HTTPClient.Timeout
	}
```

It uses the generic httpclient timeout when 0

**Comment by reinkrul** [comment]
Default is 30 secs
