### ISSUE TITLE
IAM: simple UserAccessToken flow is slow

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#3089]
While implementing a simple User Access Token flow, I noticed it's quite slow. Although this might be due to devtunnel being used?

Setup:
- devtunnel
- Local workstation
- 1 Nuts node
- Policy definition only defines "organization" PD, with no input descriptors (so no VCs are presented)

<img width="1677" alt="Screenshot 2024-05-05 at 07 03 51" src="https://github.com/nuts-foundation/nuts-node/assets/1481228/b390968d-39df-40e7-ac33-a0366455300a">

My hypothesis is that the many HTTP calls (retrieving DIDs, metadata, etc) that aren't cached in combination with devtunnel makes it "slow" (quoted since we don't have defined how fast it must be).

**Comment by woutslakhorst** [comment]
How much time does the e2e test take? That also does a complete flow.

**Comment by gerardsn** [comment]
```
ok      github.com/nuts-foundation/nuts-node/e2e-tests/browser/openid4vp_employeecredential     0.712s
```

**Comment by reinkrul** [comment]
Will re-open if it is still slow without devtunnel (like in Demo EHR setup)
