### ISSUE TITLE
Browser is not redirected back to client when scope is unknown

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#3104]
![Screenshot 2024-05-10 at 13 42 33](https://github.com/nuts-foundation/nuts-node/assets/1481228/9cacf558-2f23-444a-9fce-972be00de9bd)

Why no redirection back?

**Comment by woutslakhorst** [comment]
because the error is not wrapped with the redirect_url:
```
presentationDefinitions, err := r.presentationDefinitionForScope(ctx, verifier, params.get(oauth.ScopeParam))
	if err != nil {
		return nil, err
	}
```
