### ISSUE TITLE
VDR: Resolve controllers using transaction's signing time

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#311]
`ResolveControllers` doesn't take the signing time of the transaction containing the document's controller being resolved into consideration.

When `ResolveControllers` should optionally take resolver input metadata so VDR's ambassador can resolve controllers in relation to the TXs signing time.

**Comment by reinkrul** [comment]
@woutslakhorst agree?

**Comment by woutslakhorst** [comment]
Indeed, the controller's DID Document (and thus key) may have been changed parallel to the DID Document change.

👍
