### ISSUE TITLE
Allow user identity passing in s2s flow

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#3186]
Since user wallets will probably serve QEAA and this is out of reach (for now), we need a different way to transfer user data. Maybe also obtained from some other token. This would also mean that the user flow won't be used (no sence) and means user identity must be transferred with the s2s flow.

**Comment by woutslakhorst** [comment]
Problem with being generic. Currently we use PDs to select VCs that should be in the VP. What is desired is later put into the introspection result (then used for authz). If ID tokens are not selected via PDs, there's no way to map fields from the ID token to the introspection result.

**Comment by reinkrul** [comment]
Related to https://github.com/nuts-foundation/nuts-specification/issues/275

**Comment by reinkrul** [comment]
Fixed by https://github.com/nuts-foundation/nuts-node/pull/3206 with the organization self-attesting the identity of the user.
