### ISSUE TITLE
Add `subject_id` to `did` table. Add `findBySubjectId`

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#3193]
Same subject DIDs should automatically add AlsoKnownAs of other DIDs to documents.

**Comment by reinkrul** [comment]
"Subject" is a ambiguous; `credentialSubject.id` is in our case a specific DID, not a grouping of DIDs owned by an entity. So when talking about "credential subject" it can then either be a DID or a group of DIDs. What happened to "tenant", "party", "entity"?

**Comment by woutslakhorst** [comment]
`DID Subject` as defined in DID Core

**Comment by reinkrul** [comment]
We probably need a `subject` table since we need to associate `did:nuts` with subjects, too
