### ISSUE TITLE
Allow passing of additional credentials to access token request and support holder claims

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#3198]
see https://www.w3.org/TR/vc-data-model-2.0/#presentations-including-holder-claims on how to use credentials without proof.

The idea is to add a credential without proof as param to the request-service-access-token call. This credential will be used as well when comparing the PD to the wallet of the organisation. This will expose fields from the credential via introspection.
We must support signing of such credentials by adding the holder property.

**Comment by reinkrul** [comment]
https://www.w3.org/TR/vc-data-model/#proofs-signatures:

> At least one proof mechanism, and the details necessary to evaluate that proof, MUST be expressed for a [credential](https://www.w3.org/TR/vc-data-model/#dfn-credential) or [presentation](https://www.w3.org/TR/vc-data-model/#dfn-presentations) to be a [verifiable credential](https://www.w3.org/TR/vc-data-model/#dfn-verifiable-credentials) or [verifiable presentation](https://www.w3.org/TR/vc-data-model/#dfn-verifiable-presentations); that is, to be [verifiable](https://www.w3.org/TR/vc-data-model/#dfn-verify).
This specification identifies two classes of proof mechanisms: external proofs and embedded proofs. An external proof is one that wraps an expression of this data model, such as a JSON Web Token, which is elaborated on in Section [6.3.1 JSON Web Token](https://www.w3.org/TR/vc-data-model/#json-web-token). An embedded proof is a mechanism where the proof is included in the data, such as a Linked Data Signature, which is elaborated upon in Section [6.3.2 Data Integrity Proofs](https://www.w3.org/TR/vc-data-model/#data-integrity-proofs).

But it could be considered an external proof (it's on the VP) from the VC's point of view?
