### ISSUE TITLE
Add `did_methods` config parameter, defaults to [web, nuts]. Order is significant.

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#3253]

**Comment by reinkrul** [comment]
Avoid underscores in config parameters, as this breaks confioguration through env variables.

**Comment by gerardsn** [comment]
Implemented as `didmethods` in #3254. Can this be closed?

**Comment by reinkrul** [comment]
I think the config flags are incorrect in that PR.
