### ISSUE TITLE
Auth: change API endpoint DID parameter to subject ID when requesting tokens/credentials

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#3262]
The current v2 auth API endpoints have DID as parameter for multi-tenancy: access tokens issued by the Authz Server are scoped to this parameter. However, since we now have a subject instead of DID as tenant, having the DID in endpoints complicates for endpoint registration in DID documents:

- it 1:1 binds a specific DID (e.g. did:web) to an Authz Server endpoint scoped to the same DID (although the subject might have multiple DIDs)
- DID isn't the primary parameter used for communicating tenancy to the local Nuts node, so constructing the authz server URL from the DID might require more API calls and resolving

Since the DID in the API endpoints are really only used for tenancy, we should change it to subject ID instead.

Out of scope:
- https://github.com/nuts-foundation/nuts-node/issues/3278

**Comment by woutslakhorst** [comment]
fixed bu #3333
