### ISSUE TITLE
VDR: Rename SubjectManager to Manager

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#3295]
The name stutters, due to the package name:

```didsubject.SubjectManager``` v.s. ```didsubject.Manager```

**Comment by woutslakhorst** [comment]
the interface is called `didsubject.Manager` which should be used when refering via a variable from a different package.

**Comment by reinkrul** [comment]
The type is called `Manager`, the interface `SubjectManager`.

**Comment by woutslakhorst** [comment]
haha, 🤦
