### ISSUE TITLE
Network: refactor Protocol layer (too many dependencies)

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#330]
Since we don't have dependency injection types that have too many dependencies stand out like a sore thumb. One of these is the `Protocol` type:

```
Configure(p2pNetwork p2p.Adapter, graph dag.DAG, publisher dag.Publisher, payloadStore dag.PayloadStore, diagnosticsProvider func() Diagnostics,
advertHashesInterval time.Duration, advertDiagnosticsInterval time.Duration, peerID p2p.PeerID)
```

This type should be refactored such that it has less direct dependencies (and maybe a nicer pattern for the configuration options, which are the last 3 parameters).

**Comment by woutslakhorst** [comment]
Generic code quality
