### ISSUE TITLE
Missing example for the service definition of discovery service files

### ISSUE THREAD

**Issue by stevenvegt** [nuts-foundation/nuts-node#3332]
This page https://nuts-node.readthedocs.io/en/latest/pages/deployment/discovery.html states a directory can be configured to put files that contain a `service definition` of a service.

The definition of the file contents seems to be missing.

From section 5 of [the unpublished spec](https://github.com/nuts-foundation/nuts-specification/pull/267/files#diff-c20b8160a8c6c799a245f12eeef505110a2bfea0a95d8eb5be28385a34d838c3) the following example could be used:

```json
{
  "id": "uc_university_v1",
  "endpoint": "https://example.com/usecase/university/v1",
  "presentation_max_validity": 259200,
  "presentation_definition": {
    "id": "pd_university",
    "input_descriptors": [ 
      {
        "id": "pd_university_type",
        "constraints": {
          "fields": [ 
            { "path": ["$.type"], "filter": { "type": "string", "const": "UniversityCredential" } }, 
            { "path": "$.credentialSubject.name", "filter": { "type": "string" } }
         ]
       }
     }
   ]}
 } 
```

**Comment by woutslakhorst** [comment]
it must be wrapped in a string to object mapping where the string is the desired scope

**Comment by woutslakhorst** [comment]
fixed
