### ISSUE TITLE
Discovery registration selects expired credential

### ISSUE THREAD

**Issue by stevenvegt** [nuts-foundation/nuts-node#3362]
**Description**:

I issued a credential with an `expirationDate` in the past. Then issued a new credential with the date in the future. When registering the subject for the discovery service, it replies with the following:

```
Unexpected HTTP response (len=169): {\"detail\":\"presentation is invalid for registration\\npresentation is valid longer than the credential(s) it contains\",\"status\":400,\"title\":\"RegisterPresentation failed\"}" http_request_path=/discovery/hackathon_v2024 module=Discovery
```

**Current behavior:**
It seems the wallet selects the first matching credential without looking if it is still valid.

**Expected behavior:**
The wallet selects the first valid credential.

**Comment by woutslakhorst** [comment]
`r.vcr.Wallet().List(ctx, subject)` just returns all credentials and doesn't filter on validity (and probably also not revocation)
