### ISSUE TITLE
VDR: v2 service APIs issues

### ISSUE THREAD

**Issue by gerardsn** [nuts-foundation/nuts-node#3366]
note: `service.id` == `serviceId`

### GET / search `/internal/vdr/v2/subject/{id}/service`
search based on `service.type`
`type` parameter is required in business logic, but optional in API

### POST / create `/internal/vdr/v2/subject/{id}/service`
It contains the following example for the body:
```
{
  "id": "string",
  "type": "string",
  "serviceEndpoint": "string"
}
```
`id` value is overwritten by the API.
The documentations says
> The ID is always generated. Duplicate services are ignored.

So `id` field should be removed from the example.
The definition of duplicates is unclear, is this based on `type` or in combination with `serviceEndpoint`?

~The generated `id` is a uuid that is the same for all DID docs in the subject. However, our did:nuts spec requires the `id` to be a hash of service.~ it is the hash of the document

### PUT / update `/internal/vdr/v2/subject/{id}/service/{serviceId}`
Same issues as POST.

Lookup is based on `service.id`, but we used to manage services using `service.type` and still use this in GET/POST. Doing everything by `service.id` would be more in line with the DID spec, but this requires us to change the way we work with services.

PUT first does a search based on the `serviceId` and then generates a new `serviceId` for the updated service. So the `serviceId` PUT is being called on is removed and replaced with a new one. Is this in line with REST?

### DELETE `/internal/vdr/v2/subject/{id}/service/{serviceId}`
Also managed by `serviceId`, which does not match the way we work with services. I also don't know how users are going to find the `serviceId` if it is not stored directly after creating/updating a service

**Comment by woutslakhorst** [comment]
> the way we work with services?

what does that mean?

**Comment by woutslakhorst** [comment]
I believe the awkwardness comes from the fact that we only look at the fragment of the given serviceID.

**Comment by gerardsn** [comment]
> > the way we work with services
> 
> what does that mean?

In did:nuts we reference services by `type` which MUST be unique in a DID document. We currently still create service based on type. If the nuts-node manages DID Documents we can also guarantee there is only 1 service per type. 

It is weird to create/search a service by type and then update/delete it by ID. 

Usage would look like
- A user creates a service on a subject with a certain type
- It then receives the created services, one per did in the subject, which is the input that now contains a service.id. The service.id is equal to full-did#serviceID, making users handle DIDs again.
- The user now has to store a mapping from `type` to `serviceID` to be able to update/delete it in the future
1. If the service is ever updated, the user's mapping also needs to be updated because the `serviceID` changes on an update. (This violates PUT semantics)
2. If the user did not save this mapping, it will have to query the node for which DIDs are in a subject and then resolve one of the DID Documents through the node to find the service. This goes against our view of abstracting the DIDs away for users.


3 And as you said, to use PUT/DELETE, users need to know that `serviceID` is the fragment of the service.id field

**Comment by gerardsn** [comment]
The current API is a better match for the DID semantics, but our conventions for `serviceID` and our goal of hiding the DIDs for an end user conflict with this

**Comment by woutslakhorst** [comment]
I don't agree that the users need to store anything. 

"Does my customer have service with type X" (using search):
- yes => check if URL is still valid. If not, update by ID 
- no => add it

Also users do not need to know that the fragment is used. This is done for them, they can just use the full ID.
If using services through the discovery service is a better match, we might as well deprecate this part of the API right away.

**Comment by woutslakhorst** [comment]
So actionable: improve API documentation?
