### ISSUE TITLE
SQL: did_service and did_verification_method entries are overwritten on DID updates

### ISSUE THREAD

**Issue by gerardsn** [nuts-foundation/nuts-node#3367]
`did_service` and `did_verification_method` table entries use the `service.id`/`verificationMethod.id` as primary key. This `id` does not change when a DID document is updated. Since the tables use the `did_document_version.id` as foreign key, any unchanged services and vms are overwritten during DID document updates. This means it is not possible to rebuild a DID document from the SQL data.

Does this matter? The latest version is probably the one we are interested in, and for this version the references are correct. For older versions the `did_document_version.raw` can be used.

**Comment by woutslakhorst** [comment]
This is a bug. New services get their ID by using a hash of the contents. So an update should definitely not use the same id

**Comment by gerardsn** [comment]
that is only if the service itself is updated, and that works as intended.

The issue here is that something else on the DID document is changed, and the older versions of the document now lose their reference to service since that now only points to the latest version of the document this service occurs on.

**Comment by gerardsn** [comment]
We could change the primary key to include `did_document_id` to make it unique for a document version. This would result in lot of copies of the same services / vms. This is also a foreign key, so I'm not sure this is even possible. 

Or invert the relationship. Let `did_document_version` point to all the services/vms `id`s it has.
