### ISSUE TITLE
DID @context are added in the wrong order

### ISSUE THREAD

**Issue by gerardsn** [nuts-foundation/nuts-node#3368]
what we produce:
did:nuts: `"@context":["https://nuts.nl/did/v1","https://w3c-ccg.github.io/lds-jws2020/contexts/lds-jws2020-v1.json","https://www.w3.org/ns/did/v1"]`
did:web: `"@context":["https://w3c-ccg.github.io/lds-jws2020/contexts/lds-jws2020-v1.json","https://www.w3.org/ns/did/v1"`

according to the DID spec https://www.w3.org/TR/did-core/#production-0:
> The serialized value of @ context MUST be the JSON String https://www.w3.org/ns/did/v1, or a JSON Array where **the first item** is the JSON String https://www.w3.org/ns/did/v1 and the subsequent items are ...

I believe this has to do with security context to prevent overloading values or something like that?

It's too late to fix this for `did:nuts`, but we should consider fixing it now that we are introducing new did methods.

(We've already fixed this for VC's)

**Comment by woutslakhorst** [comment]
nuts context is no longer used in code.
