### ISSUE TITLE
Discovery registrationParameters are empty when they shouldn't

### ISSUE THREAD

**Issue by stevenvegt** [nuts-foundation/nuts-node#3405]
After registering an org to a Discovery service:

`POST {{nuts-internal}}/internal/discovery/v1/hackathon_v2024/{{Org2SubjectId}}`

body:
```
{
  "registrationParameters":
    {
      "fhir": "http://fhir:8090/fhir"
    }
  
}
```

The result of a search does not contain the registrationParameters:

`GET {{nuts-internal}}/internal/discovery/v1/hackathon_v2024?credentialSubject.organization.name=VVT*`
```
[
  {
    "credential_subject_id": "did:web:localhost%3A5551:iam:d8f7e763-4396-458c-b6ee-890ecca2c1eb",
    "fields": {
      "city": "Grunloe",
      "name": "VVT de Regenboog",
      "ura": "88888888"
    },
    "id": "did:web:localhost%3A5551:iam:d8f7e763-4396-458c-b6ee-890ecca2c1eb#65a24ac5-bbbc-48f8-95c9-6307722f9900",
    "registrationParameters": {},
    "vp": "eyJhbGciOiJF..."
}
```

**Comment by woutslakhorst** [comment]
if Registration Credentials are not present in presentation definition, they are filtered out....
