### ISSUE TITLE
Discovery service retry for failed registration is unclear

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#3408]
The discovery service client will try to register VPs even if the holder doesn't have the right credentials. This is strange behaviour. Proposal is to return a 409 if the PD is not satisfied and only refresh when still valid. In all other cases don't retry.

If for whatever reason the PD is updated which causes current registrations to become invalid, this will be a manual check.`GetServiceActivation` can be used for this.

**Comment by reinkrul** [comment]
If the credential expired, it would be nice if it auto-healed without having to reactivate the service.

**Comment by woutslakhorst** [comment]
My proposal would be twofold:
- add parameter for activation: `immediate` which would cause a 400/412 if it fails. No retry is done.
- add status SQL table that holds status/error per subject/did that is available via API.
