### ISSUE TITLE
Holder APIs don't check holder DID param

### ISSUE THREAD

**Issue by stevenvegt** [nuts-foundation/nuts-node#3413]
I'm able to use invalid DIDs in the vcr/holder apis.
When adding a new VC, the holder DID from the URI does not have to match the `credentialSubject.id`.

Examples:

```
POST {{nuts-internal}}/internal/vcr/v2/holder/unknown-did/vc
valid body for known did:
{
  "@context": [...],
  "credentialSubject": {
    "id": "did:web:localhost%3A5551:iam:known-did",
    ...
  },
  ...
}
```

```
POST {{nuts-internal}}/internal/vcr/v2/holder/known-did/vc
body:
{
  "@context": [...],
  "credentialSubject": {
    "id": "did:web:localhost%3A5551:iam:unknown-did",
    ...
  },
  ...
}
```

All result in a 204

```
POST {{nuts-internal}}/internal/vcr/v2/holder/unknown-did/vc
```
Result in `status 200` with an empty array.

Expected results:
1. Check if the holder DID-param in the URL is known
2. Check if the `credentialSubject.id` matches the DID-param

**Comment by woutslakhorst** [comment]
The API description doesn't say the two have to match. Currently everything credential is put into the DB. When creating a VP, VCs are selected based on credentialSubject.id.

**Comment by reinkrul** [comment]
What would be the potential future use case to have them differ? Otherwise, it can only create confusion

**Comment by woutslakhorst** [comment]
Now we can without any harm to create more clarity:

- change `did` param to `subject` param
- check if subject is owned by node

**Comment by reinkrul** [comment]
Why would we check signatures? Receiving a VC with an invalid signature would be very odd. If testing is of concern, maybe we should check signatures after issuance.

**Comment by woutslakhorst** [comment]
Does it hurt to check it?

**Comment by gerardsn** [comment]
I believe the idea was that you do not need to be able te verify a VC to use it. 

So if you get a VC issued by `did:amazing:new-method` then you can still use that VC even though you can't verify it. Most likely the verifier will also be a nuts-node that can't handle it, but this could potentially be useful somewhere in the future in something like a e-herkenning flow? (any non-node2node communication) 

I think this could enable (partial) forward compatibility for nodes running an older version that does not support the new DID method. (Assumes VPs can be signed by other DID methods than used in the VC / reintroduction of AKA...)

Anyway, all hypothetical use-cases that might not play a decisive role in adding signature validation right now.
