### ISSUE TITLE
Network: peer diagnostics/state incorrect after reconnect

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#342]
After a peer (Raspberry PI in electrical cabinet at home) disconnected and directly reconnected again to a node hosted in the cloud, the diagnostics on the cloud node are incorrect. It shows up in the "omnihashes" statistic, but not in the "connected peers":

```
[Protocol] Peer omnihashes: a776b8c9ac6f5349065612521de7a7ec9eb608af1a00f45f2c98dd58bb1cc41e={f7e7ef59-dbf4-46dd-b2f6-90c3dec4b3a0, ce26f36a-7dfb-4733-838b-c35e633a5cec, c1323417-ea15-40f1-a190-546b5b46bd5b, 6488eaf3-cec8-4986-a2c3-fd2f6a768a5e, 3a6d9005-7b12-464f-894d-c9057ef9bd96}
```

Log of Raspberry PI node:

```
time="2021-06-16T23:34:59Z" level=warning msg="Peer connection error (peer-id=edc2f210-6c39-4823-ab49-b47953ec57fc): rpc error: code = Unavailable desc = transport is closing" module=Network
time="2021-06-16T23:34:59Z" level=warning msg="Peer connection error (peer-id=c1323417-ea15-40f1-a190-546b5b46bd5b): rpc error: code = Unavailable desc = transport is closing" module=Network
time="2021-06-16T23:34:59Z" level=info msg="Connected to peer (id=edc2f210-6c39-4823-ab49-b47953ec57fc,addr=nuts.reinkrul.nl:5555)" module=Network
time="2021-06-16T23:35:00Z" level=info msg="Connected to peer (id=c1323417-ea15-40f1-a190-546b5b46bd5b,addr=********:5555)" module=Network
```

Log of cloud node:

```
time="2021-06-16T23:34:59Z" level=info msg="New peer connected (peer=f7e7ef59-dbf4-46dd-b2f6-90c3dec4b3a0@213.127.27.252:29120)" module=Network
time="2021-06-16T23:35:22Z" level=warning msg="Peer connection error (peer-id=f7e7ef59-dbf4-46dd-b2f6-90c3dec4b3a0): rpc error: code = Canceled desc = context canceled" module=Network
```

So the peers is actually connected, but the diagnostics are screwed up.

**Comment by woutslakhorst** [comment]
Not totally clear what the problem is....

**Comment by reinkrul** [comment]
> Not totally clear what the problem is....

Updated the description.

This happens because the lifecycle of a connecting peer is racy. What happened:

- PI node experienced a network problem (closed connection), so it reconnects to cloud node
- Cloud node accepts new connection -> diagnostics updated with new peer (which was already connected, according to the diagnostics).
- Cloud node realizes first connection is broken, disconnects it -> remove peer from diagnostics (`Connected peers`)
- PI node publishes DAG heads -> Cloud node re-adds the peers omnihash to diagnostics

`Connected peers` and `Peer hashes` is now out-of-sync.

The problem is two-fold:

- We haven't specified what happens if the same peer (identified by peer ID) connects twice. We don't want duplicate connections: we only need 1 between 2 peers and having more adds overhead. I think we the accepting node should disconnect the first connection and accept the second connection, because the first connection might be broken (and therefore cause the peer to reconnect).
-

**Comment by reinkrul** [comment]
Specified in https://github.com/nuts-foundation/nuts-specification/pull/87
