### ISSUE TITLE
Auth: RFC021 additional credentials + multiple DID methods enabled = failure

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#3423]
When a service access token is requested (RFC021) when multiple DID methods are enabled, and additional credential(s) (NutsEmployeeCredential) are provided, an error occurs;

```
multiple sign instructions not supported
```

This is probably due to the submission builder matching on VCs from multiple DIDs/wallets. It should probably try to fulfil the input descriptors using the same DID? Or at least sort them to make it generally succeed. Now it seems to always fail.

**Comment by woutslakhorst** [comment]
duplicate of #3424
