### ISSUE TITLE
Node panics when registering on a discovery service and ./config/discovery does not exist

### ISSUE THREAD

**Issue by gerardsn** [nuts-foundation/nuts-node#3456]
`Module.Condfigure(...)` exits when the default directory does not exist causing `publicURL` to not be set. This results in a panic when a user tries to register anything on a discovery service.

`./config/policy` uses the same approach in `Configure(...)`, so may suffer from similar issues.

**Comment by woutslakhorst** [comment]
> `./config/policy` uses the same approach in `Configure(...)`, so may suffer from similar issues.

You mean `./policy/local.go#configure`? It doesn't do any other initialisation.

**Comment by gerardsn** [comment]
then policy probably does not suffer from this
