### ISSUE TITLE
API proposal: DELETE /internal/vcr/v2/holder/{subjectID}/vc/{id}

### ISSUE THREAD

**Issue by gerardsn** [nuts-foundation/nuts-node#3462]
we currently have 
```
DELETE /internal/vcr/v2/holder/{did}/vc/{id}
```
which is the only API that still uses `{did}`.

probably a 'nice to have' to make the API's consistent

**Comment by woutslakhorst** [comment]
Since the ID of the VC is already enough, we could just change it to subject?

**Comment by woutslakhorst** [comment]
we can introduce a REMOVE api ;) and deprecate the old one.

**Comment by gerardsn** [comment]
turns out `DELETE /internal/vcr/v2/holder/{did}/vc/{id}` is a new API, so we can just change it

**Comment by woutslakhorst** [comment]
> turns out `DELETE /internal/vcr/v2/holder/{did}/vc/{id}` is a new API, so we can just change it

should not be done in an RC but given the amount of users we have world wide....
