### ISSUE TITLE
If revocation status list is down, discovery registration fails

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#3468]
Should be a default-open state, if it can't fetch the status list? (just like the CRLs)

**Comment by woutslakhorst** [comment]
For registration this would be ok, for downloading not. The current client ignores invalid VPs/VCs and still updates it LC. That will become more complicated.

An alternative would be to check it runtime, but that would require a local copy of the revocationlist at all times. An asynchronous download would then also be required.

**Comment by woutslakhorst** [comment]
Since most issuers will also be those who register themselves, registration is not really an issue (now). Clients could face a problem that they will ignore a VP when downloaded (and revocation is unavailable). This leads to an unrecoverable situation.

**Comment by woutslakhorst** [comment]
Proposal:

- always download (unchecked, trust server)
- add column for validation (bool)
- not validated, do not return search result
- add background process for validation
- add background process to check for `exp` and revocation status. If expired or revoked, remove from list.
