### ISSUE TITLE
Check write rights for user on startup

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#3470]
to prevent "out-of-memory" error

**Comment by woutslakhorst** [comment]
This should be done from within the deprecated storage initialization since a did:web/v6 only impl doesn't require write access.

**Comment by reinkrul** [comment]
Except for sqlite

**Comment by gerardsn** [comment]
issue occurs on linux hosts with a mounted datadir because the host user does not match the container user
