### ISSUE TITLE
Regex for subject doesn't match documentation

### ISSUE THREAD

**Issue by tomelfring** [nuts-foundation/nuts-node#3481]
The regex used for a subject doesn't match with the documentation next to it. Also it doesn't match the documentation used in NUTS-admin. Documentation states an underscore is allowed, regex doesn't allow it.

Regex:
https://github.com/nuts-foundation/nuts-node/blob/master/vdr/didsubject/manager.go#L44-L45

NUTS-admin:
https://github.com/nuts-foundation/nuts-admin/blob/main/web/src/admin/IdentityForm.vue#L8

Possible solutions:
- Change the regex to include underscore: `^[a-zA-Z0-9.-_]+$`
- Change documentation to match regex

**Comment by woutslakhorst** [comment]
@reinkrul your design ideas?

**Comment by woutslakhorst** [comment]
I would say `_` is fine since it doesn't require path escaping
