### ISSUE TITLE
DAG unittest: `TestBBoltDAG_Diagnostics` fails on arm64

### ISSUE THREAD

**Issue by dmeijboom** [nuts-foundation/nuts-node#352]
The test failed on my Apple Macbook M1 (and in a clean docker environment using the `arm64` platform).
It succeeds when switching to `amd64` in docker.

Logs:

```
--- FAIL: TestBBoltDAG_Diagnostics (0.11s)
    bbolt_dag_test.go:238: 
                Error Trace:    bbolt_dag_test.go:238
                Error:          Not equal: 
                                expected: "[DAG] Heads: [3a3b3e2ada3df88bcede97f7ff4a05c29ed2c2a9c282fd0f599fbd1cb732d0b0]\n[DAG] Number of transactions: 1\n[DAG] Stored transaction size (bytes): 8192"
                                actual  : "[DAG] Heads: [3a3b3e2ada3df88bcede97f7ff4a05c29ed2c2a9c282fd0f599fbd1cb732d0b0]\n[DAG] Number of transactions: 1\n[DAG] Stored transaction size (bytes): 32768"
                                
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -2,2 +2,2 @@
                                 [DAG] Number of transactions: 1
                                -[DAG] Stored transaction size (bytes): 8192
                                +[DAG] Stored transaction size (bytes): 32768
                Test:           TestBBoltDAG_Diagnostics
time="2021-07-05T11:04:35+02:00" level=error msg="Unable to read payload to publish DAG: (ref=aea340244cc662167ac6ed4b192512a2fc29026eb0f6e3b00ec13db7868257bd) failed" module=Network
time="2021-07-05T11:04:35+02:00" level=error msg="Transaction subscriber returned an error (ref=744d4d985b4129b0bd7ee64ae89f80ecea79f5459e73b27dbfef7ea16ebf158d,type=foo/bar): failed" module=Network
FAIL
FAIL    github.com/nuts-foundation/nuts-node/network/dag        4.439s
```

**Comment by dmeijboom** [comment]
This has to do with the page size (which differs per architecture). Page size on `amd64` is ~ `4000` while on `arm64` (at least for the Apple M1) it's `16000`. As bbolt will allocate 2 pages of memory it explains the difference between both architectures.

We could fix this by calculating the page size using `os.Getpagesize()` but I'd rather remove the memory check as it's up to bbolt how to deal with memory internally.

**Comment by reinkrul** [comment]
This diagnostic is broken anyways, because it just indicates the number (and size) of pages which are allocated. But it was the best I could find to indicate transaction store size. Question is also, maybe it's better to have the actual database size (as it is now) rather than the actual stored transaction size. Because the first one is the amount of disk space being used. I'd say just check that the size is `> 0`?
