### ISSUE TITLE
PKI: accepts certs not in truststore when softfail=true (default)

### ISSUE THREAD

**Issue by gerardsn** [nuts-foundation/nuts-node#3528]
PKI validator should only accept certificates from CAs that are in the truststore, also when set to softfail.

this is currently working as designed, so I removed the bug label
From the `Validator.Validate` interface:
```
Ignoring all errors except ErrCertRevoked changes the behavior from hard-fail to soft-fail. Without a truststore, the Validator is a noop if set to soft-fail
```
Is there a reason we needed it this way?

backport to V5.4 and V6.0 if accepted

**Comment by woutslakhorst** [comment]
As discussed, all CAs must be in the truststore also for did:x509
