### ISSUE TITLE
PKI: add method to perform strict validation for did:x509 regardless of configured softfail value

### ISSUE THREAD

**Issue by gerardsn** [nuts-foundation/nuts-node#3530]
`did:x509` must always fail if the CRLs are not available.

For certificate validation on a connection, we allow the user to set a strategy with `pki.softfail` since it is only one of the security measures. 
For `did:x509` the certificate forms the root of trust so it MUST always be validated against its CRL.

Consequences of this change:
- all CAs accepted for `did:x509` must be added to the configured truststore `tls.truststorefile`
- The truststore is (was already) used for more things than the nuts network. This means gRPC traffic should always be offloaded in the proxy and validated against the correct chain before sending it to the nuts-node.

**Comment by woutslakhorst** [comment]
> The truststore is (was already) used for more things than the nuts network. This means gRPC traffic should always be offloaded in the proxy and validated against the correct chain before sending it to the nuts-node.

This would become an issue for v7 when the tls config param is removed but did:x509 still exists?

**Comment by gerardsn** [comment]
new requirement to offloading of certs is documented. Implications of using deprecated features will be re-evaluated when v7 is being prepared
