### ISSUE TITLE
did:x509 issuer and resolver assume the root CA as ca-fingerprint

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#3587]
Which is wrong: in practice, this will be PKIOverheid Private Service Root CA, meaning _any_ intermediate CA certificate is accepted. This would allow more intermediate CAs than CIBG UZI (through KPN) to issue certificates that can used to create `UziServerCertificateCredential`.

The did:x509 spec states that the ca-fingerprint property can be of any root or intermediate CA. It's then up to the verifier (in our case through PEX) to restrict this to the accepted trust anchors

Meaning:
- The uzi-x509-issuer tool should take the direct issuer of the UZI server certificate (deepest intermediate CA), since this (probably) what use cases/Bolts want to configure in their PEX PDs
- The DID resolver in the Nuts node should take any ca-fingerprint to validate the cert chain, instead of hardcoded assume it's the root CA's ca-fingerprint.

**Comment by woutslakhorst** [comment]
Something to put in the RFC

**Comment by reinkrul** [comment]
- For Nuts-node: accept any CA level for ca-fingerprint
- For issuer tool: pick first non-registration authority CA (CIBG Intermediate, so not PKIOverheid Private Services Root CA, not KPN intermediate CA)

**Comment by rolandgroen** [comment]
Linked to nuts-foundation/uzi-did-x509-issuer#31
