### ISSUE TITLE
X509Credential validation

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#3599]
According to RFC, does credentialSubject contain only properties from the did:x509

**Comment by woutslakhorst** [comment]
During validatoin the did:x509 CRL MUST also be checked. This can't be checked during the did resolve since this would allow for a _CRL list spam_ attack.

**Comment by gerardsn** [comment]
see https://github.com/nuts-foundation/nuts-node/pull/3606#issuecomment-2540987436 and comment after that
