### ISSUE TITLE
RFC003: JWT Grant is missing some fields

### ISSUE THREAD

**Issue by dmeijboom** [nuts-foundation/nuts-node#369]
According` to [RFC003](https://nuts-foundation.gitbook.io/drafts/rfc/rfc003-oauth2-authorization#4-2-2-payload) the JWT Grant is missing the following fields:
- vcs: A list of base64 encoded Nuts Authorization Credentials. Optional
- purposeOfUse: A list of desired usages. Corresponds to Bolts. Omitted when empty.

Note that these fields are concidered out of scope for now:
- osi: Ops signature, optional, reserved for future use.

**Comment by woutslakhorst** [comment]
isn't `usi` included yet?

**Comment by woutslakhorst** [comment]
Creating the JWT grant token already includes the `usi` field.

See auth/services/messages.go#55

**Comment by dmeijboom** [comment]
> Creating the JWT grant token already includes the `usi` field.
> 
> See auth/services/messages.go#55

Ah right, removed it from the list!
