### ISSUE TITLE
Consistent logging

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#40]

**Comment by woutslakhorst** [comment]
- [ ] check if all engines create a logger
- [ ] set log level from config
- [ ] setup logging defaults, when and where to do debug, info, error, warn

**Comment by woutslakhorst** [comment]
Proposal for logging:

## Error log
Use error logging at the 'edge' of the application: when an API returns a 500, at startup or when a asynchronous task fails and puts something in an dl-queue (eg: network receiving a transaction and not being able to process it). This will make sure each error is only logged once. Error logging should require immediate attention. System level events like out-of-memory also result in Error logging (and usual a crash of the application).

## Warn log
Use warn logging when an API returns a 40x code. Warn logging could also be used at places where 'undesired' behaviour is detected or when deprecated functionality is used. 
Warn log should act as input to change user behaviour or change the way connecting software works.

## Info log
Info logging may be used in the 'service' layer and API layer indicating an action has been completed with the result (like an identifier).

## Debug log
Debug logging may be used in the API and service layer when an action is started. It may also display the given parameters for the action. In general this would be the case for public methods.

## Trace logging
Trace logging may be added at each level of the application but only at the beginning of a function. Trace logging may also be added to private methods.

**Comment by reinkrul** [comment]
Can we include not using `Fatal`, since that panics the application?


imo a panic should never be used where you can just return an error and let the call tree decide whether to exit the application or not.

**Comment by woutslakhorst** [comment]
I saw a blog post somewhere where custom errors were used throughout the app. The custom errors contained a msg to the user but also a technical msg and trace for the administrator. We could use something like that to differentiate between return errors and logged errors.

**Comment by reinkrul** [comment]
> I saw a blog post somewhere where custom errors were used throughout the app. The custom errors contained a msg to the user but also a technical msg and trace for the administrator. We could use something like that to differentiate between return errors and logged errors.

I always find that quite fiddly, because it depends on the interface through which the call is made, how technical the user is. So imo you can only decide on what to return to the caller in the interface layer. For instance; what message would you present to the user when an array index is out of bounds, or a piece of JSON can't be parsed? (answer: it depends...)

**Comment by woutslakhorst** [comment]
When errors are replaced by another error: a file not found to a app specific error. That could be a good place to add some logging since the original message is gone. If it's unintended it's an `error` if it's user error it's a `warn`

**Comment by reinkrul** [comment]
Stuff that's left to fix:

- [ ] Consistency in log-with-formatting v.s. log-with-fields
- [ ] Maybe some more trace/debug logging in places where considered appropriate
