### ISSUE TITLE
Dependabot PRs fail due to missing Docker registry info

### ISSUE THREAD

**Issue by gerardsn** [nuts-foundation/nuts-node#404]
Docker registry info + secrets need to be added for Dependabot.

**Comment by gerardsn** [comment]
[GitHub Actions triggered by Dependabot](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/automating-dependabot-with-github-actions) fail due to:
> For workflows initiated by Dependabot (github.actor == "dependabot[bot]") using the pull_request, pull_request_review, pull_request_review_comment, and push events, the following restrictions apply:
>
>GITHUB_TOKEN has read-only permissions.
Secrets are inaccessible.

**Comment by woutslakhorst** [comment]
we'll disable image pushing for PRs

**Comment by woutslakhorst** [comment]
it's the e2e tests that fail due to missing rights on the local repo. Image pushing is already disabled to docker for PRs
