### ISSUE TITLE
Make sure VCs aren't embedded in the Access Token

### ISSUE THREAD

**Issue by dmeijboom** [nuts-foundation/nuts-node#423]
It could be that this is already the case but we need to make sure verifiable credentials are not embedded in the Access Token response as we will hit header size quickly. They are embedded in the request but in the response we should use DIDs instead.

**Comment by woutslakhorst** [comment]
The access token is custom, so they would have proactively been put there. Should be DID URLs indeed.

**Comment by woutslakhorst** [comment]
This is already fixed
