### ISSUE TITLE
Aliased API types should delegate JSON (un)marshaling to aliased type

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#443]
Some or our generated Open API implementations alias an existing type instead of generating one, for simplicity (e.g. `VerifiableCredential` in VCR or `DIDDocument` in VDR).

Many of these types however, have custom JSON (un)marshalers, being one of the reasons why they're aliased instead of generated. However, they don't actually call the JSON (un)marshalers of the underlying type.

These aliased types should probably redefine the JSON unmarshalers and delegate it to the underlying type?

**Comment by woutslakhorst** [comment]
After some searching, I'm afraid so.... are there any unit tests to confirm its going wrong?

**Comment by woutslakhorst** [comment]
can't reproduce. Seems to be working
