### ISSUE TITLE
Proposal | Add reverse DNS lookup so the diagnostics shows DNS name

### ISSUE THREAD

**Issue by gjrtimmer** [nuts-foundation/nuts-node#466]
Implement reverse DNS lookup, this will allow the diagnostics to show the DNS where it connects to instead of the IP number.
Very useful for IT administrators.

Status
	Registered engines: Status,Metrics,Crypto,Network,Verifiable Data Registry,Verifiable Credential Store,Auth,Didman
	Uptime: 97h32m13.397769877s
	SoftwareVersion: master
	Git commit: efaf817154a0b524d63f75139c83dc4fa735a9ea
	OS/Arch: linux/amd64
Network
	[Protocol] Peer omnihashes: c1c0292d6baa56b1b7f2c99ac90e7a6a17db895b60eec9fb4a7d934497c67662={ae6c5592-0d9b-4fe2-9ef4-7376acf82831}, 2adfc8099d416b1943a0fc780cdc2dec2df715865b2e0aa3d36bc93af7ee9ce5={ce26f36a-7dfb-4733-838b-c35e633a5cec, 919ed4b7-f4f9-4b33-a143-c676ff39aafb, 54d0e7c5-525f-4fc5-b253-920b9be7d8e9, 3cbcc178-683a-48d7-8143-ce3cdeeb5f71, 336abe5a-189f-4b36-8dee-38c93f6dc651}
	[P2P Network] Connected peers #: 6
	[P2P Network] Connected peers: ce26f36a-7dfb-4733-838b-c35e633a5cec@144.2.168.69:35002 ae6c5592-0d9b-4fe2-9ef4-7376acf82831@82.75.148.49:50344 919ed4b7-f4f9-4b33-a143-c676ff39aafb@213.127.15.166:45926 54d0e7c5-525f-4fc5-b253-920b9be7d8e9@77.166.140.253:39466 3cbcc178-683a-48d7-8143-ce3cdeeb5f71@84.104.10.210:34918 336abe5a-189f-4b36-8dee-38c93f6dc651@nuts.woutslakhorst.nl:5555
	[P2P Network] Peer ID of local node: 689d995b-de18-4635-a898-4a49451e0387
	[DAG] Heads: [845d3aebb1b01e03c2af07ac171449e4b16360a6b8a452e5be10c1911f8455db]
	[DAG] Number of transactions: 459
	[DAG] Stored database size (bytes): 319488
Verifiable Data Registry
	# Conflicted DID Documents: 2

**Comment by woutslakhorst** [comment]
not really needed when nodes get a DID as well.

**Comment by reinkrul** [comment]
I don't see IP addresses in the diagnostics anymore these days. Closing for now,

**Comment by gerardsn** [comment]
inbound still shows IP, outbound shows NutsComm/bootstrap address

**Comment by reinkrul** [comment]
I'd suggest reopening when someone asks about it again
