### ISSUE TITLE
Proposal | Implement json output for diagnostics

### ISSUE THREAD

**Issue by gjrtimmer** [nuts-foundation/nuts-node#468]
Implement a request for different output of the diagnostics, this will allow parsing by external tools.

## Proposal
```bash
?format=yaml
?format=json
```
When this parameter is added to the diagnostics the result it returned in `yaml` or `json`

**Comment by woutslakhorst** [comment]
Better to use the `Accept` header.

**Comment by gjrtimmer** [comment]
@woutslakhorst Agreed

**Comment by reinkrul** [comment]
@gjrtimmer we just implemented this, thanks for the suggestion!
