### ISSUE TITLE
Auto-healing for missing payloads

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#474]
Our current payload-retrieval function states:

```
// TODO: Currently we send the query to the peer that sent us the hash, but this peer might not have the
//   transaction contents. We need a smarter way to get it from a peer who does.
```

The function (to retrieve payload) is only called when a transaction is received. The peer however, might not have the payload or something might wrong while receiving the payload (network partition, disk fault, OS crash, etc) leading to the payload not being received. Since the process isn't retried, the payload will never be received and thus will be forever missing.

We have plans to make receiving both transaction and payload atomic, then this situation can't occur any more. But we need a fix for the meantime.

We could introduce a goroutine that periodically finds transactions which' payload is missing, and query all peers for the payload. That way the situation will be resolved over time, unless nobody has it any more, because the node has gone away or because of a network partition. In that case the branch should be garbage collected after some time.

**Comment by woutslakhorst** [comment]
fetching payloads will be something that will also be there in a newer version of the protocol.
