### ISSUE TITLE
Fix and debug strange memory corruption issue

### ISSUE THREAD

**Issue by dmeijboom** [nuts-foundation/nuts-node#488]
In the hackathon some Nuts nodes gave strange errors such as:

```
node_1   | time="2021-09-29T13:47:07Z" level=info msg="Received transaction hash from peer that we don't have yet or we're missing its contents, will query it (peer=3073bb0b-1652-455a-a7c9-b1f523331d27,hash=8925c3b1f5b1c3ca50993e43ac04337046f8139b672e7ba482651012052b9d35)" module=Network
node_1   | Error: transaction verification failed (tx=871b720e6b00b747dc21938a67bfa0cf8f1b4292d902084fbdab31d891e73ee6): failed extract from compact serialization format: invalid number of segments
```

or

```
node_1   | Error: transaction verification failed (tx=e389c595a07235609ada2a9b6b94b8e1eb3877a91458e7ac0124277522a58362): failed to decode signature: failed to decode source: illegal base64 data at input byte 86
```

We need to debug what's going on here.

**Comment by reinkrul** [comment]
Just discussed this with @woutslakhorst and maybe it has to do with us using bbolt values (slices) outside the transaction, which isn't allowed.

Before trying to fix this I'll be setting up a testenvironment with 20-ish machines producing/updating DIDs, so we can hopefully reproduce this.

**Comment by dmeijboom** [comment]
> Just discussed this with @woutslakhorst and maybe it has to do with us using bbolt values (slices) outside the transaction, which isn't allowed.

Could be. Should be an easy fix too if that's really the issue.

> Before trying to fix this I'll be setting up a testenvironment with 20-ish machines producing/updating DIDs, so we can hopefully reproduce this.

Sounds good. We might even want to add this in the E2E test.

**Comment by woutslakhorst** [comment]
To fix properly, branch from a point before #489 was fixed

**Comment by reinkrul** [comment]
Fixed as part of https://github.com/nuts-foundation/nuts-node/pull/492

**Comment by reinkrul** [comment]
After applying these changes I couldn't reproduce it any more (on my local Docker setup). I could write a failing integration test that proves you get corrupted byte slices when you use one returned by BBolt outside of its transaction, but then I would just be testing BBolt instead of our integration with it.

How would you prove it?

**Comment by reinkrul** [comment]
> branch from an earlier point, apply the deadlock fix and then use the load test to prove it?

See https://github.com/nuts-foundation/nuts-node/pull/537 for failing unit test:

```
--- FAIL: TestBBoltDAG_Get (0.17s)
    --- FAIL: TestBBoltDAG_Get/bbolt_byte_slice_is_copied (0.11s)
        bbolt_dag_test.go:116: 
            	Error Trace:	bbolt_dag_test.go:116
            	            				asm_amd64.s:1581
            	Error:      	Received unexpected error:
            	            	illegal base64 data at input byte 0
            	            	failed to decode source
            	            	github.com/lestrrat-go/jwx/internal/base64.Decode
            	            		/home/circleci/go/pkg/mod/github.com/lestrrat-go/jwx@v1.2.6/internal/base64/base64.go:59
            	            	github.com/lestrrat-go/jwx/jws.parse
            	            		/home/circleci/go/pkg/mod/github.com/lestrrat-go/jwx@v1.2.6/jws/jws.go:612
            	            	github.com/lestrrat-go/jwx/jws.parseCompact
            	            		/home/circleci/go/pkg/mod/github.com/lestrrat-go/jwx@v1.2.6/jws/jws.go:598
            	            	github.com/lestrrat-go/jwx/jws.Parse
            	            		/home/circleci/go/pkg/mod/github.com/lestrrat-go/jwx@v1.2.6/jws/jws.go:427
            	            	github.com/nuts-foundation/nuts-node/network/dag.TestBBoltDAG_Get.func3.1
```
