### ISSUE TITLE
AdvertHashes always returns empty blocks in development network

### ISSUE THREAD

**Issue by dmeijboom** [nuts-foundation/nuts-node#501]
Not sure if this is an issue in the Nuts Node implementation or rather specifically an issue on the development network but it seems like the `AdvertHashes` network-message doesn't include actual blocks.

Example:

```
AdvertHashes(AdvertHashes {
  current_block_date: 1633305600,
  blocks: [
    BlockHashes { hashes: [] },
    BlockHashes { hashes: [] }
  ],
  historic_hash: [
    44, 118, 35, 87, 185, 160, 39, 220, 131, 126, 167, 45, 38, 167, 25, 255, 223, 222, 0, 239, 65, 196, 75, 161, 63, 233, 117, 141, 234, 99, 119, 252
  ]
})
```

Is this simply not implemented, am I reading the spec wrong or is it a bug?

**Comment by woutslakhorst** [comment]
today, yesterday and everything before. So no TXs were published today and yesterday....

**Comment by dmeijboom** [comment]
> today, yesterday and everything before. So no TXs were published today and yesterday....

Check, wasn't aware that the blocks we're only from today + yesterday.
