### ISSUE TITLE
Secure management/ops APIs with authentication

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#540]
They're now unsecured and we depend on the deployment (e.g. behind a firewall/reverse proxy) to secure it.

This probably applies to all `/internal` APIs.

**Comment by reinkrul** [comment]
There's a few parts to decide on:

- What is the actual use case/why do we need it?
- What authentication types to support, e.g.:
  - TLS client authentication
  - Simple token based (e.g. JWT bearer)
  - Token based with protocol (e.g. OAuth2)
  - IP whitelist
  - Basic auth
- What to support in the Nuts CLI
- What to support in the Nuts API
- What is the current de facto industry standard
- Do we need authorization?

Since authentication could also be handled by a reverse proxy (proxying calls to the Nuts node), we don't necessarily need to support all means within the Nuts node itself. All of these options above could actually be implemented by that proxy.

**Comment by woutslakhorst** [comment]
App authentication within an infrastructure. Not all apps may access others apps.
An initial thought would be mTLS for an admin working remote, this could be handled by a proxy.
API keys for other apps, injected by env variables

**Comment by reinkrul** [comment]
@dmeijboom @stevenvegt your thoughts?

**Comment by dmeijboom** [comment]
It depends. In production, mTLS makes sense as these endpoints are internal anyways (they shouldn't be publicly accessible). Assuming the private keys are stored somewhere else (like Vault indeed) I'm not sure if we really need something like token based authentication.

**Comment by reinkrul** [comment]
Allowing a JWT to be used is the most straightforward approach. While simple to use as-is, this is the most flexible option to integrate with other existing auth platforms.

Provide command to generate a token, store signing key in configured crypto store.

Allow token to be passed either as argument to CLI commands or read it from file (e.g. `auth.token`).
