### ISSUE TITLE
Auth: externalize IRMA embedded database

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#542]
So clustering can be supported, without having to route callbacks from the IRMA app back to the initiating Nuts node (a.k.a. sticky sessions).

**Comment by reinkrul** [comment]
I believe so, yes.

**Comment by woutslakhorst** [comment]
They currently support a single Redis as session database. Not clustered yet.

**Comment by reinkrul** [comment]
I see 2 issues with this:

1. `irmago` only supports Redis 8, while we support Redis 9 (may not be a problem since the protocol appears to be backwards compatible).
2. `irmago` does not allow you to configure a key prefix or pass the Redis client itself, so we can't use `go-stoabs` for connection management or partitioning of databases. It allows you to configure the database (integer), which we don't use in `go-stoabs`. So there's a mismatch there.

**Comment by woutslakhorst** [comment]
I'd say the redis instances must be separated. The session storage is transient, our storage is persistent. You can't do that in one instance.

**Comment by woutslakhorst** [comment]
won't fix
