### ISSUE TITLE
Decide which endpoints need CORS enabled

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#60]
Currently CORS is enabled for all endpoints (because appearantly `nuts-auth` needs it?), but this could lead to security vulnerabilities. We need to decide which endpoints really need it and just enable it on those. Maybe using the new `HTTPConfig` configuration options.

**Comment by reinkrul** [comment]
@stevenvegt I believe you told me `auth` needs CORS at a certain point, can you please explain why/where?

**Comment by stevenvegt** [comment]
When the IRMA endpoints are hosted on their own (sub)domain and the front end application (hosted on a different domain) connects directly to these endpoints (for e.g. session polling) CORS needs to be enabled on these paths.

**Comment by woutslakhorst** [comment]
the irma endpoints run at the nuts sub-domain
the app runs at a xis domain

right?

**Comment by reinkrul** [comment]
Now implemented and documented.
