### ISSUE TITLE
implement RFC015: network identity

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#603]
- Send node DID: https://github.com/nuts-foundation/nuts-node/issues/623
- Authenticate node DID: https://github.com/nuts-foundation/nuts-node/issues/639
-

**Comment by reinkrul** [comment]
Related: https://github.com/nuts-foundation/nuts-node/issues/623

**Comment by reinkrul** [comment]
We must still add this to the getting started documentation (and maybe to some other chapters).
