### ISSUE TITLE
VCR: Provide page that lists which concepts can be queried with what parameters

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#610]
The concepts and their queries are a somewhat arcane concept, since they're a configurable abstraction and not explicitly documented. It would be helpful if VCR had a page/endpoint that lists the concepts that can be queried and which parameters can be used (auto-generated).

**Comment by reinkrul** [comment]
@woutslakhorst ?

**Comment by woutslakhorst** [comment]
as in: https://nuts-node.readthedocs.io/en/latest/pages/development/3-vc.html#preconfigured-concepts?
