### ISSUE TITLE
Searching for auth creds with only credentialSubject.id doesn't give any results for creds with missing credentialSubject.subject

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#612]
`credentialSubject.id` is part of one of the indices for `NutsAuthorizationCredential`. We have a case where it does not give a result. We're sure it is present and can be resolved by other queries.

Faulty data is available. Will have to investigate if this is the case with all NutsAuthorizatoinCredentials

**Comment by reinkrul** [comment]
I tested it with a random VC from the dev network (with `untrusted=true`) and it worked. Might be something for that particular case?

**Comment by woutslakhorst** [comment]
The `cursor.Seek(seek)` for the DID key is using the `credeltialSubject.id` + `credentialSubject.subject`. But subject is not entered in the auth credential. This means that no record was indexed for this credential (it can't index with nil values). This is on the fine line of 'by design' and 'missing feature'. No report about why something has gone missing is not acceptable though.

**Comment by woutslakhorst** [comment]
nuts-foundation/go-leia#14 can fix this. BUT given the index called `index_subject` on the NutsAuthorizationCredential (https://github.com/nuts-foundation/nuts-node/blob/master/vcr/assets/NutsAuthorizationCredential.config.yaml) indexes on two fields: `credentialSubject.id` and `credentialSubject.subject`, the number of matches for just `credentialSubject.id` will be huge. All eOverdracht authorization credentials are missing the `credentialSubject.subject` field and will therefore all be placed on the same entry! thousands of documents in the same key/value pair in bbolt might be a bad idea.

**Comment by jarimayenburg** [comment]
Might also be good to have better error feedback that tells the client that no index was available for that search. That would avoid a confusing "no organizations found" response.

**Comment by woutslakhorst** [comment]
I changed the way multiple values are stored under a single key. go-leia will always use a sub-bucket. This enables storing an unlimited amount of entries. It's also 10 times faster when storing a 1000 values. DB size will be a bit bigger. It also requires less code in go-leia! So more features, less complexity and better performance

**Comment by woutslakhorst** [comment]
Before mentioned PR of go-leia resolves the mentioned problem.

**Comment by woutslakhorst** [comment]
- [ ] implement go-leia v2.0.0

remove current DB, rewalk DAG, rebuild DB
