### ISSUE TITLE
Log version at startup and include it in diagnostics page

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#62]
Now there's no way to determine what version a running node has. It would be convenient if it was displayed on the status page and logged on node startup;

- Git branch that the build was made from
- Git commit ID
- Build time(?)
- Git tag (for identifying releases?)

**Comment by woutslakhorst** [comment]
not in status, diagnostics.

**Comment by woutslakhorst** [comment]
Checkout https://blog.alexellis.io/inject-build-time-vars-golang/ in how to inject stuff at build time!

We can add the latest git tag in a custom build in the makefile. The docker build should then make use of this new build.
