### ISSUE TITLE
Support encryption/decryption for all supported (per-spec) key types

### ISSUE THREAD

**Issue by dmeijboom** [nuts-foundation/nuts-node#658]
We need an issue to remind ourselves to support encryption/decryption for all supported (per-spec) key types

_Originally posted by @reinkrul in https://github.com/nuts-foundation/nuts-node/issues/656#issuecomment-986664401_

**Comment by reinkrul** [comment]
We only support EC keys, P256, P384 and P521

**Comment by dmeijboom** [comment]
Should be really easy to support as https://github.com/nuts-foundation/crypto-ecies already supports multiple curves.
