### ISSUE TITLE
Fix dependency on dgrijalva/jwt-go

### ISSUE THREAD

**Issue by stevenvegt** [nuts-foundation/nuts-node#670]
dgrijalva/jwt-go has a [GHSA-w73w-5m7g-f7qc](https://github.com/advisories/GHSA-w73w-5m7g-f7qc) and not longer maintained. It is an indirect dependency:

``` go mod why github.com/dgrijalva/jwt-go
# github.com/dgrijalva/jwt-go
github.com/nuts-foundation/nuts-node/auth/services
github.com/privacybydesign/irmago
github.com/dgrijalva/jwt-go
```

Waiting for irma to fix https://github.com/privacybydesign/irmago/issues/188

**Comment by woutslakhorst** [comment]
also via oapicodegen => echo
This one is not a really big issue since we use a different lib to parse JWTs

**Comment by woutslakhorst** [comment]
irma dep fixed by #689

**Comment by dmeijboom** [comment]
Still required by:
- github.com/spf13/viper@v1.7.0
- github.com/labstack/echo/v4@v4.2.1

**Comment by woutslakhorst** [comment]
All libs updated!
