### ISSUE TITLE
Network: check JWS "crit" header when validating transactions

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#677]
RFC004 specifies what JWS headers MUST be understood by the implementation. This field is set when creating new transactions, but never checked. We could check whether we "understood" all parameters present, and whether there were parameters we didn't process/use, but were in the `crit` section.

On the other hand our RFCs are versioned, so we could just remove the section about `crit` (since we have no non-critical parameters anyways).

**Comment by woutslakhorst** [comment]
according to rfc7515, it should be there

**Comment by reinkrul** [comment]
Only necessarily complicates things, could break the network (because some clients might reject certain TXs while others don't). Not fixing.
