### ISSUE TITLE
Human-friendly error should be returned when a private TX is created, but no node DID is configured

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#686]
To help parties already running a Nuts Node migrate to public private VCs as private TXs, the Nuts Node must return a readable, descriptive error when node DID is not configured.

Must be checked.

**Comment by reinkrul** [comment]
There are a few perspectives on this:

- Technically you don't need to configure a node DID to publish a private TX: the TX is signed with a provided key (ID) and the PAL header is encrypted with key agreement keys of the specified PAL DIDs. Missing (or misconfigured) node DID isn't a problem until the parties in the PAL header try to retrieve the transaction payload.

**Comment by woutslakhorst** [comment]
an assertion would be the best for now

**Comment by dmeijboom** [comment]
> Maybe the best we could do for now, without adding lots of complexity, is asserting a node DID is configured when issuing a private transaction (although it might not be the correct one).

^ Looks like a plan. The Node DID is already validated right on startup? (as in: resolving the document and error if it doesn't exist)
