### ISSUE TITLE
Read the Docs: Swagger CSS breaks list style

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#687]
`swagger-ui.css` sets `list-style-type` for `ul` to `none`, which causes all lists to lose their bullet points. E.g.: https://nuts-node.readthedocs.io/en/latest/pages/getting-started/6-adding-authorizations.html

**Comment by woutslakhorst** [comment]
We can remove that line I think. No idea where swagger would render unwanted bullets...

**Comment by woutslakhorst** [comment]
Fixed by #923
