### ISSUE TITLE
Authentication issues when node is out of sync

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#699]
When starting a new Nuts node, you need to configure a bootstrap node to sync the existing network DAG from. However, if the bootstrap node sends a node DID the new node will attempt to authenticate it upon connecting. It does this by resolving the node DID on the VDR. The VDR, however, is empty since it's a new node. So it can't authenticate the bootstrap node's connection, and the node will immediately disconnect. This prevents new nodes from getting in sync with bootstrap nodes that provide their node DID (which all nodes should do, eventually).

This not just happens with new nodes: it can also happens when the node is so out-of-sync (after some downtime) that it misses transactions crucial for authenticating the bootstrap node.

Thus, nodes need to be able to sync (at least with bootstrap nodes), when they can't authenticate the node DID (yet). Solutions:

- When a new connection can't be authenticated, but it is a bootstrap node, do not disconnect. But also don't mark the connection as trusted. That way it can be used for syncing, but not for exchanging private VCs. After syncing, the next (re)connect with the bootstrap node will be able to authenticate.
- Auto-trust node DIDs sent by bootstrap nodes (not a very good idea)
- Delay node DID authentication until required (exchanging private VCs). Opens up new issues to solve (what if multiple peers, some are attackers/spoofers, send the same node DID).

@woutslakhorst @dmeijboom

**Comment by woutslakhorst** [comment]
- mark connection as not-authenticated (but mark with DID) but accept TXs anyway. When a DID Document update happens (with a NutsComm service), disconnect all connections marked with that DID then reconnect.

**Comment by dmeijboom** [comment]
I would be in favour of this:

> When a new connection can't be authenticated, but it is a bootstrap node, do not disconnect. But also don't mark the connection as trusted. That way it can be used for syncing, but not for exchanging private VCs. After syncing, the next (re)connect with the bootstrap node will be able to authenticate.

**Comment by woutslakhorst** [comment]
⬆️ would be doable to implement.
