### ISSUE TITLE
Nats consumer not setup correctly

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#711]
starting the node gives:

```
ERRO[0002] failed to setup NATS handler: nats: no stream matches subject 
```

When looking at https://github.com/nats-io/nats.go/blob/main/js_test.go, several are things are missing:

- A stream has to be setup. How to name a stream? Which subjects can the stream contain?
- Consumers have to be setup. They have to be unique. (Also over a cluster)
- Subscriptions have to be bound to the consumer/stream.
- The right options have to be set for our use-case.

A minimal example to have the server started and events delivered:

```
func (p *protocol) setupNatsHandler() error {
	_, js, err := p.eventsConnectionPool.Acquire(p.ctx)
	if err != nil {
		return err
	}

	if _, err = js.AddStream(&nats.StreamConfig{Name: "privates"}); err != nil { // todo stream name
		return err
	}

	// todo name
	todoId := make([]byte, 32)
	rand.Read(todoId)
	consumerId := hash.SHA256Sum(todoId).String()

	if _, err = js.AddConsumer(
		"privates",
		&nats.ConsumerConfig{
			Durable:        consumerId,
			DeliverSubject: events.PrivateTransactionsSubject,
			AckPolicy:      nats.AckExplicitPolicy,
		}); err != nil { // todo consumer config
		return err
	}

	if _, err = js.Subscribe(events.PrivateTransactionsSubject, func(msg *nats.Msg) {
		if err := p.handlePrivateTx(msg); err != nil {
			log.Logger().Errorf("failed to handle private transaction: %v", err)

			if err := msg.Nak(); err != nil {
				log.Logger().Errorf("failed to NACK private transaction event: %v", err)
			}

			return
		}

		if err := msg.Ack(); err != nil {
			log.Logger().Errorf("failed to ACK private transaction event: %v", err)
		}
	}, nats.AckExplicit(), nats.Bind("privates", consumerId)); err != nil { // todo set consumer name and binding!
		return err
	}

	return nil
}
```

Proposal for current state of the node is to remove the event queue from the private TX sending and use a direct call. Using this PR: #708. This will most likely require the V2 protocol to bind to the replayingDAGPublisher like the v1 protocol does.

**Comment by dmeijboom** [comment]
It's true that there are some things missing (see: #717).

> A stream has to be setup. How to name a stream? Which subjects can the stream contain?

Indeed. It makes sense for the private transactions to have its own stream. When we add events/subjects we need to think about the stream it will be send to.

> Consumers have to be setup. They have to be unique. (Also over a cluster)

I don't think this is required.

> Subscriptions have to be bound to the consumer/stream.

This can be done implicitly. We only have to define the subject to listen to and the NATS client will automatically select the correct stream.

> The right options have to be set for our use-case.

Indeed.
