### ISSUE TITLE
Disconnect when a Nuts node connects to itself

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#718]
When service discovery is implemented, parties can publish another party's `NutsComm` endpoint, causing the other party's node to connect to itself. It does not look like it could very much harm at this point, but it's not very neat either.

When a connection is made and the peer presents the same ID as the local node, it should disconnect (and probably not try to connect again).

**Comment by woutslakhorst** [comment]
No it should check the TLS certificate, otherwise you'll introduce a future blocker for clustering.

**Comment by dmeijboom** [comment]
> No it should check the TLS certificate, otherwise you'll introduce a future blocker for clustering.

Not sure what you mean. When clustered the nodes won't have the same Node DID right? Or do they? Also, do we verify the thumbprint in the certificate or something? Not sure if that's the right thing to do as you can use a single certificate for multiple nodes (by using multiple SANs in the certificate).

**Comment by woutslakhorst** [comment]
the NodeDID is currently the vendor DID. If for clustering multiple nodes share the same vendor, they would share the same NodeDID (unless we design it differently). It's also expected that any Node API is behind a reverse-proxy that also load balances requests over the different node (assumption here). This means a single domain and certificate will be true for multiple nodes.

**Comment by reinkrul** [comment]
Check whether this is still relevant.

**Comment by reinkrul** [comment]
@gerardsn is this still a thing with nodeDID authentication?

**Comment by gerardsn** [comment]
it does not connect to itself.
if someone else publishes the node's NutsComm endpoint it will fail authentication and disconnect + not try again for a while

**Comment by reinkrul** [comment]
It only connects to itself when it is configured as bootstrap node (which makes no sense). It is filtered from discovered node list;

```go
func (n *Network) connectToDID(nodeDID did.DID, node did.Document) {
	if !nodeDID.Empty() && node.ID.Equals(nodeDID) {
		// Found local node, do not discover.
		return
	}
...
}
```

Looks OK for now.
