### ISSUE TITLE
Retry doesn't stop when node does not have a nodeDID

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#747]
check if a VC can be created for this node, that should already give a problem since that would require a did Node?

This is annoying since other nodes that do not have a did node set will get this error even if the TX is not for them...

```
network-node-three-1  | time="2022-01-14T15:04:00Z" level=error msg="retry of TransactionPayloadQuery failed: failed to decrypt PAL header (tx=f4045fcbd996919ed6171fcbf9403bbce1fcdf982c2ef169aefbd8d259635b04): node DID is not set" module=Network
```

**Comment by dmeijboom** [comment]
For the Node DID we currently use the `transport.NodeDIDResolver` interface. There is no guarantee (even thought it's currently the case) that repeated calls on `NodeDIDResolver.Resolve()` will return the same result.

We also discussed resolving the Node DID automatically somehow. This means that a new implementation which automatically resolves the Node DID can actually return a Node DID later on even though previous calls returned an error or nil.

**Comment by woutslakhorst** [comment]
It's not a requirement to set a nodeDID. So "private" network users get bothered by lots of error messages....

**Comment by dmeijboom** [comment]
> It's not a requirement to set a nodeDID. So "private" network users get bothered by lots of error messages.... But how to distinguish between not willing to set and not set yet?
> 
> Would that require replaying the DAG when changing your nodeDID?

I don't think there is a way to distinguish between purposely not setting your node DID or forgetting to set it. However, we could try rate limiting the `Resolve()` calls? An alternative would be to add a flag which disables resolving the node DID for your own node.

**Comment by woutslakhorst** [comment]
*not set yet* could actually be detectable: If you have DID documents under your control and those have a NutsComm endpoint but you didn't set your nodeDID and auto-detect fails => startup WARNING/ERROR/failure?

Then the retry job can just ignore all jobs when no nodeDID is known.

**Comment by reinkrul** [comment]
check docs
