### ISSUE TITLE
Crypto: switch to Vault KV store v2

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#766]
See https://github.com/nuts-foundation/nuts-node/pull/762

**Comment by woutslakhorst** [comment]
@stevenvegt what was the reason to choose `v1`?

**Comment by stevenvegt** [comment]
Well, the docs of vault make it quite clear: https://www.vaultproject.io/docs/secrets/kv

>When running the kv secrets backend non-versioned, only the most recently written value for a key will be preserved. The benefits of non-versioned kv is a reduced storage size for each key since no additional metadata or history is stored. Additionally, requests going to a backend configured this way will be more performant because for any given request there will be fewer storage calls and no locking.

We don't need versioning, so: faster, less storage.

I suppose you think that v2 is shomehow better or newer. If they had called it "unversioned" or "versioned" we would not have this confusion.

**Comment by reinkrul** [comment]
Switching to v2 doesn't have any clear advantages for now.
