### ISSUE TITLE
Additional OrganizationCredential subject information not returned on search

### ISSUE THREAD

**Issue by jarimayenburg** [nuts-foundation/nuts-node#768]
I'm researching the ability to add identifiers to Organization Credentials. When I try to create an OC using the following request
```
POST /internal/vcr/v1/vc

{
  "type": "NutsOrganizationCredential",
  "issuer": "did:nuts:HANN15y73URwZdYNUKiEKYXssQynhHCYSHM6P9Yz2fQw",
  "credentialSubject": {
		"id": "did:nuts:HANN15y73URwZdYNUKiEKYXssQynhHCYSHM6P9Yz2fQw",
		"organization": {
			"name": "HINQ",
			"city": "Den Haag",
			"identifiers": {
				"agb": "12345678"
			}
		}
	}
}
```

I get a response telling me that the organization was created with the correct subject information:
```
...
	"credentialSubject": {
		"id": "did:nuts:HANN15y73URwZdYNUKiEKYXssQynhHCYSHM6P9Yz2fQw",
		"organization": {
			"city": "Den Haag",
			"identifiers": {
				"agb": "12345678"
			},
			"name": "HINQ"
		}
	},
...
```

However, if I then search for an organization using the following request, I only get the name and city back
```
GET /internal/didman/v1/search/organizations?query=HINQ

...
		"organization": {
			"city": "Den Haag",
			"name": "HINQ"
		}
...
```

The new "identifiers" field is missing now.

**Comment by jarimayenburg** [comment]
@woutslakhorst I'm tagging you because of our conversation last friday

**Comment by reinkrul** [comment]
@stevenvegt is this applicable to the new v2 API we're designing as we speak?

**Comment by jarimayenburg** [comment]
It works if I use a different VC (e.g. NutsOrganizationCredentialV2) and search using the regular concept searching API

**Comment by woutslakhorst** [comment]
This is by design for "known" VCs.
Workarounds for now:
- define your own VC and use as is (like you said)
- wait a few weeks for official identifier support ;)
