### ISSUE TITLE
Echo server is not exposed to the outside world by default

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#78]
Since it binds on `localhost:1323` you'd have to configure it to have any endpoints being available from the outside at all, which is not very convenient.

```
http:
  default:
    address: :1323
```

Maybe better: bind on `:1323` (all interfaces) by default so it's available from the outside (Docker container e.g.), and add some extra checks to strict mode, disallowing unsafe configuration. Maybe disallow this 'bind to all interfaces' in strict mode to enforce administrators to provide alternative bindings?

**Comment by woutslakhorst** [comment]
doesn't disallow bind to all interfaces be a nuisance when using a containerized environment?

**Comment by reinkrul** [comment]
@woutslakhorst you made me realize what defaults are safe highly depends on the environment you're running in. Binding to all interfaces (by default) could be unsafe when running on bare metal but should be fine in a Docker or other containerized environment.

I suppose it will most often be run inside a container I guess making it the most convenient for that environment is the right choice. In other words: change the default bind address to all interface (`:1323`).
