### ISSUE TITLE
Validate node DID being set when the NutsComm endpoint was set

### ISSUE THREAD

**Issue by dmeijboom** [nuts-foundation/nuts-node#787]
It would be nice to show an error message that the node DID was not set when we can find NutsComm endpoints on DID documents owned by the node. As that's clearly a misconfiguration.

**Comment by woutslakhorst** [comment]
For production as well? Since auto-detect is now only working for non-strict settings.

**Comment by dmeijboom** [comment]
> For production as well? Since auto-detect is now only working for non-strict settings.

Yeah I think so. It still makes sense for production right? As the user probably forgot to set the node did.

**Comment by woutslakhorst** [comment]
It could also indicate lingering private keys or a private key storage that is used by multiple node setups. All enough reasons to throw errors.
 👍

**Comment by reinkrul** [comment]
Nice to have, but not required (also not required for production)

**Comment by reinkrul** [comment]
It already logs a message when node DID is set (which generally must be the case for acc/prd nodes), so no need to fix this.
