### ISSUE TITLE
VDR: Concurrency integration test sometimes fails

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#799]
```
DEBU[0005] Stopping gRPC connection manager              module=Network
--- FAIL: TestVDRIntegration_ConcurrencyTest (2.50s)
    integration_test.go:301: 
        	Error Trace:	integration_test.go:301
        	            				asm_amd64.s:1581
        	Error:      	Received unexpected error:
        	            	missing clock value
        	Test:       	TestVDRIntegration_ConcurrencyTest
        	Messages:   	unable to update doc with a new service
```

https://app.circleci.com/pipelines/github/nuts-foundation/nuts-node/2861/workflows/5095a23a-4eff-4b45-9a70-4334768d3ed8/jobs/3080

**Comment by woutslakhorst** [comment]
The `lastTransactionTracker` holds this state and is called from the dag.Publisher not as DAG Subscriber. That last one has transactional context the first one does not.

We could split the subscriber into 2: 1 with TX context (XOR, IBLT) and 1 without (dag.Publisher). That latter one will then most likely disappear and be swapped for Nats Events.
