### ISSUE TITLE
Replace bindata with fs.Embed

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#80]
See https://blog.golang.org/go1.16

- Replace bindata with 1.16's `fs.Embed`

**Comment by reinkrul** [comment]
Fixed

**Comment by woutslakhorst** [comment]
Not all embedded resources are replaced with fs.Embed.

**Comment by reinkrul** [comment]
> Not all embedded resources are replaced with fs.Embed.

Renamed the issue.
