### ISSUE TITLE
Ambiguous error when node's certificate has expired (outbound connections)

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#818]
When a node connects outbound while its certificate (of the local node) is expired, the error message being logged isn't very clear about what went wrong:

`time="2022-02-12T05:44:23Z" level=info msg="Couldn't connect to peer, reconnecting in 194 seconds (peer=nuts.reinkrul.nl:5555,err=unable to connect: context deadline exceeded: connection closed before server preface received)" module=Network`

On the server side, nothing's logged. Maybe we can do some sanity checks or return more useful errors.

**Comment by woutslakhorst** [comment]
The opposite does generate an error (the client that connects to an expired server cert.)
