### ISSUE TITLE
Auth: implement oauth endpoint selection by bolt

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#83]
Endpoints are specified in the DID Documents. The RFC describes the use of compound endpoints to use endpoints from another DID document. This needs to be supported by Nuts Auth.

**Comment by reinkrul** [comment]
The RFC is too vague on this point, needs clarification:

> Each service MUST define an `oauth` serviceEndpoint. This endpoint is either the URL of the authorization server, or in case of a compound service an URI which resolves to another service. In order for the client to resolve the authorization server endpoint it MUST look up the `auth` service endpoint of the service.

- does "it MUST look up the `auth` service endpoint of the service." apply to the compound endpoints?
- is `auth` a typo which should've been `oauth`?

**Comment by woutslakhorst** [comment]
maybe we should solve the service CRDT problem first, which might result in abandoning the service reference concept...

**Comment by woutslakhorst** [comment]
> maybe we should solve the service CRDT problem first, which might result in abandoning the service reference concept...

services will be immutable, but still referenceable via URI query params. So RFC003 needs a clarification?

**Comment by woutslakhorst** [comment]
there's a bit more involved:

- create a bearer token => requires the oauth service id. There's support for scope <- use as bolt? Renaming to service might be better
- use vdr to resolve the service ID,
- create token
- The token is only useable at the url defined by the service ID. Now it's up to the user to use it. The service could return the URL/Service as return value next to the token.
