### ISSUE TITLE
Network: conversationManager should limit number of conversations to avoid DoS by creating many conversations

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#843]

**Comment by woutslakhorst** [comment]
Don't know if this is an issue since the initiator creates the conversation, not an external node.

**Comment by reinkrul** [comment]
The receiver does not register a conversation as well?

**Comment by woutslakhorst** [comment]
> The receiver does not register a conversation as well?
no

**Comment by woutslakhorst** [comment]
#861 is solved, this is no longer an issue.
