### ISSUE TITLE
VCR: LDProof expiry field is not according to JSON-LD context (potential vulnerability)

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#857]
Our JSON-LD `Proof` type specifies `expirationDate`, but the field does not exist in the JSON-LD context we specify (https://w3c-ccg.github.io/lds-jws2020/contexts/lds-jws2020-v1.json): it is named `expires` there.

Consequence is that (according to @stevenvegt) the field isn't part of the actual signature. This could mean an attacker can alter the expiry date, making VCs/VPs that have expired valid again by adjusting the date, while the signature stays correct.

**Comment by woutslakhorst** [comment]
true, `expirationDate` is a VC field.
