### ISSUE TITLE
Provide API to return vendor DID

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#869]
It would be useful to have an API that returns the node's DID.

Use case from @jarimayenburg : EHR wants to search for credentials that have been issued to a certain care organization, excluding the ones that were issues by the local vendor. Instead of having to configure the vendor DID(s) (which will often equal the node DID), it would be useful to resolve it by querying the Nuts node.

Could simply be added to the diagnostics page but since that's not versioned or really intended to be part of vendor integration, a separate API would be better.

Maybe in the future, a list of all DIDs that can be managed by the local node (as suggested by https://github.com/nuts-foundation/nuts-node/pull/611). But in the current state it's hard to get a definite, accurate answer to "which DID documents can I manage", because one would have to do a reverse lookup on the DID documents controllers ("which DID documents have my vendor DID as controller"). The current memory/BBolt implementation of VDR do not support this, and it isn't very straightforward to support this either (unless we migrate to something like `go-leia`).

**Comment by woutslakhorst** [comment]
The current design idea is to have a local administration for you as a vendor and your customer. You generate DIDs for each of those and add the DID to your administration, you can then query your own administration for your own customers. It seams to me some of this responsibility is given to the Nuts node in this use-case. I do not think that's the way to go. You tell the node what the vendor DID is, not the other way round.

**Comment by jarimayenburg** [comment]
Sure, but the current design also generates OIDs if you don't supply one yourself. Therefore, it would still be nice to query all this information from the node, even if it's just to store it in your own administration.

The alternative now is to go search for an organization DID and then use the issuer DID to figure out the DID of the vendor.

I'm all for a minimalist implementation, but the Nuts node is already challenging for new implementors to comprehend and use as is, so all convenience APIs are much appreciated.

**Comment by reinkrul** [comment]
The concept of vendor/node DID will ultimately disappear when we've completely adopted OpenID4VP and removed the Nuts gRPC network. So no need for this API in the future.
