### ISSUE TITLE
DID document updates from the network should not be stopped by deactivated

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#878]
These checks could prevent an update in the case of a parallel update. If A and B are parallel, A is a deactivate and B is a regular update. Nodes that proces A before B will not apply B. Nodes that apply B before A will merge the two and the result will be B.

**Comment by reinkrul** [comment]
First step would be to monitor DID documents that are reactivated, and show it in the diagnostics. That way we can detect possible fraudulent behaviour.

**Comment by woutslakhorst** [comment]
> First step would be to monitor DID documents that are reactivated, and show it in the diagnostics. That way we can detect possible fraudulent behaviour.

We could do this via a stored flag inside the VDR. It would only be used for diagnostics, it'll be set only without a possibility to reset. Although that last part may cause accidents to be persistent till the end of time....
