### ISSUE TITLE
Mark resurrected DID Documents as such and show them in diagnostics

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#879]
Consider the following:

- Given A and B are updates of the same DID Document in parallel
- A is a deactivation and B is a regular update. Due to the parallelism, the deactivation must not block the update. It'll be a conflict but manageable.
- C is a TX that deactivates the controller of a DID Document.
- D is a DID Document update that uses the previous of C as controller/signing key.
- D would be a legit transaction because source TX will point to a valid TX, just not the latest one....
- D may not be blocked by C since that would introduce another parallel attack case.

D does not currently point to the previous transaction of the same DID Document when another controller is used. It's therefore not possible to check if the previous TX of the DID Document was a deactivation. It's therefore a possibility to resurrect deactivated DID Documents without notice.

**Comment by woutslakhorst** [comment]
Resurrection of deactivated DIDs could indicate a stolen private key. There should be a way to detect this. Preventing is almost impossible, since every blockade also adds an attack vector.

An idea is to add a deactivated flag to DID Document metadata. Once set it'll always be set. Then diagnostics can tell us if a document has ever been deactivated and is no longer deactivated.

**Comment by gerardsn** [comment]
Makes sense to me. Would you use this flag for anything other than marking this DID as deactivated?

**Comment by woutslakhorst** [comment]
> Makes sense to me. Would you use this flag for anything other than marking this DID as deactivated?

it's hard to oversee where this would be beneficial at this point.

**Comment by reinkrul** [comment]
But we might have to reconsider the usefulness of key rotation at that point. Would be useful if key rotation can still be used to mitigate potentially leaked (or known lkeaked) keys.

**Comment by woutslakhorst** [comment]
> But we might have to reconsider the usefulness of key rotation at that point. Would be useful if key rotation can still be used to mitigate potentially leaked (or known lkeaked) keys.

Only if old keys were to be deleted and that you'll most likely not know from eachother

**Comment by woutslakhorst** [comment]
Moving to next milestone

**Comment by woutslakhorst** [comment]
Evaluating this 6 months later:

It's either a conflict due to the fact the DID update MUST point to the previous one or it's an invalid update since the previous update was a deactivation.

**Comment by reinkrul** [comment]
I did a quick search, and I think we're missing documentation on how to find out which DID documents are conflicted?
