### ISSUE TITLE
server flag --network.bootstrapNodes adds nodes 3 times

### ISSUE THREAD

**Issue by gerardsn** [nuts-foundation/nuts-node#88]
`nuts server --network.bootstrapNodes node1:5555` results in 
`network.bootstrapNodes -> [node1:5555 node1:5555 node1:5555]`

`nuts server --network.bootstrapNodes node1:5555,node2:555` results in 
`network.bootstrapNodes -> [node1:5555 node2:5555 node1:5555 node2:5555 node1:5555 node2:5555]`

**Comment by woutslakhorst** [comment]
each time `flags.Parse()` is called, it's duplicated. Maybe the calls can be removed?
