### ISSUE TITLE
Move Nuts specific credential types validation and creation?

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#885]

**Comment by woutslakhorst** [comment]
The question is where to place validations. Creating VCs without validation opens up the possibility to do things wrong...

**Comment by reinkrul** [comment]
Maybe this should wait until we externalize it with schemas and business rules for validation? It would aid supporting other VC types, but at the same time allows this issue to be solved easily?

**Comment by woutslakhorst** [comment]
Will close it for now, should be part of business rules.
