### ISSUE TITLE
Network: make failing connectors less chatty

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#891]
When Nuts nodes are discovered through their `NutsComm` service published in their DID documents, the node will start connection to these.

It will try to connect with an increasing backoff, ultimately trying to connect just once per hour. However, when a restart occurs it will start over trying to connect (intervals are more or less multiplied by 1.5, so after 1s, 2s, 3s, 5s, 7s, 11s, 15s etc). When a remote node experiences some temporary downtime this work very well, because the local node quickly tries to reconnect. But when a published address is abandoned (e.g. because the DID document is abandoned, or the private key was lost) the local node will still try to reconnect at a short interval after restarting. This leads to very cluttered logs, especially when there the number of abandoned Nuts node addresses grows.

Best solution is probably to let the back-off survive restarts (persist the connector backoff).

@woutslakhorst your thoughts?

**Comment by woutslakhorst** [comment]
A persistent backoff would be the best candidate. The loglevel can also change when the backoff increases: Warn->Info->Debug
