### ISSUE TITLE
Node exits during startup with unhelpful error message

### ISSUE THREAD

**Issue by stevenvegt** [nuts-foundation/nuts-node#934]
After an update of my local Nuts node, the node exists during startup giving me the cryptic message: `DID document does not contain a keyAgreement key`.
This is not very helpful. Perhaps the node should not exit, of if it is really a deal breaker, explain how to fix it.

**Comment by woutslakhorst** [comment]
It's an invalid node configuration, so the exit is sound. But it could be more helpful by saying you have to add a `keyAgreement` key to the configured DID Document.
