### ISSUE TITLE
Network Protocol v2: which errors should be returned to the remote peer?

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#973]
Network protocol v2 currently returns any error from the handler (`Handle()`) which most probably sends them back as a (custom, application level) error to the peer. But this might not be the correct course of action, since it also discloses information about the internal state of the local node (e.g. `WritePayload()` fails, or `FindBetweenLC()`).

Thus, all errors that can be returned should probably be specified by the RFC? And if another error occurs, it should probably just be captured, logged and obfuscated into something like "client side error" (or better).

**Comment by woutslakhorst** [comment]
So shouldn't this be an issue for nuts-specification then?

**Comment by reinkrul** [comment]
> So shouldn't this be an issue for nuts-specification then?

I'm not 100% sure local errors are sent back over the (gRPC) wire, so I wanted to test that first.

**Comment by reinkrul** [comment]
Implement https://github.com/nuts-foundation/nuts-specification/pull/182
