### ISSUE TITLE
Auth: support organizations having multiple, non-matching credentials

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#987]
Currently, only the first organization credential found for an organization is used when creating or validating contracts. This can create issues where the organization name/city in the contract doesn't match the name/city when validating the contract.

Use case might be when an organization changes its name or location(?). And it's bound to happen during development/testing.

Solution is probably to:
- Accept an organization VC in `Notary.DrawUpContract` instead of providing organization DID
- Check the signed contract against all resolved organization VCs in `Notary.validateIssuer`

**Comment by woutslakhorst** [comment]
It would also be possible to extract the name/city from the signed contract and use those to find a valid VC

**Comment by woutslakhorst** [comment]
Proposed solution:

- change validation to query organizational credential based on contract name/city. Now a NotNil query is used and later the result of that query is matched against the name/city from the contract.
- add option to API to provide VC that must be used to construct contract. (Optional)
